package chartvalues

import (
	"fmt"
	"strings"

	"shepherd/internal/beacon"
)

// RequiredOperatorExtraEnvVar names an env var the k8s-monitoring chart's
// OWN validation (collectors.validate.remoteConfig, live in the chart's
// templates/_validations.tpl at PinnedChartVersion) unconditionally requires
// to exist in a collector's alloy.extraEnv wherever remoteConfig.enabled is
// true — regardless of what auth mechanism that collector actually uses.
// This package's rendered auth never reads it (see the header comment
// Render emits): the check is legacy from the chart's Grafana-Cloud-specific
// origin and was never generalized when generic basic-auth remoteConfig
// support was added, confirmed by reading _validations.tpl and
// _collector_remoteConfig.tpl directly, not assumed.
//
// Render deliberately does NOT emit this itself. The two ways to satisfy it
// from values alone are (a) alloy.extraEnv, a field the vendored
// values.schema.json does not declare for alloy-collector.properties.alloy —
// it belongs to the wrapped grafana/alloy chart's own schema, which this
// package does not vendor (see doc.go's scope boundary) — or (b) flipping
// remoteConfig.secret.create to false, which DOES auto-satisfy this check
// (confirmed empirically against the real chart) but as an unwanted side
// effect ALSO makes secrets.usesSecret true for remoteConfig.tls.{ca,cert,key}
// unconditionally, rendering a tls_config block that reads
// remote.kubernetes.secret.<name>.data["ca"|"cert"|"key"] from THIS SAME
// credentials secret — keys nothing in this package ever asks the operator
// to provision, so Alloy would fail evaluating that expression at runtime.
// Between "leave a schema-unprovable field out and document a one-line
// operator addition" and "silently ship a config with a dangling secret-key
// reference", this package chooses the former. See Render's header comment
// for the operator-facing version of this note.
const RequiredOperatorExtraEnvVar = "GCLOUD_RW_API_KEY"

// Render turns a validated Spec into a k8s-monitoring Helm values LAYER:
// YAML text meant to be passed as one of possibly several `-f` files
// alongside the operator's own (`helm upgrade ... -f their-values.yaml -f
// this-file.yaml`), never the operator's only values file. See doc.go for
// why the surface stops here.
//
// The shape (top-level cluster.name, collectors.<name>.remoteConfig.*) and
// every field name it sets are not invented: schema_test.go asserts each one
// against testdata/values.schema.json, walked at test time rather than
// copied from memory into a comment that could drift.
func Render(spec Spec) ([]byte, error) {
	if err := Validate(spec); err != nil {
		return nil, err
	}

	poll := spec.PollFrequency
	if poll == "" {
		poll = DefaultPollFrequency
	}
	// Alloy's remotecfg block takes a base URL with no trailing slash
	// (docs/spec.md's e2e fixture: "url http://shepherd:8080", not
	// ".../"). Normalizing here means the guided form does not need its
	// own "no trailing slash" validation message for what is purely a
	// formatting nicety.
	shepherdURL := strings.TrimSuffix(spec.ShepherdURL, "/")

	roles := make([]string, 0, len(spec.Roles))
	want := make(map[string]bool, len(spec.Roles))
	for _, r := range spec.Roles {
		want[r] = true
	}
	for _, r := range validRoles() { // canonical order: deterministic output regardless of input order
		if want[r] {
			roles = append(roles, r)
		}
	}

	var sb strings.Builder
	sb.WriteString("# Generated by Shepherd (Collectors → Connect a cluster) for Grafana's\n")
	fmt.Fprintf(&sb, "# k8s-monitoring chart, version %s.\n", PinnedChartVersion)
	sb.WriteString("#\n")
	sb.WriteString("# This is not a complete values.yaml: it only points the collectors below at\n")
	sb.WriteString("# Shepherd. Apply it with your own values file and shepherd-credentials.yaml,\n")
	sb.WriteString("# which loads each collector's agent token from a Kubernetes Secret:\n")
	sb.WriteString("#   helm upgrade ... -f your-values.yaml -f shepherd-layer.yaml -f shepherd-credentials.yaml\n")
	sb.WriteString("# No secret is ever in either file.\n")
	sb.WriteString("\n")

	sb.WriteString("cluster:\n")
	fmt.Fprintf(&sb, "  name: %s\n\n", yamlDoubleQuote(spec.ClusterName))

	sb.WriteString("collectors:\n")
	for _, role := range roles {
		fmt.Fprintf(&sb, "  %s:\n", collectorName(role))
		sb.WriteString("    remoteConfig:\n")
		sb.WriteString("      enabled: true\n")
		fmt.Fprintf(&sb, "      url: %s\n", yamlDoubleQuote(shepherdURL))
		fmt.Fprintf(&sb, "      pollFrequency: %s\n", yamlDoubleQuote(poll))
		sb.WriteString("      auth:\n")
		sb.WriteString("        type: basic\n")
		fmt.Fprintf(&sb, "        usernameFrom: %s\n", yamlSingleQuote(fmt.Sprintf("sys.env(%q)", beacon.DefaultTokenIDEnv)))
		fmt.Fprintf(&sb, "        passwordFrom: %s\n", yamlSingleQuote(fmt.Sprintf("sys.env(%q)", beacon.DefaultTokenSecretEnv)))
		sb.WriteString("      extraAttributes:\n")
		fmt.Fprintf(&sb, "        role: %s\n", yamlDoubleQuote(role))
		if spec.Tenant != "" {
			fmt.Fprintf(&sb, "        tenant: %s\n", yamlDoubleQuote(spec.Tenant))
		}
	}

	return []byte(sb.String()), nil
}

// yamlDoubleQuote renders s as a YAML double-quoted scalar. Callers only
// ever pass Validate-checked values (bounded: no quote, no backslash, no
// control characters), so this never needs YAML's backslash-escape rules —
// it exists to make every emitted scalar's quoting explicit and uniform
// rather than relying on plain-scalar rules that vary by content.
func yamlDoubleQuote(s string) string { return `"` + s + `"` }

// yamlSingleQuote renders s as a YAML single-quoted scalar: double quotes
// inside s (every value this is used for is a sys.env("...") expression)
// are literal in single-quoted YAML, so no escaping is needed as long as s
// itself never contains a single quote — true for every caller here, all of
// which build the string themselves from constants this package controls.
func yamlSingleQuote(s string) string { return "'" + s + "'" }
