apiVersion: v2
name: shepherd
description: Self-hosted Grafana Alloy fleet manager
type: application
version: 0.6.1
appVersion: "0.2.1"
keywords:
  - alloy
  - grafana
  - observability
  - fleet
home: https://github.com/procoduck/shepherd
