// Code generated by "make gen-alloy-version" from deploy/versions.env. DO NOT EDIT.

// Package version exposes build-time version constants.
package version

// AlloySchemaVersion is the pinned Alloy schema version this build serves.
// Source of truth: ALLOY_VERSION in deploy/versions.env.
const AlloySchemaVersion = "alloy-v1.18.1"
