// visual-toolbar-save.spec.ts — B4: the toolbar's name field, matcher chip
// editor, save (create/update), and existing-pipeline load flow.
import { expect } from '@playwright/test';
import { basicScenario, pipeline } from '../fixtures/factories';
import { appAdmin } from '../fixtures/personas';
import { schemaFixture } from '../fixtures/schema-fixture';
import { test } from '../fixtures/test';

const mockGraph = {
  kind: 'alloy-graph/v1',
  schema_version: 'alloy-v1.18.1',
  nodes: [],
  edges: [],
  bindings: [],
  viewport: { x: 0, y: 0, zoom: 1 },
  meta: { created_with: 'shepherd-parser' },
};

test.describe('visual builder toolbar — new pipeline', () => {
  test.beforeEach(async ({ page, api }) => {
    await api.loginAs(appAdmin);
    const s = basicScenario();
    api.seed({
      orgs: [s.org],
      schema: schemaFixture,
      visualRenderResult: {
        content: '// generated by shepherd visual builder\n',
        node_map: {},
        diagnostics: [],
      },
    });
    await page.goto('/pipelines/visual/new');
    await page.waitForSelector('[data-testid="visual-builder"]', { timeout: 10_000 });
    await page.waitForSelector('[data-testid="palette-search"]', { timeout: 8_000 });
  });

  test('Save is disabled with a tooltip until a matcher is added', async ({ page }) => {
    const saveBtn = page.locator('[data-testid="toolbar-save"]');
    await expect(saveBtn).toBeDisabled();
    await expect(saveBtn).toHaveAttribute('title', /matcher/i);
  });

  test('rejects a malformed matcher inline and accepts a well-formed one', async ({ page }) => {
    const input = page.locator('[data-testid="matcher-input"]');
    await input.fill('not-a-matcher');
    await input.press('Enter');
    await expect(page.locator('[data-testid="matcher-error"]')).toBeVisible();
    await expect(page.locator('[data-testid="matcher-chip"]')).toHaveCount(0);
    await expect(page.locator('[data-testid="toolbar-save"]')).toBeDisabled();

    await input.fill('cluster="prod-eu-1"');
    await input.press('Enter');
    await expect(page.locator('[data-testid="matcher-chip"]')).toHaveCount(1);
    await expect(input).toHaveValue('');
    await expect(page.locator('[data-testid="toolbar-save"]')).toBeEnabled();
  });

  test('x removes a matcher chip', async ({ page }) => {
    const input = page.locator('[data-testid="matcher-input"]');
    await input.fill('cluster="prod-eu-1"');
    await input.press('Enter');
    await expect(page.locator('[data-testid="matcher-chip"]')).toHaveCount(1);

    await page.click('[data-testid="matcher-remove-0"]');
    await expect(page.locator('[data-testid="matcher-chip"]')).toHaveCount(0);
    await expect(page.locator('[data-testid="toolbar-save"]')).toBeDisabled();
  });

  test('validity chip shows Valid on an empty (error-free) graph', async ({ page }) => {
    const chip = page.locator('[data-testid="toolbar-validity"]');
    await expect(chip).toContainText('Valid');
  });

  test('validity chip click expands the problems tab of the bottom drawer', async ({ page }) => {
    await expect(page.locator('[data-testid="bottom-drawer"]')).toHaveClass(/h-8/);
    await page.click('[data-testid="toolbar-validity"]');
    await expect(page.locator('[data-testid="bottom-drawer"]')).toHaveClass(/h-64/);
  });

  test('fills name, adds a matcher, saves, and navigates to the new pipeline', async ({
    page,
    api,
  }) => {
    await page.locator('[data-testid="toolbar-name"]').fill('checkout-metrics');
    const input = page.locator('[data-testid="matcher-input"]');
    await input.fill('cluster="prod-eu-1"');
    await input.press('Enter');

    await page.locator('[data-testid="toolbar-save"]').click();

    await expect(page).toHaveURL(/\/pipelines\/pip-\d+$/, { timeout: 5_000 });

    const creates = api.calls('PipelineService/CreatePipeline');
    expect(creates).toHaveLength(1);
    const body = creates[0].body as Record<string, unknown>;
    expect(body.name).toBe('checkout-metrics');
    expect(body.matchers).toEqual(['cluster="prod-eu-1"']);
    expect(body.source).toBe('visual');
    expect(body.wizardState).toBeTruthy();
    expect((body.wizardState as Record<string, unknown>).kind).toBe('alloy-graph/v1');
  });

  test('surfaces server render diagnostics as a toast and does not save', async ({ page, api }) => {
    api.seed({
      visualRenderResult: {
        content: '',
        node_map: {},
        diagnostics: [{ layer: 'L1', code: 'label_collision', node_id: 'n1', message: 'boom' }],
      },
    });
    const input = page.locator('[data-testid="matcher-input"]');
    await input.fill('cluster="prod-eu-1"');
    await input.press('Enter');
    await page.locator('[data-testid="toolbar-save"]').click();

    await expect(page.locator('[data-sonner-toast]').filter({ hasText: 'boom' })).toBeVisible({
      timeout: 5_000,
    });
    expect(api.calls('PipelineService/CreatePipeline')).toHaveLength(0);
  });
});

test.describe('visual builder toolbar — editing an existing pipeline', () => {
  test('loads an existing visual pipeline: seeds name/matchers and updates on save', async ({
    page,
    api,
  }) => {
    await api.loginAs(appAdmin);
    const s = basicScenario();
    const visualPipe = pipeline({
      id: 'pip-visual-1',
      name: 'existing-visual',
      source: 'visual',
      matchers: ['cluster="prod-eu-1"'],
    });
    api.seed({
      orgs: [s.org],
      schema: schemaFixture,
      pipelines: [visualPipe],
      graphViewResult: { graph: mockGraph, opaque: false, warning: '' },
      visualRenderResult: { content: '// generated\n', node_map: {}, diagnostics: [] },
    });

    await page.goto(`/pipelines/${visualPipe.id}/visual`);
    await page.waitForSelector('[data-testid="visual-builder"]', { timeout: 10_000 });

    await expect(page.locator('[data-testid="toolbar-name"]')).toHaveValue('existing-visual');
    await expect(page.locator('[data-testid="matcher-chip"]')).toHaveCount(1);
    await expect(page.locator('[data-testid="matcher-chip"]')).toContainText('cluster="prod-eu-1"');

    await page.locator('[data-testid="toolbar-save"]').click();
    await expect(page).toHaveURL(new RegExp(`/pipelines/${visualPipe.id}$`), { timeout: 5_000 });

    const updates = api.calls('PipelineService/UpdatePipeline');
    expect(updates).toHaveLength(1);
    const body = updates[0].body as Record<string, unknown>;
    expect(body.name).toBe('existing-visual');
    expect(body.matchers).toEqual(['cluster="prod-eu-1"']);
  });

  test('a non-visual pipeline shows a clear error state instead of an empty canvas', async ({
    page,
    api,
  }) => {
    await api.loginAs(appAdmin);
    const s = basicScenario();
    // s.pipelines[0] has source: 'ui' (basicScenario).
    api.seed({ orgs: [s.org], schema: schemaFixture, pipelines: [s.pipelines[0]] });

    await page.goto(`/pipelines/${s.pipelines[0].id}/visual`);
    await expect(page.locator('[data-testid="visual-builder-load-error"]')).toBeVisible({
      timeout: 10_000,
    });
    await expect(page.locator('[data-testid="visual-builder"]')).not.toBeVisible();
  });
});
