// visual-code-sync.spec.ts — 7.6.4
// Code tab shows the live client-side TS render.
import { expect } from '@playwright/test';
import { basicScenario } from '../fixtures/factories';
import { appAdmin } from '../fixtures/personas';
import { schemaFixture } from '../fixtures/schema-fixture';
import { test } from '../fixtures/test';

test.describe('visual code sync', () => {
  test.beforeEach(async ({ page, api }) => {
    await api.loginAs(appAdmin);
    const s = basicScenario();
    api.seed({
      orgs: [s.org],
      schema: schemaFixture,
      // Mock the server render for "Verify render" button
      visualRenderResult: {
        content:
          '// generated by shepherd visual builder — do not edit by hand (edits will be overwritten); graph revision 1, schema alloy-v1.18.1\n',
        node_map: {},
        diagnostics: [],
      },
    });
    await page.goto('/pipelines/visual/new');
    await page.waitForSelector('[data-testid="visual-builder"]', { timeout: 10_000 });
    await page.waitForSelector('[data-testid="palette-search"]', { timeout: 8_000 });
    // Bottom drawer defaults to collapsed; open it before selecting a tab.
    await page.click('[data-testid="drawer-toggle"]');
  });

  test('Code tab shows header comment after placing a node', async ({ page }) => {
    // Open Code tab
    await page.click('[data-testid="drawer-tab-code"]');

    // Place a node to trigger a render
    await page.click('[data-component="prometheus.scrape"]');

    // Code tab must show the generated header comment from the TS renderer
    const codeContent = page.locator('[data-testid="code-tab-content"]');
    await expect(codeContent).toContainText('generated by shepherd visual builder', {
      timeout: 5_000,
    });
  });

  test('Code tab shows the component name of a placed node', async ({ page }) => {
    await page.click('[data-testid="drawer-tab-code"]');
    await page.click('[data-component="prometheus.remote_write"]');

    const codeContent = page.locator('[data-testid="code-tab-content"]');
    await expect(codeContent).toContainText('prometheus.remote_write', { timeout: 5_000 });
  });

  test('Code tab is empty (just header) before any nodes are placed', async ({ page }) => {
    await page.click('[data-testid="drawer-tab-code"]');

    const codeContent = page.locator('[data-testid="code-tab-content"]');
    // With no nodes, the render still produces the header comment
    // The pre element may be empty or show only the header — either is acceptable
    await expect(codeContent).toBeVisible({ timeout: 3_000 });
  });

  test('Verify render button is present in Code tab', async ({ page }) => {
    await page.click('[data-testid="drawer-tab-code"]');
    await expect(page.locator('button:has-text("Verify render")')).toBeVisible({ timeout: 3_000 });
  });
});
