import type { GraphDocument, SchemaPayload } from './types';

export interface RenderDiagnostic {
  layer: 'L1';
  code: string;
  node_id?: string;
  node_id2?: string;
  message: string;
}
export interface RenderTSResult {
  content: string;
  nodeMap: Record<string, { startLine: number; endLine: number }>;
  diagnostics: RenderDiagnostic[];
}

const categoryOrder: Record<string, number> = {
  config: 0,
  sources: 1,
  transform: 2,
  destinations: 3,
  advanced: 4,
};
const sanitize = (label: string) => {
  const value = label
    .replace(/[^a-z0-9_]/gi, '_')
    .replace(/^[^a-zA-Z_]/, '_$&')
    .toLowerCase();
  return value || '_';
};
const quote = (value: string) => JSON.stringify(value);
function serialize(value: unknown, type: string): string {
  if (type === 'duration') return quote(String(value));
  if (typeof value === 'string') return quote(value);
  if (typeof value === 'boolean') return String(value);
  if (typeof value === 'number') return String(value);
  if (Array.isArray(value)) return `[${value.map((v) => serialize(v, 'string')).join(', ')}]`;
  if (value && typeof value === 'object') {
    return `{${Object.entries(value as Record<string, unknown>)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([k, v]) => `${k} = ${serialize(v, 'string')}`)
      .join(', ')}}`;
  }
  return quote(String(value));
}

export function renderTS(doc: GraphDocument, schema: SchemaPayload): RenderTSResult {
  const labels = new Map<string, string>();
  const seen = new Map<string, string>();
  for (const node of doc.nodes) {
    const label = sanitize(node.label);
    labels.set(node.id, label);
    if (!node.disabled) {
      const key = `${node.component}\0${label}`;
      const old = seen.get(key);
      if (old)
        return {
          content: '',
          nodeMap: {},
          diagnostics: [
            {
              layer: 'L1',
              code: 'label_collision',
              node_id: old,
              node_id2: node.id,
              message: `nodes ${old} and ${node.id} have the same label`,
            },
          ],
        };
      seen.set(key, node.id);
    }
  }
  const active = doc.nodes.filter((n) => !n.disabled);
  const ids = new Set(active.map((n) => n.id));
  const indegree = new Map(active.map((n) => [n.id, 0]));
  const adjacency = new Map<string, string[]>();
  for (const edge of doc.edges)
    if (ids.has(edge.from.node) && ids.has(edge.to.node)) {
      adjacency.set(edge.from.node, [...(adjacency.get(edge.from.node) ?? []), edge.to.node]);
      indegree.set(edge.to.node, (indegree.get(edge.to.node) ?? 0) + 1);
    }
  const compare = (a: string, b: string) => {
    const na = active.find((n) => n.id === a)!;
    const nb = active.find((n) => n.id === b)!;
    return (
      (categoryOrder[schema.components[na.component]?.category ?? 'advanced'] ?? 4) -
        (categoryOrder[schema.components[nb.component]?.category ?? 'advanced'] ?? 4) ||
      na.component.localeCompare(nb.component) ||
      labels.get(a)!.localeCompare(labels.get(b)!)
    );
  };
  const queue = active
    .filter((n) => indegree.get(n.id) === 0)
    .map((n) => n.id)
    .sort(compare);
  const order: string[] = [];
  while (queue.length) {
    const id = queue.shift()!;
    order.push(id);
    for (const to of adjacency.get(id) ?? []) {
      indegree.set(to, indegree.get(to)! - 1);
      if (indegree.get(to) === 0) queue.push(to);
    }
    queue.sort(compare);
  }
  for (const n of active) if (!order.includes(n.id)) order.push(n.id);
  order.sort((a, b) => order.indexOf(a) - order.indexOf(b));
  const version = schema._meta.alloy_version || doc.schema_version;
  let content = `// generated by shepherd visual builder — do not edit by hand (edits will be overwritten); graph revision ${doc.nodes.length}, schema ${version}\n`;
  for (const node of doc.nodes)
    if (node.disabled) content += `// node ${quote(node.label)} disabled\n`;
  const nodeMap: RenderTSResult['nodeMap'] = {};
  for (const id of order) {
    const node = active.find((n) => n.id === id)!;
    const component = schema.components[node.component];
    content += `\n${node.component} ${quote(labels.get(id)!)} {\n`;
    const startLine = content.split('\n').length - 1;
    for (const attr of component?.attributes ?? [])
      if (Object.hasOwn(node.props, attr.name)) {
        if (attr.type === 'secret' && typeof node.props[attr.name] === 'string')
          return {
            content: '',
            nodeMap: {},
            diagnostics: [
              {
                layer: 'L1',
                code: 'secret_by_value',
                node_id: id,
                message: 'secret value supplied as a literal',
              },
            ],
          };
        if (attr.type !== 'secret')
          content += `  ${attr.name} = ${serialize(node.props[attr.name], attr.type)}\n`;
      }
    for (const input of component?.inputs ?? []) {
      const wires = doc.edges
        .filter((e) => e.to.node === id && e.to.port === input.prop && ids.has(e.from.node))
        .sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
      const refs = wires.map(
        (e) =>
          `${doc.nodes.find((n) => n.id === e.from.node)!.component}.${labels.get(e.from.node)!}.${e.from.port}`,
      );
      if (refs.length)
        content += `  ${input.prop} = ${input.cardinality === 'list' ? `[${refs.join(', ')}]` : refs[0]}\n`;
    }
    for (const binding of doc.bindings.filter((b) => b.node === id))
      content += `  ${binding.prop} = ${binding.ref.expr}\n`;
    content += '}\n';
    nodeMap[id] = { startLine, endLine: content.split('\n').length - 1 };
  }
  return { content, nodeMap, diagnostics: [] };
}
