{{- if and (not .Values.existingSecret) .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shepherd.fullname" . }}-secrets
  labels:
    {{- include "shepherd.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.secrets | nindent 2 }}
{{- end }}
