{{- if and (not .Values.existingSecret) .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shepherd.fullname" . }}-secrets
  labels:
    {{- include "shepherd.labels" . | nindent 4 }}
  {{- if ((.Values.migrations).job).enabled }}
  annotations:
    {{- include "shepherd.migrateHookDeps" . | nindent 4 }}
  {{- end }}
stringData:
  {{- toYaml .Values.secrets | nindent 2 }}
{{- end }}
