apiVersion: v1
kind: Service
metadata:
  name: {{ include "shepherd.fullname" . }}
  labels:
    {{- include "shepherd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
      appProtocol: kubernetes.io/h2c
  selector:
    {{- include "shepherd.selectorLabels" . | nindent 4 }}
