apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shepherd.fullname" . }}
  labels:
    {{- include "shepherd.labels" . | nindent 4 }}
  {{- if .Values.migrations.job.enabled }}
  annotations:
    {{- include "shepherd.migrateHookDeps" . | nindent 4 }}
  {{- end }}
