package cli

// Developer-only database fixtures. These commands are intentionally grouped
// under "dev" and must not be used against a production database.

import (
	"context"
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/spf13/cobra"

	"shepherd/internal/config"
	"shepherd/internal/store"
	"shepherd/internal/store/sqlc"
)

const (
	seedOrgPlatformID         = "11111111-aaaa-4000-8000-000000000001"
	seedOrgDataEngID          = "11111111-aaaa-4000-8000-000000000002"
	seedPlatformAdminGroupID  = "22222222-aaaa-4000-8000-000000000001"
	seedPlatformReaderGroupID = "22222222-aaaa-4000-8000-000000000002"
	seedDataEngAdminGroupID   = "22222222-aaaa-4000-8000-000000000003"
	seedAgentTokenID          = "00000000-de00-4000-a000-000000000001" //nolint:gosec // G101: deterministic dev fixture UUID, not a credential
	seedAgentTokenSecret      = "dev-only-agent-secret-32byteslong"    //nolint:gosec // deterministic development fixture
	seedClusterPlatformName   = "prod-eu-1"
	seedClusterStagingName    = "staging-eu-1"
	seedClusterDataEngName    = "data-eng-eu-1"
	seedDestProdPromURL       = "https://prometheus.example.com/api/v1/write"
	seedDestProdLokiURL       = "https://loki.example.com/loki/api/v1/push"
)

// baseMetricsTemplate is a complete, self-contained scrape->remote_write chain:
// it scrapes Shepherd's own /metrics via prometheus.exporter.self and forwards
// to the seeded "prom-prod" destination. It is stage-1 (and, given a real
// alloy binary, stage-2) valid on its own so the dev stack serves a working
// config instead of an empty one. %q verbs are filled with the cluster name
// and destination URL so the two stay in sync with the rest of the seed.
const baseMetricsTemplate = `prometheus.exporter.self "seed" { }

prometheus.scrape "seed" {
  targets    = prometheus.exporter.self.seed.targets
  forward_to = [prometheus.remote_write.seed.receiver]
}

prometheus.remote_write "seed" {
  external_labels = {
    cluster = %q,
  }

  endpoint {
    url = %q
  }
}
`

// demoVisualGraph is a valid alloy-graph/v1 document — discovery.kubernetes ->
// prometheus.scrape -> prometheus.remote_write — adapted from the smallest
// suitable corpus fixture (internal/visual/testdata/corpus/minimal-scrape.graph.json)
// with node labels changed ("k8s"/"app"/"sink" -> "pods"/"demo"/"demo") so it
// reads as its own example rather than a copy of that fixture. It seeds the
// demo-visual pipeline's wizard_state so opening the visual builder shows a
// real, editable graph instead of an empty canvas (D1/R3-H5).
const demoVisualGraph = `{"kind":"alloy-graph/v1","schema_version":"alloy-v1.18.1","nodes":[{"id":"n1","component":"discovery.kubernetes","label":"pods","position":{"x":0,"y":0},"props":{"role":"pod"},"disabled":false,"notes":""},{"id":"n2","component":"prometheus.scrape","label":"demo","position":{"x":1,"y":0},"props":{},"disabled":false,"notes":""},{"id":"n3","component":"prometheus.remote_write","label":"demo","position":{"x":2,"y":0},"props":{},"disabled":false,"notes":""}],"edges":[{"id":"e1","from":{"node":"n1","port":"targets"},"to":{"node":"n2","port":"targets"}},{"id":"e2","from":{"node":"n2","port":"metrics"},"to":{"node":"n3","port":"receiver"}}],"bindings":[],"viewport":{"x":0,"y":0,"zoom":1},"meta":{"created_with":"shepherd-dev-seed"}}`

// demoVisualContents is the exact render of demoVisualGraph — verified via
// visual.Render against the corpus test schema — so contents and wizard_state
// stay in lockstep (checkVisualRenderMatch would otherwise flag them as
// mismatched) and the served config is stage-1 valid on its own.
const demoVisualContents = `// generated by shepherd visual builder — do not edit by hand (edits will be overwritten); graph revision 3, schema alloy-v1.18.1

discovery.kubernetes "pods" {
  role = "pod"
}

prometheus.scrape "demo" {
  targets = [discovery.kubernetes.pods.targets]
}

prometheus.remote_write "demo" {
  receiver = [prometheus.scrape.demo.metrics]
}
`

var (
	devCmd              = &cobra.Command{Use: "dev", Short: "Developer tooling (direct DB access — never use in production)"}
	devSeedCmd          = &cobra.Command{Use: "seed", Short: "Seed development fixture data (idempotent)", RunE: runDevSeed}
	devCreateSessionCmd = &cobra.Command{Use: "create-session", Short: "Mint a dev session for persona testing (direct DB — never production)", RunE: runDevCreateSession}
)

func init() {
	devCreateSessionCmd.Flags().String("persona", "appadmin", "persona: appadmin|orgadmin-platform|reader-platform|nobody")
	devCreateSessionCmd.Flags().Duration("ttl", time.Hour, "session TTL")
	devCmd.AddCommand(devSeedCmd, devCreateSessionCmd)
	rootCmd.AddCommand(devCmd)
}

func runDevSeed(cmd *cobra.Command, _ []string) error {
	cfg, err := config.Load(cfgFile)
	if err != nil {
		return err
	}
	st, err := store.New(cmd.Context(), &cfg.Database)
	if err != nil {
		return fmt.Errorf("connecting: %w", err)
	}
	defer st.Close()
	ctx := cmd.Context()
	platform, err := upsertSeedOrg(ctx, st, seedOrgPlatformID, "platform-org", "Platform Engineering", seedPlatformAdminGroupID, seedPlatformReaderGroupID)
	if err != nil {
		return fmt.Errorf("creating platform org: %w", err)
	}
	dataEng, err := upsertSeedOrg(ctx, st, seedOrgDataEngID, "data-eng", "Data Engineering", seedDataEngAdminGroupID, "")
	if err != nil {
		return fmt.Errorf("creating data-eng org: %w", err)
	}
	fmt.Printf("orgs: platform-org(%s), data-eng(%s)\n", platform.ID, dataEng.ID)

	prod, err := st.Queries.UpsertCluster(ctx, seedClusterPlatformName)
	if err != nil {
		return fmt.Errorf("upserting prod cluster: %w", err)
	}
	staging, err := st.Queries.UpsertCluster(ctx, seedClusterStagingName)
	if err != nil {
		return fmt.Errorf("upserting staging cluster: %w", err)
	}
	if !prod.OrgID.Valid {
		if err := st.Queries.ClaimCluster(ctx, sqlc.ClaimClusterParams{ID: prod.ID, OrgID: platform.ID}); err != nil {
			return fmt.Errorf("claiming prod cluster: %w", err)
		}
	}
	if !staging.OrgID.Valid {
		if err := st.Queries.ClaimCluster(ctx, sqlc.ClaimClusterParams{ID: staging.ID, OrgID: platform.ID}); err != nil {
			return fmt.Errorf("claiming staging cluster: %w", err)
		}
	}

	// data-eng starts with its own claimed cluster + collector so the org
	// (which sorts first alphabetically in the UI) is never blank on first
	// login — see R3-H1. No collector_instances are seeded here (see below);
	// nothing in the compose stack registers against it, so it legitimately
	// shows zero live instances until someone points an agent at it.
	dataEngCluster, err := st.Queries.UpsertCluster(ctx, seedClusterDataEngName)
	if err != nil {
		return fmt.Errorf("upserting data-eng cluster: %w", err)
	}
	if !dataEngCluster.OrgID.Valid {
		if err := st.Queries.ClaimCluster(ctx, sqlc.ClaimClusterParams{ID: dataEngCluster.ID, OrgID: dataEng.ID}); err != nil {
			return fmt.Errorf("claiming data-eng cluster: %w", err)
		}
	}
	if _, err := st.Queries.UpsertCollector(ctx, sqlc.UpsertCollectorParams{ClusterID: dataEngCluster.ID, Role: "metrics"}); err != nil {
		return fmt.Errorf("upserting data-eng collector: %w", err)
	}
	// Both prod-eu-1 and staging-eu-1 are claimed by platform-org above, so
	// say so — a prior version of this message printed a hardcoded
	// "(unclaimed)" for staging even though it was claimed (R3-M1).
	fmt.Printf("clusters: %s (claimed by platform-org), %s (claimed by platform-org), %s (claimed by data-eng)\n", prod.Name, staging.Name, dataEngCluster.Name)

	// Collector rows only — no stub collector_instances. Real Alloy
	// registrations come from the compose stack's alloy-metrics/alloy-logs/
	// alloy-staging containers; seeding fake instances here used to sit
	// alongside them and confuse status (R3-H2). The "singleton" collector
	// has no compose container backing it, so it will show zero instances
	// until something registers against it — that's expected, not stale.
	for _, role := range []string{"metrics", "logs", "singleton"} {
		if _, err := st.Queries.UpsertCollector(ctx, sqlc.UpsertCollectorParams{ClusterID: prod.ID, Role: role}); err != nil {
			return fmt.Errorf("upserting %s collector: %w", role, err)
		}
	}
	fmt.Println("collectors: metrics, logs, singleton (prod-eu-1); metrics (data-eng-eu-1) — instances register themselves")

	if err := seedDestinations(ctx, st, platform.ID); err != nil {
		return fmt.Errorf("seeding destinations: %w", err)
	}
	if err := seedPipelines(ctx, st, platform.ID, platformPipelineItems()); err != nil {
		return fmt.Errorf("seeding platform pipelines: %w", err)
	}
	if err := seedPipelines(ctx, st, dataEng.ID, dataEngPipelineItems()); err != nil {
		return fmt.Errorf("seeding data-eng pipelines: %w", err)
	}
	if err := seedAgentToken(ctx, st); err != nil {
		return fmt.Errorf("seeding agent token: %w", err)
	}
	fmt.Println("seed complete")
	return nil
}

func upsertSeedOrg(ctx context.Context, st *store.Store, id, name, displayName, adminGroup, readerGroup string) (sqlc.Org, error) {
	var org sqlc.Org
	var reader any
	if readerGroup != "" {
		reader = readerGroup
	}
	err := st.Pool().QueryRow(ctx, `INSERT INTO orgs (id, name, display_name, admin_group_id, reader_group_id) VALUES ($1, $2, $3, $4, $5) ON CONFLICT (name) DO UPDATE SET display_name=EXCLUDED.display_name, admin_group_id=EXCLUDED.admin_group_id, reader_group_id=EXCLUDED.reader_group_id RETURNING id, name, display_name, admin_group_id, reader_group_id, created_at, updated_at`, id, name, displayName, adminGroup, reader).Scan(&org.ID, &org.Name, &org.DisplayName, &org.AdminGroupID, &org.ReaderGroupID, &org.CreatedAt, &org.UpdatedAt)
	return org, err
}

// seedPipelineItem describes one pipeline to seed.
type seedPipelineItem struct {
	name, contents, source string
	matchers               []string
	enabled                bool
	// wizardState is the raw JSON wizard_state document (non-empty only for
	// source="visual"/"wizard" items). Empty means NULL wizard_state.
	wizardState string
}

// platformPipelineItems returns the pipelines seeded for platform-org.
//
// base-metrics carries a complete, self-contained scrape->remote_write chain
// and real matchers (cluster="prod-eu-1", role="metrics") so it actually
// matches the alloy-metrics collector from the compose stack and the dev
// stack serves a working config instead of an empty one (R3-C1/R3-H3).
func platformPipelineItems() []seedPipelineItem {
	return []seedPipelineItem{
		{
			name:     "base-metrics",
			contents: fmt.Sprintf(baseMetricsTemplate, seedClusterPlatformName, seedDestProdPromURL),
			source:   "ui",
			matchers: []string{fmt.Sprintf("cluster=%q", seedClusterPlatformName), `role="metrics"`},
			enabled:  true,
		},
		{
			// demo-visual is source="visual" with a real alloy-graph/v1
			// wizard_state (see demoVisualGraph) so the visual builder opens
			// with an example to explore instead of a blank canvas (D1/
			// R3-H5). It shares base-metrics' matchers (both legitimately
			// match the alloy-metrics collector) but is a distinct pipeline
			// by name and by mechanism — discovery.kubernetes scrape rather
			// than base-metrics' self-exporter — so it doesn't collide with
			// base-metrics' name or purpose.
			name:        "demo-visual",
			contents:    demoVisualContents,
			source:      "visual",
			matchers:    []string{fmt.Sprintf("cluster=%q", seedClusterPlatformName), `role="metrics"`},
			enabled:     true,
			wizardState: demoVisualGraph,
		},
		{
			name:     "loki-logs",
			contents: "loki.source.file \"seed\" {\n  targets    = []\n  forward_to = []\n}\n",
			source:   "ui",
			// Matches the alloy-logs collector, but left disabled since the
			// contents are a placeholder stub (no real forward_to target).
			matchers: []string{fmt.Sprintf("cluster=%q", seedClusterPlatformName), `role="logs"`},
			enabled:  false,
		},
		{
			name:     "app-obs-wizard",
			contents: `// wizard-generated`,
			source:   "wizard",
			// No matchers: this is a stub demonstrating a wizard-sourced
			// pipeline in the UI, not something meant to actually match a
			// collector. Left disabled; producing real contents requires
			// walking the wizard.
			matchers: nil,
			enabled:  false,
		},
	}
}

// dataEngPipelineItems returns the pipelines seeded for the data-eng org, so
// it is not empty on first login (R3-H1).
func dataEngPipelineItems() []seedPipelineItem {
	return []seedPipelineItem{
		{
			name:     "example-metrics",
			contents: `prometheus.exporter.self "seed" { }`,
			source:   "ui",
			matchers: []string{fmt.Sprintf("cluster=%q", seedClusterDataEngName), `role="metrics"`},
			enabled:  false,
		},
	}
}

// seedPipelines creates the given pipelines under orgID, idempotently. For
// each pipeline actually created (not already present), it also writes
// pipeline_revisions revision 1 and an audit_log row, mirroring what
// PipelinesHandler.Create does in internal/mgmtapi/pipelines.go (R3-H4).
func seedPipelines(ctx context.Context, st *store.Store, orgID pgtype.UUID, items []seedPipelineItem) error {
	summary := make([]string, 0, len(items))
	for _, item := range items {
		if _, err := st.Queries.GetPipelineByOrgAndName(ctx, sqlc.GetPipelineByOrgAndNameParams{OrgID: orgID, Name: item.name}); err == nil {
			summary = append(summary, item.name+"(exists)")
			continue
		}
		matchers := item.matchers
		if matchers == nil {
			matchers = []string{}
		}
		matchersJSON, err := json.Marshal(matchers)
		if err != nil {
			return fmt.Errorf("marshaling matchers for %s: %w", item.name, err)
		}
		var wizardState json.RawMessage
		if item.wizardState != "" {
			wizardState = json.RawMessage(item.wizardState)
		}
		p, err := st.Queries.CreatePipeline(ctx, sqlc.CreatePipelineParams{
			OrgID: orgID, Name: item.name, Contents: item.contents, Matchers: matchersJSON,
			Enabled: item.enabled, Source: item.source, WizardState: wizardState,
			CreatedBy: "seed", UpdatedBy: "seed",
		})
		if err != nil {
			if isUnique(err) {
				summary = append(summary, item.name+"(exists)")
				continue
			}
			return fmt.Errorf("creating pipeline %s: %w", item.name, err)
		}
		if _, err := st.Queries.CreatePipelineRevision(ctx, sqlc.CreatePipelineRevisionParams{
			PipelineID: p.ID, Revision: 1, Contents: p.Contents, Matchers: p.Matchers,
			Enabled: p.Enabled, ChangedBy: "seed", ChangeNote: "seed",
		}); err != nil {
			return fmt.Errorf("creating revision 1 for %s: %w", item.name, err)
		}
		if err := st.Queries.InsertAuditLog(ctx, sqlc.InsertAuditLogParams{
			Actor: "seed", ActorType: "user", OrgID: orgID, Action: "pipeline.create",
			ResourceType: "pipeline", ResourceID: p.ID.String(), Detail: json.RawMessage(`{}`),
		}); err != nil {
			return fmt.Errorf("writing audit log for %s: %w", item.name, err)
		}
		state := "disabled"
		if item.enabled {
			state = "enabled"
		}
		summary = append(summary, fmt.Sprintf("%s(%s)", item.name, state))
	}
	fmt.Printf("pipelines: %s\n", strings.Join(summary, ", "))
	return nil
}

func seedDestinations(ctx context.Context, st *store.Store, orgID pgtype.UUID) error {
	for _, item := range []struct{ name, typ, url string }{{"prom-prod", "prometheus", seedDestProdPromURL}, {"loki-prod", "loki", seedDestProdLokiURL}} {
		dests, err := st.Queries.ListDestinationsByOrg(ctx, orgID)
		if err != nil {
			return err
		}
		found := false
		for i := range dests {
			if dests[i].Name == item.name {
				found = true
				break
			}
		}
		if found {
			continue
		}
		if _, err := st.Queries.CreateDestination(ctx, sqlc.CreateDestinationParams{OrgID: orgID, Name: item.name, Type: item.typ, Url: item.url, SecretName: "", SecretNamespace: "", AuthMode: "none", Extra: json.RawMessage(`{}`)}); err != nil && !isUnique(err) {
			return err
		}
	}
	fmt.Println("destinations: prom-prod, loki-prod")
	return nil
}

func seedAgentToken(ctx context.Context, st *store.Store) error {
	var id pgtype.UUID
	if err := id.Scan(seedAgentTokenID); err != nil {
		return err
	}
	hash := sha256.Sum256([]byte(seedAgentTokenSecret))
	_, err := st.Queries.CreateAgentTokenWithID(ctx, sqlc.CreateAgentTokenWithIDParams{ID: id, Name: "dev-alloy-token", TokenHash: hash[:], CreatedBy: "seed"})
	if err != nil && !isUnique(err) {
		return err
	}
	fmt.Printf("agent_token: id=%s secret=%s\n", seedAgentTokenID, seedAgentTokenSecret)
	return nil
}

func isUnique(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23505"
}

func runDevCreateSession(cmd *cobra.Command, _ []string) error {
	persona, err := cmd.Flags().GetString("persona")
	if err != nil {
		return err
	}
	ttl, err := cmd.Flags().GetDuration("ttl")
	if err != nil {
		return err
	}
	cfg, err := config.Load(cfgFile)
	if err != nil {
		return err
	}
	st, err := store.New(cmd.Context(), &cfg.Database)
	if err != nil {
		return fmt.Errorf("connecting: %w", err)
	}
	defer st.Close()
	type personaDef struct {
		userOID, email, displayName string
		groups                      []string
		appAdmin                    bool
	}
	personas := map[string]personaDef{
		"appadmin":          {"dev:appadmin", "appadmin@dev.local", "Dev App Admin", []string{seedPlatformAdminGroupID}, true},
		"orgadmin-platform": {"dev:orgadmin-platform", "orgadmin@dev.local", "Dev Platform Admin", []string{seedPlatformAdminGroupID}, false},
		"reader-platform":   {"dev:reader-platform", "reader@dev.local", "Dev Reader", []string{seedPlatformReaderGroupID}, false},
		"nobody":            {"dev:nobody", "nobody@dev.local", "Dev Nobody", nil, false},
	}
	p, ok := personas[persona]
	if !ok {
		return fmt.Errorf("unknown persona %q; valid: appadmin, orgadmin-platform, reader-platform, nobody", persona)
	}
	groups, err := json.Marshal(p.groups)
	if err != nil {
		return fmt.Errorf("encoding groups: %w", err)
	}
	id := fmt.Sprintf("dev-%s-%d", persona, time.Now().UnixNano())
	now := time.Now()
	_, err = st.Queries.CreateSession(cmd.Context(), sqlc.CreateSessionParams{ID: id, UserOid: p.userOID, Email: p.email, DisplayName: p.displayName, GroupIds: groups, IsAppAdmin: p.appAdmin, ExpiresAt: pgtype.Timestamptz{Time: now.Add(ttl), Valid: true}, Source: "dev"})
	if err != nil {
		return fmt.Errorf("creating session: %w", err)
	}
	fmt.Printf("session_id=%s persona=%s ttl=%s\n", id, persona, ttl)
	fmt.Println("# Set cookie: shepherd_session=<session_id>")
	return nil
}
