FROM golang:1.27-alpine@sha256:8a5910f31396cd4d89662f56c68b3ae31d374308270a1c3bd96672ee5ed43414 AS builder
WORKDIR /app
COPY main.go .
RUN go mod init mockmsft && CGO_ENABLED=0 GOOS=linux go build -o /mockmsft .

FROM gcr.io/distroless/static-debian12:nonroot@sha256:afa5c872c891853ca7fcf1f12c3edb23f7eeef36189728842dd51042ff57f7ab
COPY --from=builder /mockmsft /mockmsft
ENTRYPOINT ["/mockmsft"]
