package serve_test

import (
	"context"
	"strings"
	"testing"
	"time"

	"shepherd/internal/beacon"
	"shepherd/internal/merge"
	"shepherd/internal/schema"
	"shepherd/internal/serve"
	"shepherd/internal/version"
)

// scrapePipeline is a minimal, individually-valid-Alloy fixture pipeline —
// ComputeServed always Stage-1-validates the FINAL merged content now (see
// TestComputeServed_AlwaysStage1Validates), so every fixture used for a
// success-path assertion must itself be syntactically valid.
func scrapePipeline(id, name string, matchers []string) merge.Pipeline {
	return merge.Pipeline{
		ID:   id,
		Name: name,
		Contents: `prometheus.scrape "a" {
  targets    = []
  forward_to = []
}`,
		Matchers: matchers,
		Source:   "ui",
	}
}

// TestComputeServed_Golden proves ComputeServed's output for a fixed input is
// exactly what the two former call sites (agentapi.recomputeServeCache,
// mgmtapi.recomputeOrgCaches) used to build by hand: merge.Assemble's
// declare-wrapped content, byte-identical (the header carries no
// generation timestamp since #213), with Hash always matching
// HashContent(Content).
func TestComputeServed_Golden(t *testing.T) {
	pipelines := []merge.Pipeline{scrapePipeline("p1", "alpha", []string{`cluster="c1"`})}
	coll := serve.Collector{ID: "coll-1", Cluster: "c1", Role: "metrics"}

	got, err := serve.ComputeServed(context.Background(), serve.Deps{}, coll, pipelines)
	if err != nil {
		t.Fatalf("ComputeServed: %v", err)
	}

	const want = `// Generated by Shepherd prod
// Collector: c1/metrics (coll-1)
// Pipelines (1):
//   - alpha (rev 0)

declare "pipe_alpha" {
  prometheus.scrape "a" {
    targets    = []
    forward_to = []
  }
}
pipe_alpha "default" { }
`
	if got := got.Content; got != want {
		t.Fatalf("content mismatch:\n got:\n%s\nwant:\n%s", got, want)
	}
	if want := merge.HashContent(got.Content); got.Hash != want {
		t.Fatalf("Hash %q does not match HashContent(Content) %q", got.Hash, want)
	}
	if len(got.Exclusions) != 0 {
		t.Fatalf("unexpected exclusions: %+v", got.Exclusions)
	}
	if got.BaselineErr != nil {
		t.Fatalf("unexpected BaselineErr: %v", got.BaselineErr)
	}
}

// TestComputeServed_BaselineChangesHash proves the specific line both former
// call sites carried verbatim — "if content changed after appending the
// baseline, recompute the hash from the NEW content, not the merge-only one"
// — survived the extraction. Getting this wrong (serving merge.Assemble's
// original Hash after the baseline mutated Content) was exactly the kind of
// two-path drift docs/gateway-tier-plan.md §10 warns about.
func TestComputeServed_BaselineChangesHash(t *testing.T) {
	pipelines := []merge.Pipeline{scrapePipeline("p1", "alpha", []string{`cluster="c1"`})}
	coll := serve.Collector{ID: "coll-1", Cluster: "c1", Role: "metrics"}

	without, err := serve.ComputeServed(context.Background(), serve.Deps{}, coll, pipelines)
	if err != nil {
		t.Fatalf("ComputeServed (no baseline): %v", err)
	}

	deps := serve.Deps{BeaconBaseline: beacon.NewBaselineConfig("https://shepherd.example.test" + beacon.WritePath)}
	with, err := serve.ComputeServed(context.Background(), deps, coll, pipelines)
	if err != nil {
		t.Fatalf("ComputeServed (with baseline): %v", err)
	}

	if with.Content == without.Content {
		t.Fatalf("baseline pipeline was not appended to Content")
	}
	if with.Hash == without.Hash {
		t.Fatalf("baseline-mutated content unexpectedly kept the no-baseline hash")
	}
	if want := merge.HashContent(with.Content); with.Hash != want {
		t.Fatalf("Hash %q does not match HashContent(Content) %q after baseline append", with.Hash, want)
	}
}

// TestComputeServed_RecomputeOfUnchangedInputIsStable is the
// procoduck/shepherd#213 proof: recomputing an unchanged collector + pipeline
// set must produce byte-identical content and therefore the identical hash,
// even across a wall-clock change. Served content used to carry a
// "// Generated by Shepherd <env> at <RFC3339 now>" header line, so every
// recompute (any dirty mark — a label edit, say) changed every affected
// collector's hash and the whole fleet re-fetched and reloaded for nothing.
// The second call deliberately lands in a later wall-clock second, the
// header's former resolution, so a reintroduced timestamp fails this spec.
func TestComputeServed_RecomputeOfUnchangedInputIsStable(t *testing.T) {
	pipelines := []merge.Pipeline{scrapePipeline("p1", "alpha", []string{`cluster="c1"`})}
	coll := serve.Collector{ID: "coll-1", Cluster: "c1", Role: "metrics"}
	deps := serve.Deps{BeaconBaseline: beacon.NewBaselineConfig("https://shepherd.example.test" + beacon.WritePath)}

	first, err := serve.ComputeServed(context.Background(), deps, coll, pipelines)
	if err != nil {
		t.Fatalf("first ComputeServed: %v", err)
	}
	// Sleep past the next whole-second boundary.
	now := time.Now()
	time.Sleep(now.Truncate(time.Second).Add(time.Second + 50*time.Millisecond).Sub(now))
	second, err := serve.ComputeServed(context.Background(), deps, coll, pipelines)
	if err != nil {
		t.Fatalf("second ComputeServed: %v", err)
	}

	if first.Content != second.Content {
		t.Fatalf("recompute of an unchanged config changed the served bytes:\nfirst:\n%s\nsecond:\n%s", first.Content, second.Content)
	}
	if first.Hash != second.Hash {
		t.Fatalf("recompute of an unchanged config changed the hash: %s -> %s", first.Hash, second.Hash)
	}
	if want := merge.HashContent(second.Content); second.Hash != want {
		t.Fatalf("Hash %q does not match HashContent(Content) %q", second.Hash, want)
	}
}

// TestComputeServed_ContentChangeChangesHash is #213's other half: removing
// the timestamp must not make the hash insensitive to real changes — a
// changed pipeline body, or a newly matching pipeline, still moves it.
func TestComputeServed_ContentChangeChangesHash(t *testing.T) {
	coll := serve.Collector{ID: "coll-1", Cluster: "c1", Role: "metrics"}
	base := []merge.Pipeline{scrapePipeline("p1", "alpha", []string{`cluster="c1"`})}

	before, err := serve.ComputeServed(context.Background(), serve.Deps{}, coll, base)
	if err != nil {
		t.Fatalf("ComputeServed (before): %v", err)
	}

	edited := []merge.Pipeline{scrapePipeline("p1", "alpha", []string{`cluster="c1"`})}
	edited[0].Contents = strings.Replace(edited[0].Contents, `"a"`, `"b"`, 1)
	afterEdit, err := serve.ComputeServed(context.Background(), serve.Deps{}, coll, edited)
	if err != nil {
		t.Fatalf("ComputeServed (edited): %v", err)
	}
	if afterEdit.Hash == before.Hash {
		t.Fatal("editing a pipeline body did not change the served hash")
	}

	added := []merge.Pipeline{base[0], scrapePipeline("p2", "beta", []string{`cluster="c1"`})}
	afterAdd, err := serve.ComputeServed(context.Background(), serve.Deps{}, coll, added)
	if err != nil {
		t.Fatalf("ComputeServed (added): %v", err)
	}
	if afterAdd.Hash == before.Hash || afterAdd.Hash == afterEdit.Hash {
		t.Fatal("a newly matching pipeline did not change the served hash")
	}
}

// TestComputeServed_AlwaysStage1Validates is the extraction's one deliberate
// behavior change: agentapi's former recomputeServeCache only Stage-1
// validated the merged output "if s.validator != nil" — a nil validator (as
// every test in this repo, and no production wiring, ever constructs) meant
// a merged config that failed to even PARSE still reached serve_cache.
// ComputeServed takes no validator at all and always runs validate.Stage1 on
// the final content: there is no configuration that can skip it.
func TestComputeServed_AlwaysStage1Validates(t *testing.T) {
	broken := merge.Pipeline{
		ID: "p1", Name: "broken", Contents: `prometheus.scrape "a" {`,
		Matchers: []string{`cluster="c1"`}, Source: "ui",
	}
	coll := serve.Collector{ID: "coll-1", Cluster: "c1", Role: "metrics"}

	_, err := serve.ComputeServed(context.Background(), serve.Deps{}, coll, []merge.Pipeline{broken})
	if err == nil {
		t.Fatal("expected ComputeServed to refuse a merged config that fails Stage 1, got nil error")
	}
}

// TestComputeServed_SameShapeCallsAgree is the parity half of the W2-S3
// proof: internal/agentapi.recomputeServeCache (lazy) sets EnforceRoles:
// false, internal/mgmtapi.recomputeOrgCaches (eager) sets EnforceRoles: true
// — see Deps' doc comment for why that difference is deliberate — but with a
// REAL, non-nil schema registry, both must still produce identical
// content and hash: EnforceRoles only changes what a nil Schema means, never
// the outcome once one is actually wired. (Real end-to-end coverage of each
// call site individually lives where it always did:
// internal/mgmtapi/beacon_baseline_test.go for the eager path,
// internal/agentapi/service_test.go's GetConfig specs for the lazy one —
// this spec is what proves the SHARED function they both now call cannot
// silently diverge between them.)
func TestComputeServed_SameShapeCallsAgree(t *testing.T) {
	reg, err := schema.New(schema.Embedded, version.AlloySchemaVersion)
	if err != nil {
		t.Fatalf("schema.New: %v", err)
	}
	pipelines := []merge.Pipeline{
		scrapePipeline("p1", "alpha", []string{`cluster="parity-cluster"`}),
		scrapePipeline("p2", "beta", []string{`cluster="parity-cluster"`}),
	}
	baseline := beacon.NewBaselineConfig("https://shepherd.example.test" + beacon.WritePath)
	coll := serve.Collector{ID: "coll-parity", Cluster: "parity-cluster", Role: "metrics"}

	lazyShaped, err := serve.ComputeServed(context.Background(),
		serve.Deps{Schema: reg, EnforceRoles: false, BeaconBaseline: baseline}, coll, pipelines)
	if err != nil {
		t.Fatalf("lazy-shaped call: %v", err)
	}
	eagerShaped, err := serve.ComputeServed(context.Background(),
		serve.Deps{Schema: reg, EnforceRoles: true, BeaconBaseline: baseline}, coll, pipelines)
	if err != nil {
		t.Fatalf("eager-shaped call: %v", err)
	}

	if lazyShaped.Content != eagerShaped.Content {
		t.Fatalf("content diverged between the two call shapes:\nlazy:\n%s\neager:\n%s", lazyShaped.Content, eagerShaped.Content)
	}
	if lazyShaped.Hash != eagerShaped.Hash {
		t.Fatalf("hash diverged: lazy=%s eager=%s", lazyShaped.Hash, eagerShaped.Hash)
	}
}

// TestComputeServed_EnforceRolesNilSchema pins the one place the two former
// call sites' behavior genuinely diverges on purpose (see Deps.EnforceRoles'
// doc comment), so a future edit to ComputeServed cannot accidentally
// collapse it: internal/agentapi's shape (EnforceRoles: false) degrades to
// unenforced config when Schema is nil — matching its "a corrupt embedded
// schema degrades the guard rather than taking the fleet offline" contract
// (agentapi.New's doc comment) — while internal/mgmtapi's shape
// (EnforceRoles: true) refuses outright, matching
// internal/mgmtapi/router.go's "schemaReg is nil here" degraded-mount path,
// where recomputeOrgCaches must keep refusing rather than start silently
// serving unenforced config that looks enforced.
func TestComputeServed_EnforceRolesNilSchema(t *testing.T) {
	pipelines := []merge.Pipeline{scrapePipeline("p1", "alpha", []string{`cluster="c1"`})}
	coll := serve.Collector{ID: "coll-1", Cluster: "c1", Role: "metrics"}

	if _, err := serve.ComputeServed(context.Background(),
		serve.Deps{Schema: nil, EnforceRoles: false}, coll, pipelines); err != nil {
		t.Fatalf("EnforceRoles:false with a nil Schema must degrade, not refuse: %v", err)
	}
	if _, err := serve.ComputeServed(context.Background(),
		serve.Deps{Schema: nil, EnforceRoles: true}, coll, pipelines); err == nil {
		t.Fatal("EnforceRoles:true with a nil Schema must refuse to serve unenforced config, got nil error")
	}
}
