import type { Route } from '@playwright/test';
import { json, list, type MockState, Router } from './router';

const mockIdCounters: Record<string, number> = {};
function mockId(prefix: string): string {
  mockIdCounters[prefix] = (mockIdCounters[prefix] ?? 0) + 1;
  return `${prefix}-${String(mockIdCounters[prefix]).padStart(4, '0')}`;
}

export function resetMockState() {
  for (const key of Object.keys(mockIdCounters)) delete mockIdCounters[key];
}

// Default handlers for every endpoint in spec §12
export function installDefaultHandlers(router: Router) {
  const s = router.state;

  router.register('POST', '/api/orgs/:org/visual/render', (r) =>
    json(
      r,
      200,
      s.visualRenderResult ?? {
        content: '// generated by shepherd visual builder\n',
        node_map: {},
        diagnostics: [],
      },
    ),
  );
  router.register('POST', '/api/orgs/:org/visual/validate', (r) =>
    json(r, 200, { diagnostics: [] }),
  );
  router.register('POST', '/api/orgs/:org/visual/upgrade-check', (r) =>
    json(
      r,
      200,
      s.upgradeCheckResult ?? {
        old_version: 'alloy-v1.12.0',
        new_version: 'alloy-v1.18.1',
        items: [],
        needs_upgrade: false,
      },
    ),
  );
  router.register('POST', '/api/orgs/:org/simulate/relabel', (r) =>
    json(
      r,
      200,
      s.simulateRelabelResult ?? {
        traces: [
          {
            input: { __meta_kubernetes_pod_name: 'api-server-abc123' },
            steps: [
              {
                rule_index: 0,
                action: 'replace',
                before: { __meta_kubernetes_pod_name: 'api-server-abc123' },
                after: { instance: 'api-server-abc123' },
                kept: true,
              },
            ],
            output: { instance: 'api-server-abc123' },
            kept: true,
          },
          {
            input: { __meta_kubernetes_pod_name: 'worker-xyz789' },
            steps: [
              {
                rule_index: 0,
                action: 'keep',
                before: { __meta_kubernetes_pod_name: 'worker-xyz789' },
                kept: false,
              },
            ],
            kept: false,
          },
        ],
      },
    ),
  );
  router.register('POST', '/api/orgs/:org/simulate/logs', (r) =>
    json(
      r,
      200,
      s.simulateLogsResult ?? {
        traces: [
          {
            input: 'sample log line',
            steps: [
              {
                stage_index: 0,
                stage_type: 'json',
                simulated: true,
                line_before: 'sample log line',
                line_after: 'sample log line',
                labels_before: {},
                labels_after: {},
              },
            ],
            output: 'sample log line',
            dropped: false,
          },
        ],
      },
    ),
  );
  router.register('GET', '/api/orgs/:org/pipelines/:id/graph', (r) =>
    json(
      r,
      200,
      s.graphViewResult ?? {
        graph: {
          kind: 'alloy-graph/v1',
          schema_version: 'alloy-v1.18.1',
          nodes: [],
          edges: [],
          bindings: [],
          viewport: { x: 0, y: 0, zoom: 1 },
          meta: { created_with: 'shepherd-parser' },
        },
        opaque: false,
        warning: '',
      },
    ),
  );

  // ── Auth ──────────────────────────────────────────────────────────────────
  router.register('GET', '/api/me', (r) => {
    if (s.me === null || s.me === undefined) {
      return json(r, 401, { error: { code: 'unauthenticated', message: 'not authenticated' } });
    }
    return json(r, 200, s.me);
  });
  router.register('GET', '/auth/methods', (r) =>
    r.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        oidc: s.authMethods?.oidc ?? true,
        local_admin: s.authMethods?.local_admin ?? false,
      }),
    }),
  );
  router.register('POST', '/api/auth/local/login', async (r) => {
    const body = (await r.request().postDataJSON()) as { username?: string; password?: string };
    const expected = s.localAdminCreds;
    if (expected && body.username === expected.username && body.password === expected.password) {
      if (s.localAdminPersona !== undefined) s.me = s.localAdminPersona;
      return r.fulfill({ status: 200, contentType: 'application/json', body: '{"ok":true}' });
    }
    return r.fulfill({
      status: 401,
      contentType: 'application/json',
      body: JSON.stringify({
        error: { code: 'invalid_credentials', message: 'invalid username or password' },
      }),
    });
  });
  router.register('GET', '/auth/login', (r) =>
    r.fulfill({ status: 302, headers: { location: '/auth/callback?code=mock' } }),
  );
  router.register('GET', '/auth/callback', (r) =>
    r.fulfill({ status: 302, headers: { location: '/' } }),
  );
  router.register('GET', '/auth/logout', (r) =>
    r.fulfill({ status: 302, headers: { location: '/login' } }),
  );

  // ── Admin ─────────────────────────────────────────────────────────────────
  router.register('GET', '/api/admin/orgs', (r) => json(r, 200, list(s.orgs)));
  router.register('POST', '/api/admin/orgs', async (r) => {
    const body = await r.request().postDataJSON();
    const o = {
      id: mockId('org'),
      admin_group_id: '11111111-1111-1111-1111-111111111111',
      ...body,
      created_at: '2026-08-17T09:00:00Z',
      updated_at: '2026-08-17T09:00:00Z',
    };
    s.orgs.push(o);
    return json(r, 201, o);
  });
  router.register('PATCH', '/api/admin/orgs/:org', async (r) => {
    const body = await r.request().postDataJSON();
    return json(r, 200, body);
  });
  router.register('DELETE', '/api/admin/orgs/:org', (r) => r.fulfill({ status: 204 }));

  router.register('GET', '/api/admin/clusters', (r) => json(r, 200, list(s.clusters)));
  router.register('POST', '/api/admin/clusters/:cluster/claim', (r) =>
    json(r, 200, { status: 'claimed' }),
  );
  router.register('POST', '/api/admin/clusters/:cluster/unclaim', (r) =>
    json(r, 200, { status: 'unclaimed' }),
  );

  router.register('GET', '/api/admin/agent-tokens', (r) => json(r, 200, list(s.agentTokens)));
  router.register('POST', '/api/admin/agent-tokens', async (r) => {
    const body = await r.request().postDataJSON();
    const t = {
      id: mockId('tok'),
      ...body,
      status: 'active',
      secret: 'one-time-secret-value',
      created_at: '2026-08-17T09:00:00Z',
    };
    s.agentTokens.push(t);
    return json(r, 201, t);
  });
  router.register('DELETE', '/api/admin/agent-tokens/:id', (r) => r.fulfill({ status: 204 }));

  router.register('GET', '/api/admin/groups/search', (r) => json(r, 200, { items: [], total: 0 }));

  // ── Org-scoped ────────────────────────────────────────────────────────────
  router.register('GET', '/api/orgs/:org/collectors', (r) => json(r, 200, list(s.collectors)));
  router.register('GET', '/api/orgs/:org/collectors/:id', (r, p) => {
    const c = s.collectors.find((x: Record<string, unknown>) => x['id'] === p['id']);
    return c
      ? json(r, 200, c)
      : json(r, 404, { error: { code: 'not_found', message: 'collector not found' } });
  });
  router.register('GET', '/api/orgs/:org/collectors/:id/served-config', (r) =>
    json(r, 200, s.servedConfig),
  );
  router.register('POST', '/api/orgs/:org/collectors/:id/assignments', (r) => json(r, 201, {}));
  router.register('DELETE', '/api/orgs/:org/collectors/:id/assignments/:group_id', (r) =>
    r.fulfill({ status: 204 }),
  );

  router.register('GET', '/api/orgs/:org/attributes', (r) => json(r, 200, s.attributes));

  router.register('GET', '/api/orgs/:org/pipelines', (r) => json(r, 200, list(s.pipelines)));
  router.register('POST', '/api/orgs/:org/pipelines', async (r) => {
    const body = await r.request().postDataJSON();
    const p = {
      id: mockId('pip'),
      enabled: false,
      source: 'ui',
      created_at: '2026-08-17T09:00:00Z',
      updated_at: '2026-08-17T09:00:00Z',
      ...body,
    };
    s.pipelines.push(p);
    return json(r, 201, p);
  });
  router.register('POST', '/api/orgs/:org/pipelines/validate', async (r) => {
    return json(r, 200, s.validateResult);
  });
  router.register('GET', '/api/orgs/:org/pipelines/:id', (r, p) => {
    const pip = s.pipelines.find((x: Record<string, unknown>) => x['id'] === p['id']);
    return pip
      ? json(r, 200, pip)
      : json(r, 404, { error: { code: 'not_found', message: 'pipeline not found' } });
  });
  router.register('PUT', '/api/orgs/:org/pipelines/:id', async (r, p) => {
    const body = await r.request().postDataJSON();
    const idx = s.pipelines.findIndex((x: Record<string, unknown>) => x['id'] === p['id']);
    if (idx >= 0) Object.assign(s.pipelines[idx] as Record<string, unknown>, body);
    return json(r, 200, s.pipelines[idx] ?? body);
  });
  router.register('DELETE', '/api/orgs/:org/pipelines/:id', (r, p) => {
    s.pipelines = s.pipelines.filter((x: Record<string, unknown>) => x['id'] !== p['id']);
    return r.fulfill({ status: 204 });
  });
  router.register('POST', '/api/orgs/:org/pipelines/:id/enable', (r, p) => {
    const pip = s.pipelines.find((x: Record<string, unknown>) => x['id'] === p['id']) as
      | Record<string, unknown>
      | undefined;
    if (pip) pip['enabled'] = true;
    return json(r, 200, pip ?? {});
  });
  router.register('POST', '/api/orgs/:org/pipelines/:id/disable', (r, p) => {
    const pip = s.pipelines.find((x: Record<string, unknown>) => x['id'] === p['id']) as
      | Record<string, unknown>
      | undefined;
    if (pip) pip['enabled'] = false;
    return json(r, 200, pip ?? {});
  });
  router.register('GET', '/api/orgs/:org/pipelines/:id/preview-matches', (r) =>
    json(r, 200, s.previewResult),
  );
  router.register('GET', '/api/orgs/:org/pipelines/:id/revisions', (r, p) => {
    const pip = s.pipelines.find((x: Record<string, unknown>) => x['id'] === p['id']) as
      | Record<string, unknown>
      | undefined;
    const revisions = (pip?.['revisions'] as unknown[]) ?? [];
    return json(r, 200, list(revisions));
  });

  router.register('GET', '/api/orgs/:org/destinations', (r) => json(r, 200, list(s.destinations)));
  router.register('POST', '/api/orgs/:org/destinations', async (r) => {
    const body = await r.request().postDataJSON();
    const d = {
      id: mockId('dst'),
      created_at: '2026-08-17T09:00:00Z',
      updated_at: '2026-08-17T09:00:00Z',
      ...body,
    };
    s.destinations.push(d);
    return json(r, 201, d);
  });
  router.register('GET', '/api/orgs/:org/destinations/:id', (r, p) => {
    const d = s.destinations.find((x: Record<string, unknown>) => x['id'] === p['id']);
    return json(r, d ? 200 : 404, d ?? { error: { code: 'not_found', message: 'not found' } });
  });
  router.register('PUT', '/api/orgs/:org/destinations/:id', async (r) =>
    json(r, 200, await r.request().postDataJSON()),
  );
  router.register('DELETE', '/api/orgs/:org/destinations/:id', (r) => r.fulfill({ status: 204 }));

  router.register('GET', '/api/orgs/:org/ado-credentials', (r) =>
    json(r, 200, list(s.adoCredentials)),
  );
  router.register('POST', '/api/orgs/:org/ado-credentials', async (r) => {
    const body = await r.request().postDataJSON();
    const c = { id: mockId('cred'), created_at: '2026-08-17T09:00:00Z', ...body };
    s.adoCredentials.push(c);
    return json(r, 201, c);
  });
  router.register('DELETE', '/api/orgs/:org/ado-credentials/:id', (r) =>
    r.fulfill({ status: 204 }),
  );

  router.register('GET', '/api/orgs/:org/repo-links', (r) => json(r, 200, list(s.repoLinks)));
  router.register('POST', '/api/orgs/:org/repo-links', async (r) => {
    const body = await r.request().postDataJSON();
    const l = { id: mockId('rl'), created_at: '2026-08-17T09:00:00Z', ...body };
    s.repoLinks.push(l);
    return json(r, 201, l);
  });
  router.register('DELETE', '/api/orgs/:org/repo-links/:id', (r) => r.fulfill({ status: 204 }));

  router.register('GET', '/api/orgs/:org/wizards', (r) =>
    json(r, 200, {
      items: [{ kind: 'app-observability', title: 'App Observability', steps: [] }],
      total: 1,
    }),
  );
  router.register('GET', '/api/orgs/:org/wizards/:kind', (r) =>
    json(r, 200, {
      kind: r.request().url().split('/').pop(),
      title: 'App Observability',
      steps: [],
    }),
  );
  router.register('POST', '/api/orgs/:org/wizards/commit', async (r) => {
    const body = (await r.request().postDataJSON()) as Record<string, unknown>;
    const p = {
      id: mockId('pip'),
      name: body['name'],
      enabled: false,
      source: 'wizard',
      created_at: '2026-08-17T09:00:00Z',
      updated_at: '2026-08-17T09:00:00Z',
    };
    s.pipelines.push(p);
    return json(r, 201, p);
  });

  router.register('GET', '/api/orgs/:org/audit', (r) => json(r, 200, list(s.auditRows)));

  // Schema endpoint — serves the visual builder schema fixture if seeded
  router.register('GET', '/api/schema/:version', (r) => {
    if (s.schema) return json(r, 200, s.schema);
    return json(r, 404, { error: { code: 'not_found', message: 'schema not seeded in mock' } });
  });
}

// Drift guard: list every registered route pattern
export function registeredRoutes(router: Router): string[] {
  // Access private routes via type cast for introspection
  return (router as unknown as { routes: Array<{ method: string; pattern: RegExp }> }).routes.map(
    (r) => `${r.method} ${r.pattern.source}`,
  );
}

// Helper: build a default MockState
export function defaultState(): MockState {
  resetMockState();
  return {
    me: null,
    orgs: [],
    clusters: [],
    collectors: [],
    pipelines: [],
    revisions: new Map(),
    destinations: [],
    adoCredentials: [],
    repoLinks: [],
    agentTokens: [],
    auditRows: [],
    attributes: { cluster: ['prod-eu-1'], role: ['metrics', 'logs', 'singleton', 'receiver'] },
    previewResult: { count: 2, collector_ids: ['col-0001', 'col-0002'] },
    validateResult: { valid: true, diagnostics: [] },
    servedConfig: {
      content: '',
      hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    },
    unmatched: [],
    authMethods: { oidc: true, local_admin: false },
    localAdminCreds: undefined,
    localAdminPersona: undefined,
    schema: undefined,
    visualRenderResult: undefined,
    graphViewResult: undefined,
    upgradeCheckResult: undefined,
    simulateRelabelResult: undefined,
    simulateLogsResult: undefined,
  };
}

// Suppress unused import warning
export type { Route };
