/**
 * Fullstack test fixtures.
 * Provides real-backend login helpers and DB-backed utilities.
 *
 * NEVER import the mocked `api` fixture here.
 * NEVER intercept network requests (page-level route mocks) in fullstack specs.
 */
import { test as base, expect, type Page } from '@playwright/test';

// Dev stack credentials (from dev/shepherd.dev.env)
export const DEV_ADMIN_USERNAME = 'admin';
export const DEV_ADMIN_PASSWORD = 'admin';
export const DEV_BASE_URL = 'http://localhost:8080';

// Local editor/viewer accounts seeded by `shepherd dev seed` on the platform
// org (internal/cli/dev.go's seedLocalUsers) — same login/password pair as
// the seed's seedEditorLogin/seedEditorPassword and
// seedViewerLogin/seedViewerPassword constants.
export const DEV_EDITOR = { username: 'editor', password: 'editor-dev-pass' };
export const DEV_VIEWER = { username: 'viewer', password: 'viewer-dev-pass' };

/**
 * loginAs performs a real POST /api/auth/local/login and waits for the
 * shepherd_session cookie to be set. Fast: ~1 round-trip, no browser redirect.
 *
 * Retries once on a 429 from internal/auth/login_throttle.go's per-login
 * bucket (burst 10, refill ~1/6s) — real, and shared across this whole
 * suite's single dev stack: with `workers: 1` and enough specs logging in as
 * the same username in a tight window (most fullstack specs use admin), the
 * bucket can be exhausted well before it refills. The server's own
 * Retry-After tells us exactly how long that takes; honoring it is the
 * correct response to a real rate limiter, not a flakiness workaround, and
 * a second 429 (or any non-200) still fails loudly.
 */
export async function loginAs(page: Page, username: string, password: string): Promise<void> {
  for (let attempt = 0; ; attempt++) {
    const resp = await page.request.post('/api/auth/local/login', {
      data: { username, password },
      headers: {
        'Content-Type': 'application/json',
        'X-Requested-With': 'XMLHttpRequest',
      },
    });
    if (resp.status() === 200) return;
    if (resp.status() === 429 && attempt === 0) {
      const retryAfterSeconds = Number(resp.headers()['retry-after']) || 6;
      await page.waitForTimeout(retryAfterSeconds * 1000 + 250);
      continue;
    }
    throw new Error(`loginAs failed: ${resp.status()} ${await resp.text()}`);
  }
}

/** loginAsAdmin is loginAs for the seeded bootstrap admin — kept as its own
 * export because every existing fullstack spec imports it by name. */
export async function loginAsAdmin(page: Page): Promise<void> {
  return loginAs(page, DEV_ADMIN_USERNAME, DEV_ADMIN_PASSWORD);
}

/**
 * forceRecompute triggers a lazy serve-cache recompute by sending a Connect-JSON
 * GetConfig RPC. The collector token ID and secret must be set as env vars or
 * passed explicitly. Uses the seeded dev agent token.
 */
export async function forceRecompute(
  page: Page,
  collectorCluster: string,
  collectorRole: string,
  tokenId = '00000000-de00-4000-a000-000000000001',
  tokenSecret = 'dev-only-agent-secret-32byteslong',
): Promise<void> {
  const creds = Buffer.from(`${tokenId}:${tokenSecret}`).toString('base64');
  const resp = await page.request.post('/collector.v1.CollectorService/GetConfig', {
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Basic ${creds}`,
    },
    data: {
      id: `fullstack-probe-${Date.now()}`,
      hash: '',
      localAttributes: { cluster: collectorCluster, role: collectorRole },
    },
  });
  // A non-200 (e.g. 401 for a rejected token) means the recompute was NOT
  // triggered, which defeats this helper's purpose — fail loudly.
  if (resp.status() !== 200) {
    throw new Error(`forceRecompute failed: ${resp.status()} ${await resp.text()}`);
  }
}

// timestampRe mirrors internal/serve/compute_test.go's normalize helper: it
// matches buildHeader's (internal/merge/merge.go) "// Generated by Shepherd
// <version> at <RFC3339>" line, which stamps time.Now() on every recompute.
// A spec comparing served-config content/hash across two recomputes must
// normalize this line first, or it is really asserting "these two recomputes
// happened in the same instant" rather than "these two recomputes produced
// the same config".
const timestampRe = /^\/\/ Generated by Shepherd .* at .*$/m;

/** normalizeServedConfig strips the recompute timestamp so content from two
 * different recomputes can be compared for actual (matching-relevant)
 * equality. */
export function normalizeServedConfig(content: string): string {
  return content.replace(timestampRe, '// Generated by Shepherd <version> at <timestamp>');
}

/** Fullstack test fixture type — same base as Playwright test, no mock api. */
export const test = base;
export { expect };
