//go:build e2ek8s

package k8s_test

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"connectrpc.com/connect"
	"sigs.k8s.io/e2e-framework/pkg/envconf"
	"sigs.k8s.io/e2e-framework/pkg/features"

	mgmtv1 "shepherd/gen/shepherd/mgmt/v1"
	"shepherd/internal/chartvalues"
)

// TestChartValuesConnectACluster is gate G10 (docs/gateway-tier-plan.md §6):
// values generated by Shepherd's own RenderChartValues RPC, installed with
// Grafana's REAL k8s-monitoring chart at the pinned version, produce an Alloy
// that registers with Shepherd and receives a pipeline. The unit specs prove
// the values validate against the chart's schema and `helm template` cleanly;
// only a running install proves the collectors actually attach — the
// "renders but does not attach" failure chartvalues' collectorName comment
// warns about.
//
// The operator's side is done exactly as the Connect a cluster dialog tells
// them: an app admin creates an agent token, the Secret command stores it, and
// helm installs the chart with the two generated files and nothing else.
func TestChartValuesConnectACluster(t *testing.T) {
	var (
		f           *fixture
		api         *shepherdAPI
		orgID       string
		collectorID string
		monNS       string
	)
	const (
		release  = "shepherd-g10"
		cluster  = "g10-cluster"
		password = "e2e-chart-values-admin-pass"
	)

	feat := features.New("chart values: generated values + real k8s-monitoring → Alloy registers and is served a pipeline").
		WithLabel("suite", "chartvalues").
		Setup(func(ctx context.Context, t *testing.T, cfg *envconf.Config) context.Context {
			f = newFixture(ctx, t, cfg, "chart-values")
			monNS = f.ns + "-mon"
			out := kubectlArgv(cfg, "-n", f.ns, "patch", "secret", chartSecretName, "--type=merge",
				"-p", fmt.Sprintf(`{"stringData":{"SHEPHERD_BOOTSTRAP_ADMIN_PASSWORD":%q}}`, password))
			if !strings.Contains(out, "patched") {
				t.Fatalf("setting the bootstrap admin password: %s", out)
			}
			// server.base_url is what RenderChartValues points collectors at;
			// in kind that is Shepherd's in-cluster Service.
			baseURL := fmt.Sprintf("http://%s.%s.svc.cluster.local:8080", release, f.ns)
			helmRun(t, cfg, f, "install", release, "--set replicas=1", "--set simulator.enabled=false",
				"--set config.server.base_url="+baseURL)
			waitDeploymentAvailable(t, cfg, f.ns, release)

			api = newShepherdAPI(t, cfg, f.ns, release)
			api.login(t, "admin", password)
			org, err := api.admin.CreateOrg(ctx, connect.NewRequest(&mgmtv1.CreateOrgRequest{
				Name: "g10", DisplayName: "G10", AdminGroupId: "g10-admins",
			}))
			if err != nil {
				t.Fatalf("CreateOrg: %v", err)
			}
			orgID = org.Msg.GetId()
			return ctx
		}).
		Assess("the generated values, installed with k8s-monitoring, register a collector with Shepherd",
			func(ctx context.Context, t *testing.T, cfg *envconf.Config) context.Context {
				rendered, err := api.fleet.RenderChartValues(ctx, connect.NewRequest(&mgmtv1.RenderChartValuesRequest{
					OrgId: orgID, ClusterName: cluster, Roles: []string{"metrics"}, PollFrequency: "10s", Namespace: monNS,
				}))
				if err != nil {
					t.Fatalf("RenderChartValues: %v", err)
				}
				r := rendered.Msg
				if r.GetClusterStatus() != "new" {
					t.Fatalf("cluster_status %q before any install, want new", r.GetClusterStatus())
				}

				token, err := api.admin.CreateAgentToken(ctx, connect.NewRequest(&mgmtv1.CreateAgentTokenRequest{Name: "g10"}))
				if err != nil {
					t.Fatalf("CreateAgentToken: %v", err)
				}
				// The Secret the credentials layer reads — the dialog's step 1.
				out := kubectlArgv(cfg, "create", "namespace", monNS)
				if !strings.Contains(out, "created") && !strings.Contains(out, "AlreadyExists") {
					t.Fatalf("creating %s: %s", monNS, out)
				}
				out = kubectlArgv(cfg, "-n", monNS, "create", "secret", "generic", r.GetSecretName(),
					"--from-literal="+chartvalues.SecretKeyTokenID+"="+token.Msg.GetId(),
					"--from-literal="+chartvalues.SecretKeyTokenSecret+"="+token.Msg.GetSecret())
				if !strings.Contains(out, "created") {
					t.Fatalf("creating the agent-token Secret: %s", out)
				}

				dir := t.TempDir()
				layer := filepath.Join(dir, "shepherd-layer.yaml")
				creds := filepath.Join(dir, "shepherd-credentials.yaml")
				if err := os.WriteFile(layer, []byte(r.GetValuesYaml()), 0o600); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(creds, []byte(r.GetCredentialsYaml()), 0o600); err != nil {
					t.Fatal(err)
				}
				// The real chart, from Grafana's repo, at the version the
				// values were checked against — and only the two generated files.
				helm := exec.Command("helm", "upgrade", "--install", "k8s-monitoring", "k8s-monitoring",
					"--repo", "https://grafana.github.io/helm-charts", "--version", r.GetChartVersion(),
					"--kubeconfig", cfg.KubeconfigFile(), "--namespace", monNS,
					"-f", layer, "-f", creds, "--wait", "--timeout", "5m")
				if out, err := helm.CombinedOutput(); err != nil {
					t.Fatalf("helm install k8s-monitoring %s: %v\n%s\n%s", r.GetChartVersion(), err, out, describeNS(cfg, monNS))
				}

				// The collector registers under its cluster attribute; an app
				// admin then claims the cluster for the org (the dialog's note).
				end := time.Now().Add(4 * time.Minute)
				for {
					resp, err := api.admin.ListClusters(ctx, connect.NewRequest(&mgmtv1.ListClustersRequest{}))
					found := false
					if err == nil {
						for _, c := range resp.Msg.GetItems() {
							if c.GetName() == cluster {
								found = true
							}
						}
					}
					if found {
						break
					}
					if time.Now().After(end) {
						t.Fatalf("cluster %q never registered with Shepherd within 4m\n%s\n--- alloy logs ---\n%s", cluster,
							describeNS(cfg, monNS), kubectlArgv(cfg, "-n", monNS, "logs", "-l", "app.kubernetes.io/name=alloy-metrics", "--tail=40"))
					}
					time.Sleep(5 * time.Second)
				}
				if _, err := api.admin.ClaimCluster(ctx, connect.NewRequest(&mgmtv1.ClaimClusterRequest{Cluster: cluster, OrgId: orgID})); err != nil {
					t.Fatalf("ClaimCluster: %v", err)
				}
				again, err := api.fleet.RenderChartValues(ctx, connect.NewRequest(&mgmtv1.RenderChartValuesRequest{
					OrgId: orgID, ClusterName: cluster, Roles: []string{"metrics"},
				}))
				if err != nil || again.Msg.GetClusterStatus() != "claimed" {
					t.Fatalf("after the claim, RenderChartValues reports %v (err %v), want claimed", again.Msg.GetClusterStatus(), err)
				}

				collectors, err := api.fleet.ListCollectors(ctx, connect.NewRequest(&mgmtv1.ListCollectorsRequest{OrgId: orgID}))
				if err != nil {
					t.Fatalf("ListCollectors: %v", err)
				}
				for _, c := range collectors.Msg.GetItems() {
					if c.GetCluster() == cluster && c.GetRole() == "metrics" {
						collectorID = c.GetId()
					}
				}
				if collectorID == "" {
					t.Fatalf("no metrics collector for %s in the org's fleet: %v", cluster, collectors.Msg.GetItems())
				}
				return ctx
			}).
		Assess("the registered collector is served a pipeline and reports it APPLIED",
			func(ctx context.Context, t *testing.T, cfg *envconf.Config) context.Context {
				p, err := api.pipelines.CreatePipeline(ctx, connect.NewRequest(&mgmtv1.CreatePipelineRequest{
					OrgId: orgID, Name: "g10-pipe", Contents: `prometheus.exporter.self "g10" { }`,
					Matchers: []string{`cluster="` + cluster + `"`, `role="metrics"`},
				}))
				if err != nil {
					t.Fatalf("CreatePipeline: %v", err)
				}
				if _, err := api.pipelines.EnablePipeline(ctx, connect.NewRequest(&mgmtv1.EnablePipelineRequest{
					OrgId: orgID, Id: p.Msg.GetId(),
				})); err != nil {
					t.Fatalf("EnablePipeline: %v", err)
				}

				end := time.Now().Add(3 * time.Minute)
				served, status := false, ""
				for time.Now().Before(end) {
					sc, err := api.fleet.GetServedConfig(ctx, connect.NewRequest(&mgmtv1.GetServedConfigRequest{OrgId: orgID, Id: collectorID}))
					served = err == nil && strings.Contains(sc.Msg.GetContent(), `declare "pipe_g10_pipe"`)
					c, err := api.fleet.GetCollector(ctx, connect.NewRequest(&mgmtv1.GetCollectorRequest{OrgId: orgID, Id: collectorID}))
					if err == nil {
						status = c.Msg.GetRemoteConfigStatus()
					}
					if served && status == "APPLIED" {
						return ctx
					}
					time.Sleep(5 * time.Second)
				}
				t.Fatalf("pipeline served=%v, collector remote_config_status=%q after 3m\n--- alloy logs ---\n%s", served, status,
					kubectlArgv(cfg, "-n", monNS, "logs", "-l", "app.kubernetes.io/name=alloy-metrics", "--tail=60"))
				return ctx
			}).
		Teardown(func(ctx context.Context, t *testing.T, cfg *envconf.Config) context.Context {
			if api != nil {
				api.close()
			}
			if !keepCluster() && monNS != "" {
				// The chart's pre-delete hook removes the Alloy resource and its
				// finalizer; deleting the namespace first would strand them.
				//nolint:errcheck // best-effort teardown
				_ = exec.Command("helm", "uninstall", "k8s-monitoring", "--kubeconfig", cfg.KubeconfigFile(),
					"--namespace", monNS, "--wait", "--timeout", "3m").Run()
				_ = kubectlArgv(cfg, "delete", "namespace", monNS, "--ignore-not-found", "--wait=false")
			}
			f.cleanup(cfg)
			return ctx
		}).
		Feature()

	testenv.Test(t, feat)
}
