// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ado_credentials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createADOCredential = `-- name: CreateADOCredential :one
INSERT INTO ado_credentials (org_id, name, ado_org_url, entra_tenant_id, client_id, client_secret_enc)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, name, ado_org_url, entra_tenant_id, client_id, client_secret_enc, created_at, updated_at
`

type CreateADOCredentialParams struct {
	OrgID           pgtype.UUID `json:"org_id"`
	Name            string      `json:"name"`
	AdoOrgUrl       string      `json:"ado_org_url"`
	EntraTenantID   string      `json:"entra_tenant_id"`
	ClientID        string      `json:"client_id"`
	ClientSecretEnc []byte      `json:"client_secret_enc"`
}

func (q *Queries) CreateADOCredential(ctx context.Context, arg CreateADOCredentialParams) (AdoCredential, error) {
	row := q.db.QueryRow(ctx, createADOCredential,
		arg.OrgID,
		arg.Name,
		arg.AdoOrgUrl,
		arg.EntraTenantID,
		arg.ClientID,
		arg.ClientSecretEnc,
	)
	var i AdoCredential
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.AdoOrgUrl,
		&i.EntraTenantID,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteADOCredential = `-- name: DeleteADOCredential :exec
DELETE FROM ado_credentials WHERE id = $1
`

func (q *Queries) DeleteADOCredential(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteADOCredential, id)
	return err
}

const getADOCredentialByID = `-- name: GetADOCredentialByID :one
SELECT id, org_id, name, ado_org_url, entra_tenant_id, client_id, client_secret_enc, created_at, updated_at FROM ado_credentials WHERE id = $1
`

func (q *Queries) GetADOCredentialByID(ctx context.Context, id pgtype.UUID) (AdoCredential, error) {
	row := q.db.QueryRow(ctx, getADOCredentialByID, id)
	var i AdoCredential
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.AdoOrgUrl,
		&i.EntraTenantID,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listADOCredentialsByOrg = `-- name: ListADOCredentialsByOrg :many
SELECT id, org_id, name, ado_org_url, entra_tenant_id, client_id, client_secret_enc, created_at, updated_at FROM ado_credentials WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListADOCredentialsByOrg(ctx context.Context, orgID pgtype.UUID) ([]AdoCredential, error) {
	rows, err := q.db.Query(ctx, listADOCredentialsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdoCredential
	for rows.Next() {
		var i AdoCredential
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.AdoOrgUrl,
			&i.EntraTenantID,
			&i.ClientID,
			&i.ClientSecretEnc,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateADOCredential = `-- name: UpdateADOCredential :one
UPDATE ado_credentials
SET name              = $2,
    ado_org_url       = $3,
    entra_tenant_id   = $4,
    client_id         = $5,
    client_secret_enc = $6,
    updated_at        = now()
WHERE id = $1
RETURNING id, org_id, name, ado_org_url, entra_tenant_id, client_id, client_secret_enc, created_at, updated_at
`

type UpdateADOCredentialParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	AdoOrgUrl       string      `json:"ado_org_url"`
	EntraTenantID   string      `json:"entra_tenant_id"`
	ClientID        string      `json:"client_id"`
	ClientSecretEnc []byte      `json:"client_secret_enc"`
}

func (q *Queries) UpdateADOCredential(ctx context.Context, arg UpdateADOCredentialParams) (AdoCredential, error) {
	row := q.db.QueryRow(ctx, updateADOCredential,
		arg.ID,
		arg.Name,
		arg.AdoOrgUrl,
		arg.EntraTenantID,
		arg.ClientID,
		arg.ClientSecretEnc,
	)
	var i AdoCredential
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.AdoOrgUrl,
		&i.EntraTenantID,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
