// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentToken = `-- name: CreateAgentToken :one
INSERT INTO agent_tokens (name, token_hash, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, token_hash, created_by, revoked_at, created_at, updated_at
`

type CreateAgentTokenParams struct {
	Name      string `json:"name"`
	TokenHash []byte `json:"token_hash"`
	CreatedBy string `json:"created_by"`
}

func (q *Queries) CreateAgentToken(ctx context.Context, arg CreateAgentTokenParams) (AgentToken, error) {
	row := q.db.QueryRow(ctx, createAgentToken, arg.Name, arg.TokenHash, arg.CreatedBy)
	var i AgentToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAgentTokenWithID = `-- name: CreateAgentTokenWithID :one
INSERT INTO agent_tokens (id, name, token_hash, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, token_hash, created_by, revoked_at, created_at, updated_at
`

type CreateAgentTokenWithIDParams struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	TokenHash []byte      `json:"token_hash"`
	CreatedBy string      `json:"created_by"`
}

func (q *Queries) CreateAgentTokenWithID(ctx context.Context, arg CreateAgentTokenWithIDParams) (AgentToken, error) {
	row := q.db.QueryRow(ctx, createAgentTokenWithID,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedBy,
	)
	var i AgentToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentTokenByID = `-- name: GetAgentTokenByID :one
SELECT id, name, token_hash, created_by, revoked_at, created_at, updated_at FROM agent_tokens WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) GetAgentTokenByID(ctx context.Context, id pgtype.UUID) (AgentToken, error) {
	row := q.db.QueryRow(ctx, getAgentTokenByID, id)
	var i AgentToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentTokens = `-- name: ListAgentTokens :many
SELECT id, name, token_hash, created_by, revoked_at, created_at, updated_at FROM agent_tokens ORDER BY created_at DESC
`

func (q *Queries) ListAgentTokens(ctx context.Context) ([]AgentToken, error) {
	rows, err := q.db.Query(ctx, listAgentTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentToken
	for rows.Next() {
		var i AgentToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedBy,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAgentToken = `-- name: RevokeAgentToken :exec
UPDATE agent_tokens SET revoked_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) RevokeAgentToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAgentToken, id)
	return err
}
