// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_identities.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentIdentity = `-- name: CreateAgentIdentity :one
INSERT INTO agent_identities (issuer, app_id, org_id, clusters, roles, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, issuer, app_id, org_id, clusters, roles, created_by, created_at, updated_at
`

type CreateAgentIdentityParams struct {
	Issuer    string          `json:"issuer"`
	AppID     string          `json:"app_id"`
	OrgID     pgtype.UUID     `json:"org_id"`
	Clusters  json.RawMessage `json:"clusters"`
	Roles     json.RawMessage `json:"roles"`
	CreatedBy string          `json:"created_by"`
}

// clusters and roles are jsonb string arrays marshaled in Go; '[]' means "any".
func (q *Queries) CreateAgentIdentity(ctx context.Context, arg CreateAgentIdentityParams) (AgentIdentity, error) {
	row := q.db.QueryRow(ctx, createAgentIdentity,
		arg.Issuer,
		arg.AppID,
		arg.OrgID,
		arg.Clusters,
		arg.Roles,
		arg.CreatedBy,
	)
	var i AgentIdentity
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.AppID,
		&i.OrgID,
		&i.Clusters,
		&i.Roles,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgentIdentity = `-- name: DeleteAgentIdentity :execrows
DELETE FROM agent_identities WHERE issuer = $1 AND app_id = $2
`

type DeleteAgentIdentityParams struct {
	Issuer string `json:"issuer"`
	AppID  string `json:"app_id"`
}

func (q *Queries) DeleteAgentIdentity(ctx context.Context, arg DeleteAgentIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentIdentity, arg.Issuer, arg.AppID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentIdentityByAppID = `-- name: GetAgentIdentityByAppID :one
SELECT id, issuer, app_id, org_id, clusters, roles, created_by, created_at, updated_at FROM agent_identities WHERE issuer = $1 AND app_id = $2
`

type GetAgentIdentityByAppIDParams struct {
	Issuer string `json:"issuer"`
	AppID  string `json:"app_id"`
}

// The lookup the collector auth path makes: resolve a token's (issuer, app_id)
// to its org and allowlists.
func (q *Queries) GetAgentIdentityByAppID(ctx context.Context, arg GetAgentIdentityByAppIDParams) (AgentIdentity, error) {
	row := q.db.QueryRow(ctx, getAgentIdentityByAppID, arg.Issuer, arg.AppID)
	var i AgentIdentity
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.AppID,
		&i.OrgID,
		&i.Clusters,
		&i.Roles,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentIdentities = `-- name: ListAgentIdentities :many
SELECT ai.id, ai.issuer, ai.app_id, ai.org_id, ai.clusters, ai.roles, ai.created_by, ai.created_at, ai.updated_at, o.name AS org_name
FROM agent_identities ai
JOIN orgs o ON o.id = ai.org_id
ORDER BY ai.created_at DESC
`

type ListAgentIdentitiesRow struct {
	ID        pgtype.UUID        `json:"id"`
	Issuer    string             `json:"issuer"`
	AppID     string             `json:"app_id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Clusters  json.RawMessage    `json:"clusters"`
	Roles     json.RawMessage    `json:"roles"`
	CreatedBy string             `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	OrgName   string             `json:"org_name"`
}

// Admin/CLI listing, with the org's slug so a human can read it.
func (q *Queries) ListAgentIdentities(ctx context.Context) ([]ListAgentIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, listAgentIdentities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentIdentitiesRow
	for rows.Next() {
		var i ListAgentIdentitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Issuer,
			&i.AppID,
			&i.OrgID,
			&i.Clusters,
			&i.Roles,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
