// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attributes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDistinctAttributeKeys = `-- name: ListDistinctAttributeKeys :many
SELECT DISTINCT key
FROM (
  SELECT jsonb_object_keys(ci.local_attributes) AS key
  FROM collector_instances ci
  JOIN collectors c ON ci.collector_id = c.id
  JOIN clusters cl ON c.cluster_id = cl.id
  WHERE cl.org_id = $1
  UNION VALUES ('cluster'), ('role')
) AS keys
ORDER BY key
`

func (q *Queries) ListDistinctAttributeKeys(ctx context.Context, orgID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctAttributeKeys, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctAttributeValues = `-- name: ListDistinctAttributeValues :many
SELECT DISTINCT val::text AS val
FROM (
  SELECT ci.local_attributes ->> $2::text AS val
  FROM collector_instances ci
  JOIN collectors c ON ci.collector_id = c.id
  JOIN clusters cl ON c.cluster_id = cl.id
  WHERE cl.org_id = $1
    AND ci.local_attributes ? $2::text
  UNION
  SELECT CASE WHEN $2::text = 'cluster' THEN cl2.name ELSE c2.role END AS val
  FROM collectors c2
  JOIN clusters cl2 ON c2.cluster_id = cl2.id
  WHERE cl2.org_id = $1
    AND $2::text IN ('cluster', 'role')
) AS vals
WHERE val IS NOT NULL
ORDER BY val
`

type ListDistinctAttributeValuesParams struct {
	OrgID   pgtype.UUID `json:"org_id"`
	Column2 string      `json:"column_2"`
}

func (q *Queries) ListDistinctAttributeValues(ctx context.Context, arg ListDistinctAttributeValuesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctAttributeValues, arg.OrgID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var val string
		if err := rows.Scan(&val); err != nil {
			return nil, err
		}
		items = append(items, val)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
