// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLog = `-- name: CountAuditLog :one
SELECT COUNT(*)::int AS total FROM audit_log
WHERE ($1::uuid IS NULL OR org_id = $1)
  AND (NULLIF($2::text, '') IS NULL OR actor ILIKE '%' || $2 || '%')
  AND (NULLIF($3::text, '') IS NULL OR action = $3)
`

type CountAuditLogParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 string      `json:"column_2"`
	Column3 string      `json:"column_3"`
}

func (q *Queries) CountAuditLog(ctx context.Context, arg CountAuditLogParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAuditLog, arg.Column1, arg.Column2, arg.Column3)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (actor, actor_type, org_id, action, resource_type, resource_id, detail, on_behalf_of)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditLogParams struct {
	Actor        string          `json:"actor"`
	ActorType    string          `json:"actor_type"`
	OrgID        pgtype.UUID     `json:"org_id"`
	Action       string          `json:"action"`
	ResourceType string          `json:"resource_type"`
	ResourceID   string          `json:"resource_id"`
	Detail       json.RawMessage `json:"detail"`
	OnBehalfOf   pgtype.Text     `json:"on_behalf_of"`
}

// on_behalf_of is G13's second attribution half (docs/gateway-tier-plan.md):
// the human a machine actor's write is performed for. NULL for every human
// session's own action; a 'service_account' actor_type row always carries
// one, because internal/mgmtapi.requireWriteAuthorized rejects a machine
// write with no on-behalf-of before any InsertAuditLog call is reached — see
// that function's doc comment for the reject-vs-record-as-unattributed
// decision.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.Actor,
		arg.ActorType,
		arg.OrgID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Detail,
		arg.OnBehalfOf,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, at, actor, actor_type, org_id, action, resource_type, resource_id, detail, on_behalf_of FROM audit_log
WHERE ($1::uuid IS NULL OR org_id = $1)
  AND (NULLIF($2::text, '') IS NULL OR actor ILIKE '%' || $2 || '%')
  AND (NULLIF($3::text, '') IS NULL OR action = $3)
ORDER BY at DESC
LIMIT $4 OFFSET $5
`

type ListAuditLogParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 string      `json:"column_2"`
	Column3 string      `json:"column_3"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Actor,
			&i.ActorType,
			&i.OrgID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Detail,
			&i.OnBehalfOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
