// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: beacon.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredBeaconInventory = `-- name: DeleteExpiredBeaconInventory :execrows
DELETE FROM beacon_inventory WHERE last_seen < $1
`

// Called from agentapi's existing sweeper (Sweeper.sweep), same shape as
// MarkStaleInstancesInactive/DeleteOldInstances for collector_instances: a
// collector that stops reporting ages out instead of lingering as a
// permanently-healthy ghost (plan §4, W5).
func (q *Queries) DeleteExpiredBeaconInventory(ctx context.Context, lastSeen pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredBeaconInventory, lastSeen)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBeaconInventoryByToken = `-- name: ListBeaconInventoryByToken :many
SELECT id, token_id, instance_label, component_name, healthy, last_seen, created_at FROM beacon_inventory WHERE token_id = $1 ORDER BY instance_label, component_name
`

func (q *Queries) ListBeaconInventoryByToken(ctx context.Context, tokenID pgtype.UUID) ([]BeaconInventory, error) {
	rows, err := q.db.Query(ctx, listBeaconInventoryByToken, tokenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BeaconInventory
	for rows.Next() {
		var i BeaconInventory
		if err := rows.Scan(
			&i.ID,
			&i.TokenID,
			&i.InstanceLabel,
			&i.ComponentName,
			&i.Healthy,
			&i.LastSeen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBeaconComponent = `-- name: UpsertBeaconComponent :one
INSERT INTO beacon_inventory (token_id, instance_label, component_name, healthy, last_seen)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (token_id, instance_label, component_name) DO UPDATE SET
    healthy   = EXCLUDED.healthy,
    last_seen = now()
RETURNING id, token_id, instance_label, component_name, healthy, last_seen, created_at
`

type UpsertBeaconComponentParams struct {
	TokenID       pgtype.UUID `json:"token_id"`
	InstanceLabel string      `json:"instance_label"`
	ComponentName string      `json:"component_name"`
	Healthy       bool        `json:"healthy"`
}

// token_id + instance_label + component_name is this table's identity (see
// 0010_beacon_inventory.up.sql). Re-reporting the same component just
// refreshes healthy/last_seen -- a collector polling every scrape interval
// does not grow this table, it only keeps rows alive.
func (q *Queries) UpsertBeaconComponent(ctx context.Context, arg UpsertBeaconComponentParams) (BeaconInventory, error) {
	row := q.db.QueryRow(ctx, upsertBeaconComponent,
		arg.TokenID,
		arg.InstanceLabel,
		arg.ComponentName,
		arg.Healthy,
	)
	var i BeaconInventory
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.InstanceLabel,
		&i.ComponentName,
		&i.Healthy,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}
