// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clusters.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimCluster = `-- name: ClaimCluster :exec
UPDATE clusters SET org_id = $2, updated_at = now() WHERE id = $1
`

type ClaimClusterParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) ClaimCluster(ctx context.Context, arg ClaimClusterParams) error {
	_, err := q.db.Exec(ctx, claimCluster, arg.ID, arg.OrgID)
	return err
}

const getClusterByID = `-- name: GetClusterByID :one
SELECT id, name, org_id, created_at, updated_at FROM clusters WHERE id = $1
`

func (q *Queries) GetClusterByID(ctx context.Context, id pgtype.UUID) (Cluster, error) {
	row := q.db.QueryRow(ctx, getClusterByID, id)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClusterByName = `-- name: GetClusterByName :one
SELECT id, name, org_id, created_at, updated_at FROM clusters WHERE name = $1
`

func (q *Queries) GetClusterByName(ctx context.Context, name string) (Cluster, error) {
	row := q.db.QueryRow(ctx, getClusterByName, name)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllClusters = `-- name: ListAllClusters :many
SELECT id, name, org_id, created_at, updated_at FROM clusters ORDER BY created_at
`

func (q *Queries) ListAllClusters(ctx context.Context) ([]Cluster, error) {
	rows, err := q.db.Query(ctx, listAllClusters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cluster
	for rows.Next() {
		var i Cluster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClustersByOrg = `-- name: ListClustersByOrg :many
SELECT id, name, org_id, created_at, updated_at FROM clusters WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListClustersByOrg(ctx context.Context, orgID pgtype.UUID) ([]Cluster, error) {
	rows, err := q.db.Query(ctx, listClustersByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cluster
	for rows.Next() {
		var i Cluster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnclaimedClusters = `-- name: ListUnclaimedClusters :many
SELECT id, name, org_id, created_at, updated_at FROM clusters WHERE org_id IS NULL ORDER BY created_at
`

func (q *Queries) ListUnclaimedClusters(ctx context.Context) ([]Cluster, error) {
	rows, err := q.db.Query(ctx, listUnclaimedClusters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cluster
	for rows.Next() {
		var i Cluster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unclaimCluster = `-- name: UnclaimCluster :exec
UPDATE clusters SET org_id = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) UnclaimCluster(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unclaimCluster, id)
	return err
}

const upsertCluster = `-- name: UpsertCluster :one
INSERT INTO clusters (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE SET updated_at = now()
RETURNING id, name, org_id, created_at, updated_at
`

func (q *Queries) UpsertCluster(ctx context.Context, name string) (Cluster, error) {
	row := q.db.QueryRow(ctx, upsertCluster, name)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
