// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collector_instances.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearStaleFailedStatus = `-- name: ClearStaleFailedStatus :exec
UPDATE collector_instances
SET remote_config_status = 'APPLIED',
    remote_config_error  = NULL,
    updated_at           = now()
WHERE id = $1
  -- Also covers a status that was never reported (NULL) or was cleared by the
  -- sweeper's inactive marker: agents report a status only when they apply a
  -- CHANGE, so a healthy collector that applied once and then polled steadily
  -- would otherwise sit at UNKNOWN in the UI forever. A status the agent is
  -- actively re-reporting is written by UpdateInstanceStatus earlier in the
  -- same request and still wins, because this runs only when the poll carried
  -- no status payload at all.
  AND (remote_config_status IS NULL
       OR remote_config_status IN ('FAILED', 'inactive', ''))
`

// A poll that carries no RemoteConfigStatus payload but whose reported hash
// matches what GetConfig actually served means the agent is healthy on its
// current config (see B1) — clear a stale FAILED marker back to APPLIED.
// Scoped to rows currently FAILED: a genuine FAILED the agent keeps
// re-reporting is persisted by UpdateInstanceStatus earlier in the same
// request and must win, so this call is a no-op whenever that happened.
func (q *Queries) ClearStaleFailedStatus(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, clearStaleFailedStatus, id)
	return err
}

const countActiveInstances = `-- name: CountActiveInstances :one
SELECT COUNT(*)::bigint AS total
FROM collector_instances
WHERE unregistered_at IS NULL
  AND (remote_config_status IS NULL OR remote_config_status != 'inactive')
`

// Feeds the shepherd_active_collectors gauge. "Active" is the definition the
// gauge's help text already claimed: registered, not swept to 'inactive'.
// Written as a query rather than derived from a list so the sweeper does not
// pull every instance row once a tick just to count them.
func (q *Queries) CountActiveInstances(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveInstances)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const deleteOldInstances = `-- name: DeleteOldInstances :exec
DELETE FROM collector_instances WHERE last_seen < $1
`

func (q *Queries) DeleteOldInstances(ctx context.Context, lastSeen pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldInstances, lastSeen)
	return err
}

const getCollectorInstanceByID = `-- name: GetCollectorInstanceByID :one
SELECT id, collector_id, name, local_attributes, alloy_version, os, last_seen, unregistered_at, remote_config_status, remote_config_error, created_at, updated_at FROM collector_instances WHERE id = $1
`

func (q *Queries) GetCollectorInstanceByID(ctx context.Context, id string) (CollectorInstance, error) {
	row := q.db.QueryRow(ctx, getCollectorInstanceByID, id)
	var i CollectorInstance
	err := row.Scan(
		&i.ID,
		&i.CollectorID,
		&i.Name,
		&i.LocalAttributes,
		&i.AlloyVersion,
		&i.Os,
		&i.LastSeen,
		&i.UnregisteredAt,
		&i.RemoteConfigStatus,
		&i.RemoteConfigError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestCollectorInstanceSummary = `-- name: GetLatestCollectorInstanceSummary :one
SELECT remote_config_status, last_seen, alloy_version FROM collector_instances
WHERE collector_id = $1 AND unregistered_at IS NULL
ORDER BY last_seen DESC
LIMIT 1
`

type GetLatestCollectorInstanceSummaryRow struct {
	RemoteConfigStatus pgtype.Text        `json:"remote_config_status"`
	LastSeen           pgtype.Timestamptz `json:"last_seen"`
	AlloyVersion       pgtype.Text        `json:"alloy_version"`
}

// Status, last-seen, and version of the most recently reporting live
// instance for a collector, in a single round trip (used by the collector
// list endpoint instead of N per-row status-only lookups).
func (q *Queries) GetLatestCollectorInstanceSummary(ctx context.Context, collectorID pgtype.UUID) (GetLatestCollectorInstanceSummaryRow, error) {
	row := q.db.QueryRow(ctx, getLatestCollectorInstanceSummary, collectorID)
	var i GetLatestCollectorInstanceSummaryRow
	err := row.Scan(&i.RemoteConfigStatus, &i.LastSeen, &i.AlloyVersion)
	return i, err
}

const listCollectorInstancesByCollector = `-- name: ListCollectorInstancesByCollector :many
SELECT name, alloy_version, os, last_seen, remote_config_status, remote_config_error, local_attributes
FROM collector_instances
WHERE collector_id = $1 AND unregistered_at IS NULL
ORDER BY last_seen DESC NULLS LAST
`

type ListCollectorInstancesByCollectorRow struct {
	Name               string             `json:"name"`
	AlloyVersion       pgtype.Text        `json:"alloy_version"`
	Os                 pgtype.Text        `json:"os"`
	LastSeen           pgtype.Timestamptz `json:"last_seen"`
	RemoteConfigStatus pgtype.Text        `json:"remote_config_status"`
	RemoteConfigError  pgtype.Text        `json:"remote_config_error"`
	LocalAttributes    json.RawMessage    `json:"local_attributes"`
}

// All live (still-registered) instances reporting under a collector,
// newest last_seen first, for the collector detail view.
func (q *Queries) ListCollectorInstancesByCollector(ctx context.Context, collectorID pgtype.UUID) ([]ListCollectorInstancesByCollectorRow, error) {
	rows, err := q.db.Query(ctx, listCollectorInstancesByCollector, collectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectorInstancesByCollectorRow
	for rows.Next() {
		var i ListCollectorInstancesByCollectorRow
		if err := rows.Scan(
			&i.Name,
			&i.AlloyVersion,
			&i.Os,
			&i.LastSeen,
			&i.RemoteConfigStatus,
			&i.RemoteConfigError,
			&i.LocalAttributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaleInstancesInactive = `-- name: MarkStaleInstancesInactive :exec
UPDATE collector_instances
SET remote_config_status = 'inactive', updated_at = now()
WHERE last_seen < $1
  AND unregistered_at IS NULL
  AND (remote_config_status IS NULL OR remote_config_status != 'inactive')
`

func (q *Queries) MarkStaleInstancesInactive(ctx context.Context, lastSeen pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, markStaleInstancesInactive, lastSeen)
	return err
}

const unregisterInstance = `-- name: UnregisterInstance :exec
UPDATE collector_instances
SET unregistered_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UnregisterInstance(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, unregisterInstance, id)
	return err
}

const updateInstanceStatus = `-- name: UpdateInstanceStatus :exec
UPDATE collector_instances
SET remote_config_status = $2,
    remote_config_error  = $3,
    updated_at           = now()
WHERE id = $1
`

type UpdateInstanceStatusParams struct {
	ID                 string      `json:"id"`
	RemoteConfigStatus pgtype.Text `json:"remote_config_status"`
	RemoteConfigError  pgtype.Text `json:"remote_config_error"`
}

func (q *Queries) UpdateInstanceStatus(ctx context.Context, arg UpdateInstanceStatusParams) error {
	_, err := q.db.Exec(ctx, updateInstanceStatus, arg.ID, arg.RemoteConfigStatus, arg.RemoteConfigError)
	return err
}

const upsertCollectorInstance = `-- name: UpsertCollectorInstance :one
INSERT INTO collector_instances (id, collector_id, name, local_attributes, alloy_version, os, last_seen)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (id) DO UPDATE SET
    collector_id = EXCLUDED.collector_id,
    name         = CASE
                        WHEN EXCLUDED.name = '' OR EXCLUDED.name = collector_instances.id THEN collector_instances.name
                        ELSE EXCLUDED.name
                    END,
    local_attributes = EXCLUDED.local_attributes,
    alloy_version = EXCLUDED.alloy_version,
    os           = EXCLUDED.os,
    last_seen    = now(),
    remote_config_status = CASE
                                WHEN collector_instances.remote_config_status = 'inactive' THEN NULL
                                ELSE collector_instances.remote_config_status
                            END,
    updated_at   = now()
RETURNING id, collector_id, name, local_attributes, alloy_version, os, last_seen, unregistered_at, remote_config_status, remote_config_error, created_at, updated_at
`

type UpsertCollectorInstanceParams struct {
	ID              string          `json:"id"`
	CollectorID     pgtype.UUID     `json:"collector_id"`
	Name            string          `json:"name"`
	LocalAttributes json.RawMessage `json:"local_attributes"`
	AlloyVersion    pgtype.Text     `json:"alloy_version"`
	Os              pgtype.Text     `json:"os"`
}

// On conflict, an incoming name that is empty or equal to the wire id (both
// signal "caller has no real display name to report, e.g. a bare poll with
// no collector.name attribute") never clobbers a previously-known display
// name. A successful upsert also counts as liveness recovery: it clears a
// stale 'inactive' status marker left by the lifecycle sweeper so a
// reconnecting instance shows live again.
func (q *Queries) UpsertCollectorInstance(ctx context.Context, arg UpsertCollectorInstanceParams) (CollectorInstance, error) {
	row := q.db.QueryRow(ctx, upsertCollectorInstance,
		arg.ID,
		arg.CollectorID,
		arg.Name,
		arg.LocalAttributes,
		arg.AlloyVersion,
		arg.Os,
	)
	var i CollectorInstance
	err := row.Scan(
		&i.ID,
		&i.CollectorID,
		&i.Name,
		&i.LocalAttributes,
		&i.AlloyVersion,
		&i.Os,
		&i.LastSeen,
		&i.UnregisteredAt,
		&i.RemoteConfigStatus,
		&i.RemoteConfigError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
