// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collector_instances.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOldInstances = `-- name: DeleteOldInstances :exec
DELETE FROM collector_instances WHERE last_seen < $1
`

func (q *Queries) DeleteOldInstances(ctx context.Context, lastSeen pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldInstances, lastSeen)
	return err
}

const getCollectorInstanceByID = `-- name: GetCollectorInstanceByID :one
SELECT id, collector_id, name, local_attributes, alloy_version, os, last_seen, unregistered_at, remote_config_status, remote_config_error, created_at, updated_at FROM collector_instances WHERE id = $1
`

func (q *Queries) GetCollectorInstanceByID(ctx context.Context, id string) (CollectorInstance, error) {
	row := q.db.QueryRow(ctx, getCollectorInstanceByID, id)
	var i CollectorInstance
	err := row.Scan(
		&i.ID,
		&i.CollectorID,
		&i.Name,
		&i.LocalAttributes,
		&i.AlloyVersion,
		&i.Os,
		&i.LastSeen,
		&i.UnregisteredAt,
		&i.RemoteConfigStatus,
		&i.RemoteConfigError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestCollectorInstanceStatus = `-- name: GetLatestCollectorInstanceStatus :one
SELECT remote_config_status FROM collector_instances
WHERE collector_id = $1 AND unregistered_at IS NULL
ORDER BY last_seen DESC
LIMIT 1
`

func (q *Queries) GetLatestCollectorInstanceStatus(ctx context.Context, collectorID pgtype.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getLatestCollectorInstanceStatus, collectorID)
	var remote_config_status pgtype.Text
	err := row.Scan(&remote_config_status)
	return remote_config_status, err
}

const markStaleInstancesInactive = `-- name: MarkStaleInstancesInactive :exec
UPDATE collector_instances
SET remote_config_status = 'inactive', updated_at = now()
WHERE last_seen < $1
  AND unregistered_at IS NULL
  AND (remote_config_status IS NULL OR remote_config_status != 'inactive')
`

func (q *Queries) MarkStaleInstancesInactive(ctx context.Context, lastSeen pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, markStaleInstancesInactive, lastSeen)
	return err
}

const unregisterInstance = `-- name: UnregisterInstance :exec
UPDATE collector_instances
SET unregistered_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UnregisterInstance(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, unregisterInstance, id)
	return err
}

const updateInstanceLastSeen = `-- name: UpdateInstanceLastSeen :exec
UPDATE collector_instances
SET last_seen = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateInstanceLastSeen(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateInstanceLastSeen, id)
	return err
}

const updateInstanceStatus = `-- name: UpdateInstanceStatus :exec
UPDATE collector_instances
SET remote_config_status = $2,
    remote_config_error  = $3,
    updated_at           = now()
WHERE id = $1
`

type UpdateInstanceStatusParams struct {
	ID                 string      `json:"id"`
	RemoteConfigStatus pgtype.Text `json:"remote_config_status"`
	RemoteConfigError  pgtype.Text `json:"remote_config_error"`
}

func (q *Queries) UpdateInstanceStatus(ctx context.Context, arg UpdateInstanceStatusParams) error {
	_, err := q.db.Exec(ctx, updateInstanceStatus, arg.ID, arg.RemoteConfigStatus, arg.RemoteConfigError)
	return err
}

const upsertCollectorInstance = `-- name: UpsertCollectorInstance :one
INSERT INTO collector_instances (id, collector_id, name, local_attributes, alloy_version, os, last_seen)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (id) DO UPDATE SET
    collector_id = EXCLUDED.collector_id,
    name         = EXCLUDED.name,
    local_attributes = EXCLUDED.local_attributes,
    alloy_version = EXCLUDED.alloy_version,
    os           = EXCLUDED.os,
    last_seen    = now(),
    updated_at   = now()
RETURNING id, collector_id, name, local_attributes, alloy_version, os, last_seen, unregistered_at, remote_config_status, remote_config_error, created_at, updated_at
`

type UpsertCollectorInstanceParams struct {
	ID              string          `json:"id"`
	CollectorID     pgtype.UUID     `json:"collector_id"`
	Name            string          `json:"name"`
	LocalAttributes json.RawMessage `json:"local_attributes"`
	AlloyVersion    pgtype.Text     `json:"alloy_version"`
	Os              pgtype.Text     `json:"os"`
}

func (q *Queries) UpsertCollectorInstance(ctx context.Context, arg UpsertCollectorInstanceParams) (CollectorInstance, error) {
	row := q.db.QueryRow(ctx, upsertCollectorInstance,
		arg.ID,
		arg.CollectorID,
		arg.Name,
		arg.LocalAttributes,
		arg.AlloyVersion,
		arg.Os,
	)
	var i CollectorInstance
	err := row.Scan(
		&i.ID,
		&i.CollectorID,
		&i.Name,
		&i.LocalAttributes,
		&i.AlloyVersion,
		&i.Os,
		&i.LastSeen,
		&i.UnregisteredAt,
		&i.RemoteConfigStatus,
		&i.RemoteConfigError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
