// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collector_instances.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const applySilentPoll = `-- name: ApplySilentPoll :exec
UPDATE collector_instances
SET remote_config_status = CASE
        WHEN $1::bool
          OR remote_config_status IS NULL
          OR remote_config_status IN ('inactive', '') THEN 'APPLIED'
        ELSE remote_config_status
    END,
    remote_config_error = CASE
        WHEN $1::bool
          OR remote_config_status IS NULL
          OR remote_config_status IN ('inactive', '') THEN NULL
        ELSE remote_config_error
    END,
    remote_config_status_hash = $2,
    updated_at                = now()
WHERE id = $3
  AND ($1::bool
       OR remote_config_status IS NULL
       OR remote_config_status IN ('inactive', '')
       OR remote_config_status_hash IS DISTINCT FROM $2)
`

type ApplySilentPollParams struct {
	Loaded     bool        `json:"loaded"`
	PolledHash pgtype.Text `json:"polled_hash"`
	ID         string      `json:"id"`
}

// A poll with no RemoteConfigStatus, whose hash equals what GetConfig served.
// What that silence means is Alloy's rule (remotecfg's
// getRemoteConfigStatusForRequest, v1.20.1): it re-sends a status only when
// the (status, error message) pair CHANGES — not when the config hash does.
// Evidence and captured request sequences: docs/proofs/applied-status.md.
//
//   - loaded = the poll carries effective_config: Alloy sets it only after a
//     successful load, and sends it whenever the loaded config changes, so
//     this is a verified load of the polled hash → APPLIED.
//   - no status ever reported (NULL, ”, or the sweeper's cleared 'inactive')
//     → APPLIED, so a healthy collector that applied before its row was reset
//     does not sit at UNKNOWN forever.
//   - anything else → the status stands: Alloy said nothing because its
//     outcome is unchanged. A FAILED stays FAILED — a new config that fails
//     with the same error is not re-reported (#115, F1) — and its
//     status_hash moves to the polled hash, which is now the config it is
//     failing on.
//
// Writes only when something changes, so a steady fleet does not rewrite
// its rows on every poll.
func (q *Queries) ApplySilentPoll(ctx context.Context, arg ApplySilentPollParams) error {
	_, err := q.db.Exec(ctx, applySilentPoll, arg.Loaded, arg.PolledHash, arg.ID)
	return err
}

const countActiveInstances = `-- name: CountActiveInstances :one
SELECT COUNT(*)::bigint AS total
FROM collector_instances
WHERE unregistered_at IS NULL
  AND (remote_config_status IS NULL OR remote_config_status != 'inactive')
`

// Feeds the shepherd_active_collectors gauge. "Active" is the definition the
// gauge's help text already claimed: registered, not swept to 'inactive'.
// Written as a query rather than derived from a list so the sweeper does not
// pull every instance row once a tick just to count them.
func (q *Queries) CountActiveInstances(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveInstances)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const deleteOldInstances = `-- name: DeleteOldInstances :exec
DELETE FROM collector_instances WHERE last_seen < $1
`

func (q *Queries) DeleteOldInstances(ctx context.Context, lastSeen pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldInstances, lastSeen)
	return err
}

const getCollectorInstanceByID = `-- name: GetCollectorInstanceByID :one
SELECT id, collector_id, name, local_attributes, alloy_version, os, last_seen, unregistered_at, remote_config_status, remote_config_error, created_at, updated_at, remote_config_status_hash FROM collector_instances WHERE id = $1
`

func (q *Queries) GetCollectorInstanceByID(ctx context.Context, id string) (CollectorInstance, error) {
	row := q.db.QueryRow(ctx, getCollectorInstanceByID, id)
	var i CollectorInstance
	err := row.Scan(
		&i.ID,
		&i.CollectorID,
		&i.Name,
		&i.LocalAttributes,
		&i.AlloyVersion,
		&i.Os,
		&i.LastSeen,
		&i.UnregisteredAt,
		&i.RemoteConfigStatus,
		&i.RemoteConfigError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemoteConfigStatusHash,
	)
	return i, err
}

const getLatestCollectorInstanceSummary = `-- name: GetLatestCollectorInstanceSummary :one
SELECT remote_config_status, last_seen, alloy_version, local_attributes FROM collector_instances
WHERE collector_id = $1 AND unregistered_at IS NULL
ORDER BY last_seen DESC
LIMIT 1
`

type GetLatestCollectorInstanceSummaryRow struct {
	RemoteConfigStatus pgtype.Text        `json:"remote_config_status"`
	LastSeen           pgtype.Timestamptz `json:"last_seen"`
	AlloyVersion       pgtype.Text        `json:"alloy_version"`
	LocalAttributes    json.RawMessage    `json:"local_attributes"`
}

// Status, last-seen, and version of the most recently reporting live
// instance for a collector, in a single round trip (used by the collector
// list endpoint instead of N per-row status-only lookups).
func (q *Queries) GetLatestCollectorInstanceSummary(ctx context.Context, collectorID pgtype.UUID) (GetLatestCollectorInstanceSummaryRow, error) {
	row := q.db.QueryRow(ctx, getLatestCollectorInstanceSummary, collectorID)
	var i GetLatestCollectorInstanceSummaryRow
	err := row.Scan(
		&i.RemoteConfigStatus,
		&i.LastSeen,
		&i.AlloyVersion,
		&i.LocalAttributes,
	)
	return i, err
}

const listCollectorInstancesByCollector = `-- name: ListCollectorInstancesByCollector :many
SELECT name, alloy_version, os, last_seen, remote_config_status, remote_config_error, local_attributes
FROM collector_instances
WHERE collector_id = $1 AND unregistered_at IS NULL
ORDER BY last_seen DESC NULLS LAST
`

type ListCollectorInstancesByCollectorRow struct {
	Name               string             `json:"name"`
	AlloyVersion       pgtype.Text        `json:"alloy_version"`
	Os                 pgtype.Text        `json:"os"`
	LastSeen           pgtype.Timestamptz `json:"last_seen"`
	RemoteConfigStatus pgtype.Text        `json:"remote_config_status"`
	RemoteConfigError  pgtype.Text        `json:"remote_config_error"`
	LocalAttributes    json.RawMessage    `json:"local_attributes"`
}

// All live (still-registered) instances reporting under a collector,
// newest last_seen first, for the collector detail view.
func (q *Queries) ListCollectorInstancesByCollector(ctx context.Context, collectorID pgtype.UUID) ([]ListCollectorInstancesByCollectorRow, error) {
	rows, err := q.db.Query(ctx, listCollectorInstancesByCollector, collectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectorInstancesByCollectorRow
	for rows.Next() {
		var i ListCollectorInstancesByCollectorRow
		if err := rows.Scan(
			&i.Name,
			&i.AlloyVersion,
			&i.Os,
			&i.LastSeen,
			&i.RemoteConfigStatus,
			&i.RemoteConfigError,
			&i.LocalAttributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestLocalAttributesByOrg = `-- name: ListLatestLocalAttributesByOrg :many
SELECT DISTINCT ON (ci.collector_id) ci.collector_id, ci.local_attributes
FROM collector_instances ci
JOIN collectors c ON c.id = ci.collector_id
JOIN clusters cl ON cl.id = c.cluster_id
WHERE cl.org_id = $1
  AND ci.unregistered_at IS NULL
ORDER BY ci.collector_id, ci.last_seen DESC NULLS LAST
`

type ListLatestLocalAttributesByOrgRow struct {
	CollectorID     pgtype.UUID     `json:"collector_id"`
	LocalAttributes json.RawMessage `json:"local_attributes"`
}

// The bulk read for Phase 2 org-wide matching (LABEL-MATCHING-PLAN.md §6
// Phase 2 step 1): one query per org-wide Assemble loop (stage3Check,
// previewMatchedCollectors, recomputeOrgCaches), not one per collector --
// the plan's explicitly called-out N+1 risk at ~1000-collector scale. The
// hot path (agentapi's GetConfig) does NOT use this: it already has the
// current request's local_attributes in hand and must use that, not a
// re-query that would reflect the previous heartbeat instead of this one.
//
// DISTINCT ON (collector_id) + last_seen DESC picks each collector's most
// recently reporting live instance, the same "last-seen wins" semantics
// GetLatestCollectorInstanceSummary already uses for one collector, applied
// here to every collector in the org in a single round trip.
//
// Deliberate simplification, decided 2026-09-18 (LABEL-MATCHING-PLAN.md §5):
// this returns one INSTANCE's whole attribute blob, not a true per-key union
// across every live instance a collector has -- docs/spec.md:353 describes
// the latter ("last-seen instance wins per key"). They're the same result
// unless a collector genuinely has more than one concurrently-live instance
// (an HA pair, or briefly during a rolling upgrade) reporting different
// keys, in which case this can make served config flap on whichever key
// differs, depending on poll timing. Accepted for now rather than block on
// it; revisiting means dropping DISTINCT ON to return every live instance
// per collector and folding them per-key in Go -- still one query, more
// rows, not the N+1-by-query-count pattern this query exists to avoid.
func (q *Queries) ListLatestLocalAttributesByOrg(ctx context.Context, orgID pgtype.UUID) ([]ListLatestLocalAttributesByOrgRow, error) {
	rows, err := q.db.Query(ctx, listLatestLocalAttributesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestLocalAttributesByOrgRow
	for rows.Next() {
		var i ListLatestLocalAttributesByOrgRow
		if err := rows.Scan(&i.CollectorID, &i.LocalAttributes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaleInstancesInactive = `-- name: MarkStaleInstancesInactive :exec
UPDATE collector_instances
SET remote_config_status = 'inactive', updated_at = now()
WHERE last_seen < $1
  AND unregistered_at IS NULL
  AND (remote_config_status IS NULL OR remote_config_status NOT IN ('inactive', 'FAILED'))
`

// A FAILED is left alone: 'inactive' is cleared on reconnect and a cleared
// status is promoted to APPLIED by ApplySilentPoll, so marking a failing
// instance inactive would turn its failure into APPLIED once it came back.
func (q *Queries) MarkStaleInstancesInactive(ctx context.Context, lastSeen pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, markStaleInstancesInactive, lastSeen)
	return err
}

const unregisterInstance = `-- name: UnregisterInstance :exec
UPDATE collector_instances
SET unregistered_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UnregisterInstance(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, unregisterInstance, id)
	return err
}

const updateInstanceStatus = `-- name: UpdateInstanceStatus :exec
UPDATE collector_instances
SET remote_config_status      = $2,
    remote_config_error       = $3,
    remote_config_status_hash = $4,
    updated_at                = now()
WHERE id = $1
`

type UpdateInstanceStatusParams struct {
	ID                 string      `json:"id"`
	RemoteConfigStatus pgtype.Text `json:"remote_config_status"`
	RemoteConfigError  pgtype.Text `json:"remote_config_error"`
	StatusHash         pgtype.Text `json:"status_hash"`
}

// remote_config_status_hash records which config the status is about: the
// hash the agent sent alongside it (see 0028).
func (q *Queries) UpdateInstanceStatus(ctx context.Context, arg UpdateInstanceStatusParams) error {
	_, err := q.db.Exec(ctx, updateInstanceStatus,
		arg.ID,
		arg.RemoteConfigStatus,
		arg.RemoteConfigError,
		arg.StatusHash,
	)
	return err
}

const upsertCollectorInstance = `-- name: UpsertCollectorInstance :one
INSERT INTO collector_instances (id, collector_id, name, local_attributes, alloy_version, os, last_seen)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (id) DO UPDATE SET
    collector_id = EXCLUDED.collector_id,
    name         = CASE
                        WHEN (EXCLUDED.name = '' OR EXCLUDED.name = collector_instances.id)
                             AND collector_instances.name <> '' THEN collector_instances.name
                        ELSE COALESCE(NULLIF(EXCLUDED.name, ''), collector_instances.id)
                    END,
    local_attributes = EXCLUDED.local_attributes,
    alloy_version = EXCLUDED.alloy_version,
    os           = EXCLUDED.os,
    last_seen    = now(),
    remote_config_status = CASE
                                WHEN collector_instances.remote_config_status = 'inactive' THEN NULL
                                ELSE collector_instances.remote_config_status
                            END,
    updated_at   = now()
RETURNING id, collector_id, name, local_attributes, alloy_version, os, last_seen, unregistered_at, remote_config_status, remote_config_error, created_at, updated_at, remote_config_status_hash
`

type UpsertCollectorInstanceParams struct {
	ID              string          `json:"id"`
	CollectorID     pgtype.UUID     `json:"collector_id"`
	Name            string          `json:"name"`
	LocalAttributes json.RawMessage `json:"local_attributes"`
	AlloyVersion    pgtype.Text     `json:"alloy_version"`
	Os              pgtype.Text     `json:"os"`
}

// On conflict, an incoming name that is empty or equal to the wire id (both
// signal "caller has no real display name to report, e.g. a bare poll with
// no collector.name attribute") never clobbers a previously-known display
// name — but only when a real display name is actually stored. Otherwise
// (first insert, or a row still carrying an empty name from before this
// fallback existed) fall back to the wire id rather than persist an empty
// name. A successful upsert also counts as liveness recovery: it clears a
// stale 'inactive' status marker left by the lifecycle sweeper so a
// reconnecting instance shows live again.
func (q *Queries) UpsertCollectorInstance(ctx context.Context, arg UpsertCollectorInstanceParams) (CollectorInstance, error) {
	row := q.db.QueryRow(ctx, upsertCollectorInstance,
		arg.ID,
		arg.CollectorID,
		arg.Name,
		arg.LocalAttributes,
		arg.AlloyVersion,
		arg.Os,
	)
	var i CollectorInstance
	err := row.Scan(
		&i.ID,
		&i.CollectorID,
		&i.Name,
		&i.LocalAttributes,
		&i.AlloyVersion,
		&i.Os,
		&i.LastSeen,
		&i.UnregisteredAt,
		&i.RemoteConfigStatus,
		&i.RemoteConfigError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemoteConfigStatusHash,
	)
	return i, err
}
