// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collectors.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCollectorByClusterAndRole = `-- name: GetCollectorByClusterAndRole :one
SELECT c.id, c.cluster_id, c.role, c.created_at, c.updated_at FROM collectors c
JOIN clusters cl ON c.cluster_id = cl.id
WHERE cl.name = $1 AND c.role = $2
`

type GetCollectorByClusterAndRoleParams struct {
	Name string `json:"name"`
	Role string `json:"role"`
}

func (q *Queries) GetCollectorByClusterAndRole(ctx context.Context, arg GetCollectorByClusterAndRoleParams) (Collector, error) {
	row := q.db.QueryRow(ctx, getCollectorByClusterAndRole, arg.Name, arg.Role)
	var i Collector
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollectorByID = `-- name: GetCollectorByID :one
SELECT id, cluster_id, role, created_at, updated_at FROM collectors WHERE id = $1
`

func (q *Queries) GetCollectorByID(ctx context.Context, id pgtype.UUID) (Collector, error) {
	row := q.db.QueryRow(ctx, getCollectorByID, id)
	var i Collector
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollectorOrgID = `-- name: GetCollectorOrgID :one
SELECT cl.org_id FROM collectors c
JOIN clusters cl ON c.cluster_id = cl.id
WHERE c.id = $1
`

func (q *Queries) GetCollectorOrgID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCollectorOrgID, id)
	var org_id pgtype.UUID
	err := row.Scan(&org_id)
	return org_id, err
}

const listCollectorsByOrg = `-- name: ListCollectorsByOrg :many
SELECT c.id, c.cluster_id, c.role, c.created_at, c.updated_at FROM collectors c
JOIN clusters cl ON c.cluster_id = cl.id
WHERE cl.org_id = $1
ORDER BY cl.name, c.role
`

func (q *Queries) ListCollectorsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Collector, error) {
	rows, err := q.db.Query(ctx, listCollectorsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collector
	for rows.Next() {
		var i Collector
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectorsWithClusterByOrg = `-- name: ListCollectorsWithClusterByOrg :many
SELECT c.id, c.cluster_id, c.role, c.created_at, c.updated_at, cl.name AS cluster_name
FROM collectors c
JOIN clusters cl ON c.cluster_id = cl.id
WHERE cl.org_id = $1
ORDER BY cl.name, c.role
`

type ListCollectorsWithClusterByOrgRow struct {
	ID          pgtype.UUID        `json:"id"`
	ClusterID   pgtype.UUID        `json:"cluster_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ClusterName string             `json:"cluster_name"`
}

func (q *Queries) ListCollectorsWithClusterByOrg(ctx context.Context, orgID pgtype.UUID) ([]ListCollectorsWithClusterByOrgRow, error) {
	rows, err := q.db.Query(ctx, listCollectorsWithClusterByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectorsWithClusterByOrgRow
	for rows.Next() {
		var i ListCollectorsWithClusterByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClusterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCollector = `-- name: UpsertCollector :one
INSERT INTO collectors (cluster_id, role)
VALUES ($1, $2)
ON CONFLICT (cluster_id, role) DO UPDATE SET updated_at = now()
RETURNING id, cluster_id, role, created_at, updated_at
`

type UpsertCollectorParams struct {
	ClusterID pgtype.UUID `json:"cluster_id"`
	Role      string      `json:"role"`
}

func (q *Queries) UpsertCollector(ctx context.Context, arg UpsertCollectorParams) (Collector, error) {
	row := q.db.QueryRow(ctx, upsertCollector, arg.ClusterID, arg.Role)
	var i Collector
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
