// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: destination_bindings.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDestinationBinding = `-- name: CreateDestinationBinding :one
INSERT INTO destination_bindings (destination_id, org_id, name, tenant_id)
VALUES ($1, $2, $3, $4)
RETURNING id, destination_id, org_id, name, tenant_id, created_at, updated_at
`

type CreateDestinationBindingParams struct {
	DestinationID pgtype.UUID `json:"destination_id"`
	OrgID         pgtype.UUID `json:"org_id"`
	Name          string      `json:"name"`
	TenantID      string      `json:"tenant_id"`
}

func (q *Queries) CreateDestinationBinding(ctx context.Context, arg CreateDestinationBindingParams) (DestinationBinding, error) {
	row := q.db.QueryRow(ctx, createDestinationBinding,
		arg.DestinationID,
		arg.OrgID,
		arg.Name,
		arg.TenantID,
	)
	var i DestinationBinding
	err := row.Scan(
		&i.ID,
		&i.DestinationID,
		&i.OrgID,
		&i.Name,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDestinationBinding = `-- name: DeleteDestinationBinding :exec
DELETE FROM destination_bindings WHERE id = $1
`

func (q *Queries) DeleteDestinationBinding(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDestinationBinding, id)
	return err
}

const getDestinationBindingByID = `-- name: GetDestinationBindingByID :one
SELECT id, destination_id, org_id, name, tenant_id, created_at, updated_at FROM destination_bindings WHERE id = $1
`

func (q *Queries) GetDestinationBindingByID(ctx context.Context, id pgtype.UUID) (DestinationBinding, error) {
	row := q.db.QueryRow(ctx, getDestinationBindingByID, id)
	var i DestinationBinding
	err := row.Scan(
		&i.ID,
		&i.DestinationID,
		&i.OrgID,
		&i.Name,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResolvedDestinationBinding = `-- name: GetResolvedDestinationBinding :one
SELECT
    b.id                AS binding_id,
    b.name              AS binding_name,
    b.tenant_id         AS tenant_id,
    b.org_id            AS org_id,
    d.id                AS destination_id,
    d.name              AS destination_name,
    d.type              AS type,
    d.url               AS url,
    d.secret_name       AS secret_name,
    d.secret_namespace  AS secret_namespace,
    d.auth_mode         AS auth_mode,
    d.extra             AS extra
FROM destination_bindings b
JOIN destinations d ON d.id = b.destination_id
WHERE b.id = $1
`

type GetResolvedDestinationBindingRow struct {
	BindingID       pgtype.UUID     `json:"binding_id"`
	BindingName     string          `json:"binding_name"`
	TenantID        string          `json:"tenant_id"`
	OrgID           pgtype.UUID     `json:"org_id"`
	DestinationID   pgtype.UUID     `json:"destination_id"`
	DestinationName string          `json:"destination_name"`
	Type            string          `json:"type"`
	Url             string          `json:"url"`
	SecretName      string          `json:"secret_name"`
	SecretNamespace string          `json:"secret_namespace"`
	AuthMode        string          `json:"auth_mode"`
	Extra           json.RawMessage `json:"extra"`
}

// The one query a serving-time consumer should use: the binding's tenant_id
// merged with its template's url/type/secret_name/secret_namespace/auth_mode/
// extra. Never assemble this by hand from a separate GetDestinationBindingByID
// + GetDestinationByID pair -- that seam is exactly where a half-resolved row
// (tenant overridden, credential stale/missing) could leak to a consumer.
func (q *Queries) GetResolvedDestinationBinding(ctx context.Context, id pgtype.UUID) (GetResolvedDestinationBindingRow, error) {
	row := q.db.QueryRow(ctx, getResolvedDestinationBinding, id)
	var i GetResolvedDestinationBindingRow
	err := row.Scan(
		&i.BindingID,
		&i.BindingName,
		&i.TenantID,
		&i.OrgID,
		&i.DestinationID,
		&i.DestinationName,
		&i.Type,
		&i.Url,
		&i.SecretName,
		&i.SecretNamespace,
		&i.AuthMode,
		&i.Extra,
	)
	return i, err
}

const listDestinationBindingsByOrg = `-- name: ListDestinationBindingsByOrg :many
SELECT id, destination_id, org_id, name, tenant_id, created_at, updated_at FROM destination_bindings WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListDestinationBindingsByOrg(ctx context.Context, orgID pgtype.UUID) ([]DestinationBinding, error) {
	rows, err := q.db.Query(ctx, listDestinationBindingsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DestinationBinding
	for rows.Next() {
		var i DestinationBinding
		if err := rows.Scan(
			&i.ID,
			&i.DestinationID,
			&i.OrgID,
			&i.Name,
			&i.TenantID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDestinationBindingsByOrgAndDestination = `-- name: ListDestinationBindingsByOrgAndDestination :many
SELECT id, destination_id, org_id, name, tenant_id, created_at, updated_at FROM destination_bindings WHERE org_id = $1 AND destination_id = $2 ORDER BY name
`

type ListDestinationBindingsByOrgAndDestinationParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	DestinationID pgtype.UUID `json:"destination_id"`
}

func (q *Queries) ListDestinationBindingsByOrgAndDestination(ctx context.Context, arg ListDestinationBindingsByOrgAndDestinationParams) ([]DestinationBinding, error) {
	rows, err := q.db.Query(ctx, listDestinationBindingsByOrgAndDestination, arg.OrgID, arg.DestinationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DestinationBinding
	for rows.Next() {
		var i DestinationBinding
		if err := rows.Scan(
			&i.ID,
			&i.DestinationID,
			&i.OrgID,
			&i.Name,
			&i.TenantID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDestinationBinding = `-- name: UpdateDestinationBinding :one
UPDATE destination_bindings
SET name       = $2,
    tenant_id  = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, destination_id, org_id, name, tenant_id, created_at, updated_at
`

type UpdateDestinationBindingParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	TenantID string      `json:"tenant_id"`
}

// Only name and tenant_id are settable -- see 0008_destination_bindings.up.sql
// and rpc_destination.go:rejectCredentialOverride for why the credential
// fields are not, and cannot be, part of this statement.
func (q *Queries) UpdateDestinationBinding(ctx context.Context, arg UpdateDestinationBindingParams) (DestinationBinding, error) {
	row := q.db.QueryRow(ctx, updateDestinationBinding, arg.ID, arg.Name, arg.TenantID)
	var i DestinationBinding
	err := row.Scan(
		&i.ID,
		&i.DestinationID,
		&i.OrgID,
		&i.Name,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
