// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: destinations.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDestination = `-- name: CreateDestination :one
INSERT INTO destinations (org_id, name, type, url, tenant_id, secret_name, secret_namespace, auth_mode, extra)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, name, type, url, tenant_id, secret_name, secret_namespace, auth_mode, extra, created_at, updated_at
`

type CreateDestinationParams struct {
	OrgID           pgtype.UUID     `json:"org_id"`
	Name            string          `json:"name"`
	Type            string          `json:"type"`
	Url             string          `json:"url"`
	TenantID        string          `json:"tenant_id"`
	SecretName      string          `json:"secret_name"`
	SecretNamespace string          `json:"secret_namespace"`
	AuthMode        string          `json:"auth_mode"`
	Extra           json.RawMessage `json:"extra"`
}

func (q *Queries) CreateDestination(ctx context.Context, arg CreateDestinationParams) (Destination, error) {
	row := q.db.QueryRow(ctx, createDestination,
		arg.OrgID,
		arg.Name,
		arg.Type,
		arg.Url,
		arg.TenantID,
		arg.SecretName,
		arg.SecretNamespace,
		arg.AuthMode,
		arg.Extra,
	)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.TenantID,
		&i.SecretName,
		&i.SecretNamespace,
		&i.AuthMode,
		&i.Extra,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDestination = `-- name: DeleteDestination :exec
DELETE FROM destinations WHERE id = $1
`

func (q *Queries) DeleteDestination(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDestination, id)
	return err
}

const getDestinationByID = `-- name: GetDestinationByID :one
SELECT id, org_id, name, type, url, tenant_id, secret_name, secret_namespace, auth_mode, extra, created_at, updated_at FROM destinations WHERE id = $1
`

func (q *Queries) GetDestinationByID(ctx context.Context, id pgtype.UUID) (Destination, error) {
	row := q.db.QueryRow(ctx, getDestinationByID, id)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.TenantID,
		&i.SecretName,
		&i.SecretNamespace,
		&i.AuthMode,
		&i.Extra,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDestinationsByOrg = `-- name: ListDestinationsByOrg :many
SELECT id, org_id, name, type, url, tenant_id, secret_name, secret_namespace, auth_mode, extra, created_at, updated_at FROM destinations WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListDestinationsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Destination, error) {
	rows, err := q.db.Query(ctx, listDestinationsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Destination
	for rows.Next() {
		var i Destination
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Type,
			&i.Url,
			&i.TenantID,
			&i.SecretName,
			&i.SecretNamespace,
			&i.AuthMode,
			&i.Extra,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDestination = `-- name: UpdateDestination :one
UPDATE destinations
SET name             = $2,
    type             = $3,
    url              = $4,
    tenant_id        = $5,
    secret_name      = $6,
    secret_namespace = $7,
    auth_mode        = $8,
    extra            = $9,
    updated_at       = now()
WHERE id = $1
RETURNING id, org_id, name, type, url, tenant_id, secret_name, secret_namespace, auth_mode, extra, created_at, updated_at
`

type UpdateDestinationParams struct {
	ID              pgtype.UUID     `json:"id"`
	Name            string          `json:"name"`
	Type            string          `json:"type"`
	Url             string          `json:"url"`
	TenantID        string          `json:"tenant_id"`
	SecretName      string          `json:"secret_name"`
	SecretNamespace string          `json:"secret_namespace"`
	AuthMode        string          `json:"auth_mode"`
	Extra           json.RawMessage `json:"extra"`
}

func (q *Queries) UpdateDestination(ctx context.Context, arg UpdateDestinationParams) (Destination, error) {
	row := q.db.QueryRow(ctx, updateDestination,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Url,
		arg.TenantID,
		arg.SecretName,
		arg.SecretNamespace,
		arg.AuthMode,
		arg.Extra,
	)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.TenantID,
		&i.SecretName,
		&i.SecretNamespace,
		&i.AuthMode,
		&i.Extra,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
