// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: git_credentials.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGitCredential = `-- name: CreateGitCredential :one
INSERT INTO git_credentials (
    org_id, name, kind, username,
    ado_org_url, entra_tenant_id, client_id,
    client_secret_enc, secret2_enc,
    provider_config, ssh_known_hosts, ca_cert, tls_insecure_skip_verify
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, org_id, name, ado_org_url, entra_tenant_id, client_id, client_secret_enc, created_at, updated_at, kind, username, secret2_enc, provider_config, ssh_known_hosts, ca_cert, tls_insecure_skip_verify
`

type CreateGitCredentialParams struct {
	OrgID                 pgtype.UUID     `json:"org_id"`
	Name                  string          `json:"name"`
	Kind                  string          `json:"kind"`
	Username              pgtype.Text     `json:"username"`
	AdoOrgUrl             pgtype.Text     `json:"ado_org_url"`
	EntraTenantID         pgtype.Text     `json:"entra_tenant_id"`
	ClientID              pgtype.Text     `json:"client_id"`
	ClientSecretEnc       []byte          `json:"client_secret_enc"`
	Secret2Enc            []byte          `json:"secret2_enc"`
	ProviderConfig        json.RawMessage `json:"provider_config"`
	SshKnownHosts         pgtype.Text     `json:"ssh_known_hosts"`
	CaCert                pgtype.Text     `json:"ca_cert"`
	TlsInsecureSkipVerify bool            `json:"tls_insecure_skip_verify"`
}

func (q *Queries) CreateGitCredential(ctx context.Context, arg CreateGitCredentialParams) (GitCredential, error) {
	row := q.db.QueryRow(ctx, createGitCredential,
		arg.OrgID,
		arg.Name,
		arg.Kind,
		arg.Username,
		arg.AdoOrgUrl,
		arg.EntraTenantID,
		arg.ClientID,
		arg.ClientSecretEnc,
		arg.Secret2Enc,
		arg.ProviderConfig,
		arg.SshKnownHosts,
		arg.CaCert,
		arg.TlsInsecureSkipVerify,
	)
	var i GitCredential
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.AdoOrgUrl,
		&i.EntraTenantID,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.Username,
		&i.Secret2Enc,
		&i.ProviderConfig,
		&i.SshKnownHosts,
		&i.CaCert,
		&i.TlsInsecureSkipVerify,
	)
	return i, err
}

const deleteGitCredential = `-- name: DeleteGitCredential :exec
DELETE FROM git_credentials WHERE id = $1
`

func (q *Queries) DeleteGitCredential(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGitCredential, id)
	return err
}

const getGitCredentialByID = `-- name: GetGitCredentialByID :one
SELECT id, org_id, name, ado_org_url, entra_tenant_id, client_id, client_secret_enc, created_at, updated_at, kind, username, secret2_enc, provider_config, ssh_known_hosts, ca_cert, tls_insecure_skip_verify FROM git_credentials WHERE id = $1
`

func (q *Queries) GetGitCredentialByID(ctx context.Context, id pgtype.UUID) (GitCredential, error) {
	row := q.db.QueryRow(ctx, getGitCredentialByID, id)
	var i GitCredential
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.AdoOrgUrl,
		&i.EntraTenantID,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.Username,
		&i.Secret2Enc,
		&i.ProviderConfig,
		&i.SshKnownHosts,
		&i.CaCert,
		&i.TlsInsecureSkipVerify,
	)
	return i, err
}

const listGitCredentialsByOrg = `-- name: ListGitCredentialsByOrg :many
SELECT id, org_id, name, ado_org_url, entra_tenant_id, client_id, client_secret_enc, created_at, updated_at, kind, username, secret2_enc, provider_config, ssh_known_hosts, ca_cert, tls_insecure_skip_verify FROM git_credentials WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListGitCredentialsByOrg(ctx context.Context, orgID pgtype.UUID) ([]GitCredential, error) {
	rows, err := q.db.Query(ctx, listGitCredentialsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitCredential
	for rows.Next() {
		var i GitCredential
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.AdoOrgUrl,
			&i.EntraTenantID,
			&i.ClientID,
			&i.ClientSecretEnc,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kind,
			&i.Username,
			&i.Secret2Enc,
			&i.ProviderConfig,
			&i.SshKnownHosts,
			&i.CaCert,
			&i.TlsInsecureSkipVerify,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGitCredential = `-- name: UpdateGitCredential :one
UPDATE git_credentials
SET name                     = $2,
    kind                     = $3,
    username                 = $4,
    ado_org_url              = $5,
    entra_tenant_id          = $6,
    client_id                = $7,
    client_secret_enc        = $8,
    secret2_enc              = $9,
    provider_config          = $10,
    ssh_known_hosts          = $11,
    ca_cert                  = $12,
    tls_insecure_skip_verify = $13,
    updated_at               = now()
WHERE id = $1
RETURNING id, org_id, name, ado_org_url, entra_tenant_id, client_id, client_secret_enc, created_at, updated_at, kind, username, secret2_enc, provider_config, ssh_known_hosts, ca_cert, tls_insecure_skip_verify
`

type UpdateGitCredentialParams struct {
	ID                    pgtype.UUID     `json:"id"`
	Name                  string          `json:"name"`
	Kind                  string          `json:"kind"`
	Username              pgtype.Text     `json:"username"`
	AdoOrgUrl             pgtype.Text     `json:"ado_org_url"`
	EntraTenantID         pgtype.Text     `json:"entra_tenant_id"`
	ClientID              pgtype.Text     `json:"client_id"`
	ClientSecretEnc       []byte          `json:"client_secret_enc"`
	Secret2Enc            []byte          `json:"secret2_enc"`
	ProviderConfig        json.RawMessage `json:"provider_config"`
	SshKnownHosts         pgtype.Text     `json:"ssh_known_hosts"`
	CaCert                pgtype.Text     `json:"ca_cert"`
	TlsInsecureSkipVerify bool            `json:"tls_insecure_skip_verify"`
}

func (q *Queries) UpdateGitCredential(ctx context.Context, arg UpdateGitCredentialParams) (GitCredential, error) {
	row := q.db.QueryRow(ctx, updateGitCredential,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Username,
		arg.AdoOrgUrl,
		arg.EntraTenantID,
		arg.ClientID,
		arg.ClientSecretEnc,
		arg.Secret2Enc,
		arg.ProviderConfig,
		arg.SshKnownHosts,
		arg.CaCert,
		arg.TlsInsecureSkipVerify,
	)
	var i GitCredential
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.AdoOrgUrl,
		&i.EntraTenantID,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.Username,
		&i.Secret2Enc,
		&i.ProviderConfig,
		&i.SshKnownHosts,
		&i.CaCert,
		&i.TlsInsecureSkipVerify,
	)
	return i, err
}
