// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grafana_connections.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGrafanaConnection = `-- name: DeleteGrafanaConnection :exec
DELETE FROM grafana_connections WHERE org_id = $1
`

func (q *Queries) DeleteGrafanaConnection(ctx context.Context, orgID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGrafanaConnection, orgID)
	return err
}

const getGrafanaConnectionByOrgID = `-- name: GetGrafanaConnectionByOrgID :one
SELECT id, org_id, base_url, token_enc, created_at, updated_at FROM grafana_connections WHERE org_id = $1
`

func (q *Queries) GetGrafanaConnectionByOrgID(ctx context.Context, orgID pgtype.UUID) (GrafanaConnection, error) {
	row := q.db.QueryRow(ctx, getGrafanaConnectionByOrgID, orgID)
	var i GrafanaConnection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.BaseUrl,
		&i.TokenEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGrafanaConnection = `-- name: UpsertGrafanaConnection :one
INSERT INTO grafana_connections (org_id, base_url, token_enc)
VALUES ($1, $2, $3)
ON CONFLICT (org_id) DO UPDATE SET
    base_url   = EXCLUDED.base_url,
    token_enc  = EXCLUDED.token_enc,
    updated_at = now()
RETURNING id, org_id, base_url, token_enc, created_at, updated_at
`

type UpsertGrafanaConnectionParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	BaseUrl  string      `json:"base_url"`
	TokenEnc []byte      `json:"token_enc"`
}

func (q *Queries) UpsertGrafanaConnection(ctx context.Context, arg UpsertGrafanaConnectionParams) (GrafanaConnection, error) {
	row := q.db.QueryRow(ctx, upsertGrafanaConnection, arg.OrgID, arg.BaseUrl, arg.TokenEnc)
	var i GrafanaConnection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.BaseUrl,
		&i.TokenEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
