// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group_assignments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroupAssignment = `-- name: CreateGroupAssignment :one
INSERT INTO group_assignments (collector_id, group_id, group_display_name)
VALUES ($1, $2, $3)
ON CONFLICT (collector_id, group_id) DO UPDATE SET group_display_name = EXCLUDED.group_display_name
RETURNING id, collector_id, group_id, group_display_name, created_at, updated_at
`

type CreateGroupAssignmentParams struct {
	CollectorID      pgtype.UUID `json:"collector_id"`
	GroupID          string      `json:"group_id"`
	GroupDisplayName string      `json:"group_display_name"`
}

func (q *Queries) CreateGroupAssignment(ctx context.Context, arg CreateGroupAssignmentParams) (GroupAssignment, error) {
	row := q.db.QueryRow(ctx, createGroupAssignment, arg.CollectorID, arg.GroupID, arg.GroupDisplayName)
	var i GroupAssignment
	err := row.Scan(
		&i.ID,
		&i.CollectorID,
		&i.GroupID,
		&i.GroupDisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroupAssignment = `-- name: DeleteGroupAssignment :exec
DELETE FROM group_assignments WHERE collector_id = $1 AND group_id = $2
`

type DeleteGroupAssignmentParams struct {
	CollectorID pgtype.UUID `json:"collector_id"`
	GroupID     string      `json:"group_id"`
}

func (q *Queries) DeleteGroupAssignment(ctx context.Context, arg DeleteGroupAssignmentParams) error {
	_, err := q.db.Exec(ctx, deleteGroupAssignment, arg.CollectorID, arg.GroupID)
	return err
}

const listCollectorIDsByGroupMembership = `-- name: ListCollectorIDsByGroupMembership :many
SELECT DISTINCT collector_id
FROM group_assignments
WHERE group_id = ANY($1::text[])
`

func (q *Queries) ListCollectorIDsByGroupMembership(ctx context.Context, dollar_1 []string) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listCollectorIDsByGroupMembership, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var collector_id pgtype.UUID
		if err := rows.Scan(&collector_id); err != nil {
			return nil, err
		}
		items = append(items, collector_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupAssignmentsByCollector = `-- name: ListGroupAssignmentsByCollector :many
SELECT id, collector_id, group_id, group_display_name, created_at, updated_at FROM group_assignments WHERE collector_id = $1 ORDER BY group_display_name
`

func (q *Queries) ListGroupAssignmentsByCollector(ctx context.Context, collectorID pgtype.UUID) ([]GroupAssignment, error) {
	rows, err := q.db.Query(ctx, listGroupAssignmentsByCollector, collectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupAssignment
	for rows.Next() {
		var i GroupAssignment
		if err := rows.Scan(
			&i.ID,
			&i.CollectorID,
			&i.GroupID,
			&i.GroupDisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
