// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group_assignments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroupAssignment = `-- name: CreateGroupAssignment :one
INSERT INTO group_assignments (collector_id, group_id, group_display_name)
VALUES ($1, $2, $3)
ON CONFLICT (collector_id, group_id) DO UPDATE SET group_display_name = EXCLUDED.group_display_name
RETURNING id, collector_id, group_id, group_display_name, created_at, updated_at
`

type CreateGroupAssignmentParams struct {
	CollectorID      pgtype.UUID `json:"collector_id"`
	GroupID          string      `json:"group_id"`
	GroupDisplayName string      `json:"group_display_name"`
}

func (q *Queries) CreateGroupAssignment(ctx context.Context, arg CreateGroupAssignmentParams) (GroupAssignment, error) {
	row := q.db.QueryRow(ctx, createGroupAssignment, arg.CollectorID, arg.GroupID, arg.GroupDisplayName)
	var i GroupAssignment
	err := row.Scan(
		&i.ID,
		&i.CollectorID,
		&i.GroupID,
		&i.GroupDisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroupAssignment = `-- name: DeleteGroupAssignment :exec
DELETE FROM group_assignments WHERE collector_id = $1 AND group_id = $2
`

type DeleteGroupAssignmentParams struct {
	CollectorID pgtype.UUID `json:"collector_id"`
	GroupID     string      `json:"group_id"`
}

func (q *Queries) DeleteGroupAssignment(ctx context.Context, arg DeleteGroupAssignmentParams) error {
	_, err := q.db.Exec(ctx, deleteGroupAssignment, arg.CollectorID, arg.GroupID)
	return err
}

const listCollectorIDsByGroupMembershipInOrg = `-- name: ListCollectorIDsByGroupMembershipInOrg :many
SELECT DISTINCT ga.collector_id
FROM group_assignments ga
JOIN collectors c ON c.id = ga.collector_id
JOIN clusters cl ON cl.id = c.cluster_id
WHERE ga.group_id = ANY($1::text[])
  AND cl.org_id = $2
`

type ListCollectorIDsByGroupMembershipInOrgParams struct {
	Column1 []string    `json:"column_1"`
	OrgID   pgtype.UUID `json:"org_id"`
}

// Used by internal/auth.authorizeOrgAccess's collector-assignment fallback.
//
// The org filter is load-bearing, not decoration. Without it this asks "does
// this session hold an assignment on ANY collector anywhere", and a viewer with
// one assignment in one org clears the reader floor for EVERY org -- silently,
// because GetMe computes its org list from group matches and never shows the
// extra orgs. The sibling ListTeamsByOrgAndGroups has always been org-scoped;
// this one was not.
func (q *Queries) ListCollectorIDsByGroupMembershipInOrg(ctx context.Context, arg ListCollectorIDsByGroupMembershipInOrgParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listCollectorIDsByGroupMembershipInOrg, arg.Column1, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var collector_id pgtype.UUID
		if err := rows.Scan(&collector_id); err != nil {
			return nil, err
		}
		items = append(items, collector_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupAssignmentsByCollector = `-- name: ListGroupAssignmentsByCollector :many
SELECT id, collector_id, group_id, group_display_name, created_at, updated_at FROM group_assignments WHERE collector_id = $1 ORDER BY group_display_name
`

func (q *Queries) ListGroupAssignmentsByCollector(ctx context.Context, collectorID pgtype.UUID) ([]GroupAssignment, error) {
	rows, err := q.db.Query(ctx, listGroupAssignmentsByCollector, collectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupAssignment
	for rows.Next() {
		var i GroupAssignment
		if err := rows.Scan(
			&i.ID,
			&i.CollectorID,
			&i.GroupID,
			&i.GroupDisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
