// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type AgentToken struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	TokenHash []byte             `json:"token_hash"`
	CreatedBy string             `json:"created_by"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID           int64              `json:"id"`
	At           pgtype.Timestamptz `json:"at"`
	Actor        string             `json:"actor"`
	ActorType    string             `json:"actor_type"`
	OrgID        pgtype.UUID        `json:"org_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   string             `json:"resource_id"`
	Detail       json.RawMessage    `json:"detail"`
}

type BeaconInventory struct {
	ID            pgtype.UUID        `json:"id"`
	TokenID       pgtype.UUID        `json:"token_id"`
	InstanceLabel string             `json:"instance_label"`
	ComponentName string             `json:"component_name"`
	Healthy       bool               `json:"healthy"`
	LastSeen      pgtype.Timestamptz `json:"last_seen"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Cluster struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	OrgID     pgtype.UUID        `json:"org_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Collector struct {
	ID        pgtype.UUID        `json:"id"`
	ClusterID pgtype.UUID        `json:"cluster_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CollectorInstance struct {
	ID                 string             `json:"id"`
	CollectorID        pgtype.UUID        `json:"collector_id"`
	Name               string             `json:"name"`
	LocalAttributes    json.RawMessage    `json:"local_attributes"`
	AlloyVersion       pgtype.Text        `json:"alloy_version"`
	Os                 pgtype.Text        `json:"os"`
	LastSeen           pgtype.Timestamptz `json:"last_seen"`
	UnregisteredAt     pgtype.Timestamptz `json:"unregistered_at"`
	RemoteConfigStatus pgtype.Text        `json:"remote_config_status"`
	RemoteConfigError  pgtype.Text        `json:"remote_config_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Destination struct {
	ID              pgtype.UUID        `json:"id"`
	OrgID           pgtype.UUID        `json:"org_id"`
	Name            string             `json:"name"`
	Type            string             `json:"type"`
	Url             string             `json:"url"`
	TenantID        string             `json:"tenant_id"`
	SecretName      string             `json:"secret_name"`
	SecretNamespace string             `json:"secret_namespace"`
	AuthMode        string             `json:"auth_mode"`
	Extra           json.RawMessage    `json:"extra"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DestinationBinding struct {
	ID            pgtype.UUID        `json:"id"`
	DestinationID pgtype.UUID        `json:"destination_id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	Name          string             `json:"name"`
	TenantID      string             `json:"tenant_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type GitCredential struct {
	ID                    pgtype.UUID        `json:"id"`
	OrgID                 pgtype.UUID        `json:"org_id"`
	Name                  string             `json:"name"`
	AdoOrgUrl             pgtype.Text        `json:"ado_org_url"`
	EntraTenantID         pgtype.Text        `json:"entra_tenant_id"`
	ClientID              pgtype.Text        `json:"client_id"`
	ClientSecretEnc       []byte             `json:"client_secret_enc"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Kind                  string             `json:"kind"`
	Username              pgtype.Text        `json:"username"`
	Secret2Enc            []byte             `json:"secret2_enc"`
	ProviderConfig        json.RawMessage    `json:"provider_config"`
	SshKnownHosts         pgtype.Text        `json:"ssh_known_hosts"`
	CaCert                pgtype.Text        `json:"ca_cert"`
	TlsInsecureSkipVerify bool               `json:"tls_insecure_skip_verify"`
}

type GrafanaConnection struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	BaseUrl   string             `json:"base_url"`
	TokenEnc  []byte             `json:"token_enc"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type GroupAssignment struct {
	ID               pgtype.UUID        `json:"id"`
	CollectorID      pgtype.UUID        `json:"collector_id"`
	GroupID          string             `json:"group_id"`
	GroupDisplayName string             `json:"group_display_name"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Org struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	DisplayName   string             `json:"display_name"`
	AdminGroupID  string             `json:"admin_group_id"`
	ReaderGroupID pgtype.Text        `json:"reader_group_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Pipeline struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	Name          string             `json:"name"`
	Contents      string             `json:"contents"`
	Matchers      json.RawMessage    `json:"matchers"`
	Enabled       bool               `json:"enabled"`
	Source        string             `json:"source"`
	WizardKind    pgtype.Text        `json:"wizard_kind"`
	WizardState   json.RawMessage    `json:"wizard_state"`
	RepoLinkID    pgtype.UUID        `json:"repo_link_id"`
	GitPath       pgtype.Text        `json:"git_path"`
	CreatedBy     string             `json:"created_by"`
	UpdatedBy     string             `json:"updated_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	SanitizedName pgtype.Text        `json:"sanitized_name"`
}

type PipelineRevision struct {
	ID         pgtype.UUID        `json:"id"`
	PipelineID pgtype.UUID        `json:"pipeline_id"`
	Revision   int32              `json:"revision"`
	Contents   string             `json:"contents"`
	Matchers   json.RawMessage    `json:"matchers"`
	Enabled    bool               `json:"enabled"`
	ChangedBy  string             `json:"changed_by"`
	ChangedAt  pgtype.Timestamptz `json:"changed_at"`
	ChangeNote string             `json:"change_note"`
}

type RepoLink struct {
	ID                  pgtype.UUID        `json:"id"`
	OrgID               pgtype.UUID        `json:"org_id"`
	CollectorID         pgtype.UUID        `json:"collector_id"`
	CredentialID        pgtype.UUID        `json:"credential_id"`
	Branch              string             `json:"branch"`
	Path                string             `json:"path"`
	PollIntervalSeconds int32              `json:"poll_interval_seconds"`
	LastSyncedAt        pgtype.Timestamptz `json:"last_synced_at"`
	LastCommit          pgtype.Text        `json:"last_commit"`
	SyncStatus          pgtype.Text        `json:"sync_status"`
	SyncError           pgtype.Text        `json:"sync_error"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	RepoUrl             string             `json:"repo_url"`
}

type ServeCache struct {
	CollectorID pgtype.UUID        `json:"collector_id"`
	Content     string             `json:"content"`
	Hash        string             `json:"hash"`
	ComputedAt  pgtype.Timestamptz `json:"computed_at"`
	Dirty       bool               `json:"dirty"`
}

type Session struct {
	ID             string             `json:"id"`
	UserOid        string             `json:"user_oid"`
	Email          string             `json:"email"`
	DisplayName    string             `json:"display_name"`
	GroupIds       json.RawMessage    `json:"group_ids"`
	IsAppAdmin     bool               `json:"is_app_admin"`
	IDTokenExpires pgtype.Timestamptz `json:"id_token_expires"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Source         string             `json:"source"`
}

type SimulateRun struct {
	ID                       pgtype.UUID        `json:"id"`
	OrgID                    pgtype.UUID        `json:"org_id"`
	Status                   string             `json:"status"`
	Graph                    json.RawMessage    `json:"graph"`
	RequestedDurationSeconds int32              `json:"requested_duration_seconds"`
	CreatedBy                string             `json:"created_by"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	StartedAt                pgtype.Timestamptz `json:"started_at"`
	FinishedAt               pgtype.Timestamptz `json:"finished_at"`
	Rewrites                 json.RawMessage    `json:"rewrites"`
	CapturedSeries           json.RawMessage    `json:"captured_series"`
	CapturedLogLines         json.RawMessage    `json:"captured_log_lines"`
	ComponentHealth          json.RawMessage    `json:"component_health"`
	GateDiagnostics          json.RawMessage    `json:"gate_diagnostics"`
	StderrTail               string             `json:"stderr_tail"`
	ErrorCode                string             `json:"error_code"`
	ErrorMessage             string             `json:"error_message"`
}

type TenantRoute struct {
	ID               pgtype.UUID        `json:"id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	TenantID         string             `json:"tenant_id"`
	Kind             string             `json:"kind"`
	Segment          string             `json:"segment"`
	Status           string             `json:"status"`
	ValidUntil       pgtype.Timestamptz `json:"valid_until"`
	RotatedFromID    pgtype.UUID        `json:"rotated_from_id"`
	GatewayMode      string             `json:"gateway_mode"`
	GatewayName      string             `json:"gateway_name"`
	GatewayNamespace string             `json:"gateway_namespace"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
}
