// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oidc_settings.sql

package sqlc

import (
	"context"
)

const deleteOIDCSettings = `-- name: DeleteOIDCSettings :exec
DELETE FROM oidc_settings WHERE id = true
`

func (q *Queries) DeleteOIDCSettings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOIDCSettings)
	return err
}

const getOIDCSettings = `-- name: GetOIDCSettings :one
SELECT id, enabled, provider, display_name, issuer, client_id, client_secret_enc, redirect_url, scopes, subject_claim, email_claim, name_claim, groups_claim, app_admin_groups, use_graph_groups, graph_base_url, created_at, updated_at, updated_by FROM oidc_settings WHERE id = true
`

func (q *Queries) GetOIDCSettings(ctx context.Context) (OidcSetting, error) {
	row := q.db.QueryRow(ctx, getOIDCSettings)
	var i OidcSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Provider,
		&i.DisplayName,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.RedirectUrl,
		&i.Scopes,
		&i.SubjectClaim,
		&i.EmailClaim,
		&i.NameClaim,
		&i.GroupsClaim,
		&i.AppAdminGroups,
		&i.UseGraphGroups,
		&i.GraphBaseUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertOIDCSettings = `-- name: UpsertOIDCSettings :one
INSERT INTO oidc_settings (
    id, enabled, provider, display_name, issuer, client_id, client_secret_enc,
    redirect_url, scopes, subject_claim, email_claim, name_claim,
    groups_claim, app_admin_groups, use_graph_groups, graph_base_url, updated_by
) VALUES (
    true, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
ON CONFLICT (id) DO UPDATE SET
    enabled           = EXCLUDED.enabled,
    provider          = EXCLUDED.provider,
    display_name      = EXCLUDED.display_name,
    issuer            = EXCLUDED.issuer,
    client_id         = EXCLUDED.client_id,
    client_secret_enc = EXCLUDED.client_secret_enc,
    redirect_url      = EXCLUDED.redirect_url,
    scopes            = EXCLUDED.scopes,
    subject_claim     = EXCLUDED.subject_claim,
    email_claim       = EXCLUDED.email_claim,
    name_claim        = EXCLUDED.name_claim,
    groups_claim      = EXCLUDED.groups_claim,
    app_admin_groups  = EXCLUDED.app_admin_groups,
    use_graph_groups  = EXCLUDED.use_graph_groups,
    graph_base_url    = EXCLUDED.graph_base_url,
    updated_by        = EXCLUDED.updated_by,
    updated_at        = now()
RETURNING id, enabled, provider, display_name, issuer, client_id, client_secret_enc, redirect_url, scopes, subject_claim, email_claim, name_claim, groups_claim, app_admin_groups, use_graph_groups, graph_base_url, created_at, updated_at, updated_by
`

type UpsertOIDCSettingsParams struct {
	Enabled         bool     `json:"enabled"`
	Provider        string   `json:"provider"`
	DisplayName     string   `json:"display_name"`
	Issuer          string   `json:"issuer"`
	ClientID        string   `json:"client_id"`
	ClientSecretEnc []byte   `json:"client_secret_enc"`
	RedirectUrl     string   `json:"redirect_url"`
	Scopes          []string `json:"scopes"`
	SubjectClaim    string   `json:"subject_claim"`
	EmailClaim      string   `json:"email_claim"`
	NameClaim       string   `json:"name_claim"`
	GroupsClaim     string   `json:"groups_claim"`
	AppAdminGroups  []string `json:"app_admin_groups"`
	UseGraphGroups  bool     `json:"use_graph_groups"`
	GraphBaseUrl    string   `json:"graph_base_url"`
	UpdatedBy       string   `json:"updated_by"`
}

func (q *Queries) UpsertOIDCSettings(ctx context.Context, arg UpsertOIDCSettingsParams) (OidcSetting, error) {
	row := q.db.QueryRow(ctx, upsertOIDCSettings,
		arg.Enabled,
		arg.Provider,
		arg.DisplayName,
		arg.Issuer,
		arg.ClientID,
		arg.ClientSecretEnc,
		arg.RedirectUrl,
		arg.Scopes,
		arg.SubjectClaim,
		arg.EmailClaim,
		arg.NameClaim,
		arg.GroupsClaim,
		arg.AppAdminGroups,
		arg.UseGraphGroups,
		arg.GraphBaseUrl,
		arg.UpdatedBy,
	)
	var i OidcSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Provider,
		&i.DisplayName,
		&i.Issuer,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.RedirectUrl,
		&i.Scopes,
		&i.SubjectClaim,
		&i.EmailClaim,
		&i.NameClaim,
		&i.GroupsClaim,
		&i.AppAdminGroups,
		&i.UseGraphGroups,
		&i.GraphBaseUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
