// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (name, display_name, admin_group_id, reader_group_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, display_name, admin_group_id, reader_group_id, created_at, updated_at
`

type CreateOrgParams struct {
	Name          string      `json:"name"`
	DisplayName   string      `json:"display_name"`
	AdminGroupID  string      `json:"admin_group_id"`
	ReaderGroupID pgtype.Text `json:"reader_group_id"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg,
		arg.Name,
		arg.DisplayName,
		arg.AdminGroupID,
		arg.ReaderGroupID,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.AdminGroupID,
		&i.ReaderGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrg = `-- name: DeleteOrg :exec
DELETE FROM orgs WHERE id = $1
`

func (q *Queries) DeleteOrg(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrg, id)
	return err
}

const getOrgByID = `-- name: GetOrgByID :one
SELECT id, name, display_name, admin_group_id, reader_group_id, created_at, updated_at FROM orgs WHERE id = $1
`

func (q *Queries) GetOrgByID(ctx context.Context, id pgtype.UUID) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgByID, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.AdminGroupID,
		&i.ReaderGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgByName = `-- name: GetOrgByName :one
SELECT id, name, display_name, admin_group_id, reader_group_id, created_at, updated_at FROM orgs WHERE name = $1
`

func (q *Queries) GetOrgByName(ctx context.Context, name string) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgByName, name)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.AdminGroupID,
		&i.ReaderGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrgs = `-- name: ListOrgs :many
SELECT id, name, display_name, admin_group_id, reader_group_id, created_at, updated_at FROM orgs ORDER BY name
`

func (q *Queries) ListOrgs(ctx context.Context) ([]Org, error) {
	rows, err := q.db.Query(ctx, listOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Org
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.AdminGroupID,
			&i.ReaderGroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrg = `-- name: UpdateOrg :one
UPDATE orgs
SET display_name    = $2,
    admin_group_id  = $3,
    reader_group_id = $4,
    updated_at      = now()
WHERE id = $1
RETURNING id, name, display_name, admin_group_id, reader_group_id, created_at, updated_at
`

type UpdateOrgParams struct {
	ID            pgtype.UUID `json:"id"`
	DisplayName   string      `json:"display_name"`
	AdminGroupID  string      `json:"admin_group_id"`
	ReaderGroupID pgtype.Text `json:"reader_group_id"`
}

func (q *Queries) UpdateOrg(ctx context.Context, arg UpdateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, updateOrg,
		arg.ID,
		arg.DisplayName,
		arg.AdminGroupID,
		arg.ReaderGroupID,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.AdminGroupID,
		&i.ReaderGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
