// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (name, display_name, admin_group_id, reader_group_id, tenant_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, display_name, admin_group_id, reader_group_id, created_at, updated_at, tenant_id
`

type CreateOrgParams struct {
	Name          string      `json:"name"`
	DisplayName   string      `json:"display_name"`
	AdminGroupID  string      `json:"admin_group_id"`
	ReaderGroupID pgtype.Text `json:"reader_group_id"`
	TenantID      pgtype.Text `json:"tenant_id"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg,
		arg.Name,
		arg.DisplayName,
		arg.AdminGroupID,
		arg.ReaderGroupID,
		arg.TenantID,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.AdminGroupID,
		&i.ReaderGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const deleteOrg = `-- name: DeleteOrg :exec
DELETE FROM orgs WHERE id = $1
`

func (q *Queries) DeleteOrg(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrg, id)
	return err
}

const getOrgByID = `-- name: GetOrgByID :one
SELECT id, name, display_name, admin_group_id, reader_group_id, created_at, updated_at, tenant_id FROM orgs WHERE id = $1
`

func (q *Queries) GetOrgByID(ctx context.Context, id pgtype.UUID) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgByID, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.AdminGroupID,
		&i.ReaderGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const listOrgs = `-- name: ListOrgs :many
SELECT id, name, display_name, admin_group_id, reader_group_id, created_at, updated_at, tenant_id FROM orgs ORDER BY name
`

func (q *Queries) ListOrgs(ctx context.Context) ([]Org, error) {
	rows, err := q.db.Query(ctx, listOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Org
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.AdminGroupID,
			&i.ReaderGroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrgTenantID = `-- name: SetOrgTenantID :one
UPDATE orgs
SET tenant_id  = $2,
    updated_at = now()
WHERE id = $1
  AND tenant_id IS NULL
RETURNING id, name, display_name, admin_group_id, reader_group_id, created_at, updated_at, tenant_id
`

type SetOrgTenantIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.Text `json:"tenant_id"`
}

// Set-once, enforced in SQL rather than only in Go: the WHERE clause updates
// nothing when tenant_id is already set, so a caller trying to CHANGE an
// org's tenant identity gets no row back instead of a silent rewrite.
// Changing it after routes exist would leave every existing HTTPRoute
// injecting a tenant the org no longer claims — the routes keep working and
// keep being wrong, which is the worst shape of all.
func (q *Queries) SetOrgTenantID(ctx context.Context, arg SetOrgTenantIDParams) (Org, error) {
	row := q.db.QueryRow(ctx, setOrgTenantID, arg.ID, arg.TenantID)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.AdminGroupID,
		&i.ReaderGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const updateOrg = `-- name: UpdateOrg :one
UPDATE orgs
SET display_name    = $2,
    admin_group_id  = $3,
    reader_group_id = $4,
    updated_at      = now()
WHERE id = $1
RETURNING id, name, display_name, admin_group_id, reader_group_id, created_at, updated_at, tenant_id
`

type UpdateOrgParams struct {
	ID            pgtype.UUID `json:"id"`
	DisplayName   string      `json:"display_name"`
	AdminGroupID  string      `json:"admin_group_id"`
	ReaderGroupID pgtype.Text `json:"reader_group_id"`
}

func (q *Queries) UpdateOrg(ctx context.Context, arg UpdateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, updateOrg,
		arg.ID,
		arg.DisplayName,
		arg.AdminGroupID,
		arg.ReaderGroupID,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.AdminGroupID,
		&i.ReaderGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}
