// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipeline_revisions.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPipelineRevision = `-- name: CreatePipelineRevision :one
INSERT INTO pipeline_revisions (pipeline_id, revision, contents, matchers, enabled, changed_by, change_note)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, pipeline_id, revision, contents, matchers, enabled, changed_by, changed_at, change_note
`

type CreatePipelineRevisionParams struct {
	PipelineID pgtype.UUID     `json:"pipeline_id"`
	Revision   int32           `json:"revision"`
	Contents   string          `json:"contents"`
	Matchers   json.RawMessage `json:"matchers"`
	Enabled    bool            `json:"enabled"`
	ChangedBy  string          `json:"changed_by"`
	ChangeNote string          `json:"change_note"`
}

func (q *Queries) CreatePipelineRevision(ctx context.Context, arg CreatePipelineRevisionParams) (PipelineRevision, error) {
	row := q.db.QueryRow(ctx, createPipelineRevision,
		arg.PipelineID,
		arg.Revision,
		arg.Contents,
		arg.Matchers,
		arg.Enabled,
		arg.ChangedBy,
		arg.ChangeNote,
	)
	var i PipelineRevision
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Revision,
		&i.Contents,
		&i.Matchers,
		&i.Enabled,
		&i.ChangedBy,
		&i.ChangedAt,
		&i.ChangeNote,
	)
	return i, err
}

const getMaxPipelineRevision = `-- name: GetMaxPipelineRevision :one
SELECT COALESCE(MAX(revision), 0)::int AS max_rev FROM pipeline_revisions WHERE pipeline_id = $1
`

func (q *Queries) GetMaxPipelineRevision(ctx context.Context, pipelineID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxPipelineRevision, pipelineID)
	var max_rev int32
	err := row.Scan(&max_rev)
	return max_rev, err
}

const listPipelineRevisions = `-- name: ListPipelineRevisions :many
SELECT id, pipeline_id, revision, contents, matchers, enabled, changed_by, changed_at, change_note FROM pipeline_revisions WHERE pipeline_id = $1 ORDER BY revision DESC
`

func (q *Queries) ListPipelineRevisions(ctx context.Context, pipelineID pgtype.UUID) ([]PipelineRevision, error) {
	rows, err := q.db.Query(ctx, listPipelineRevisions, pipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PipelineRevision
	for rows.Next() {
		var i PipelineRevision
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.Revision,
			&i.Contents,
			&i.Matchers,
			&i.Enabled,
			&i.ChangedBy,
			&i.ChangedAt,
			&i.ChangeNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
