// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipelines.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPipeline = `-- name: CreatePipeline :one
INSERT INTO pipelines (org_id, name, contents, matchers, enabled, source, wizard_kind, wizard_state, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, org_id, name, contents, matchers, enabled, source, wizard_kind, wizard_state, repo_link_id, git_path, created_by, updated_by, created_at, updated_at, sanitized_name
`

type CreatePipelineParams struct {
	OrgID       pgtype.UUID     `json:"org_id"`
	Name        string          `json:"name"`
	Contents    string          `json:"contents"`
	Matchers    json.RawMessage `json:"matchers"`
	Enabled     bool            `json:"enabled"`
	Source      string          `json:"source"`
	WizardKind  pgtype.Text     `json:"wizard_kind"`
	WizardState json.RawMessage `json:"wizard_state"`
	CreatedBy   string          `json:"created_by"`
	UpdatedBy   string          `json:"updated_by"`
}

func (q *Queries) CreatePipeline(ctx context.Context, arg CreatePipelineParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, createPipeline,
		arg.OrgID,
		arg.Name,
		arg.Contents,
		arg.Matchers,
		arg.Enabled,
		arg.Source,
		arg.WizardKind,
		arg.WizardState,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Contents,
		&i.Matchers,
		&i.Enabled,
		&i.Source,
		&i.WizardKind,
		&i.WizardState,
		&i.RepoLinkID,
		&i.GitPath,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SanitizedName,
	)
	return i, err
}

const deletePipeline = `-- name: DeletePipeline :exec
DELETE FROM pipelines WHERE id = $1
`

func (q *Queries) DeletePipeline(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePipeline, id)
	return err
}

const getPipelineByID = `-- name: GetPipelineByID :one
SELECT id, org_id, name, contents, matchers, enabled, source, wizard_kind, wizard_state, repo_link_id, git_path, created_by, updated_by, created_at, updated_at, sanitized_name FROM pipelines WHERE id = $1
`

func (q *Queries) GetPipelineByID(ctx context.Context, id pgtype.UUID) (Pipeline, error) {
	row := q.db.QueryRow(ctx, getPipelineByID, id)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Contents,
		&i.Matchers,
		&i.Enabled,
		&i.Source,
		&i.WizardKind,
		&i.WizardState,
		&i.RepoLinkID,
		&i.GitPath,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SanitizedName,
	)
	return i, err
}

const getPipelineByOrgAndName = `-- name: GetPipelineByOrgAndName :one
SELECT id, org_id, name, contents, matchers, enabled, source, wizard_kind, wizard_state, repo_link_id, git_path, created_by, updated_by, created_at, updated_at, sanitized_name FROM pipelines WHERE org_id = $1 AND name = $2
`

type GetPipelineByOrgAndNameParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Name  string      `json:"name"`
}

func (q *Queries) GetPipelineByOrgAndName(ctx context.Context, arg GetPipelineByOrgAndNameParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, getPipelineByOrgAndName, arg.OrgID, arg.Name)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Contents,
		&i.Matchers,
		&i.Enabled,
		&i.Source,
		&i.WizardKind,
		&i.WizardState,
		&i.RepoLinkID,
		&i.GitPath,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SanitizedName,
	)
	return i, err
}

const listEnabledPipelinesByOrg = `-- name: ListEnabledPipelinesByOrg :many
SELECT id, org_id, name, contents, matchers, enabled, source, wizard_kind, wizard_state, repo_link_id, git_path, created_by, updated_by, created_at, updated_at, sanitized_name FROM pipelines WHERE org_id = $1 AND enabled = true ORDER BY name
`

func (q *Queries) ListEnabledPipelinesByOrg(ctx context.Context, orgID pgtype.UUID) ([]Pipeline, error) {
	rows, err := q.db.Query(ctx, listEnabledPipelinesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pipeline
	for rows.Next() {
		var i Pipeline
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Contents,
			&i.Matchers,
			&i.Enabled,
			&i.Source,
			&i.WizardKind,
			&i.WizardState,
			&i.RepoLinkID,
			&i.GitPath,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SanitizedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelinesByOrg = `-- name: ListPipelinesByOrg :many
SELECT id, org_id, name, contents, matchers, enabled, source, wizard_kind, wizard_state, repo_link_id, git_path, created_by, updated_by, created_at, updated_at, sanitized_name FROM pipelines WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListPipelinesByOrg(ctx context.Context, orgID pgtype.UUID) ([]Pipeline, error) {
	rows, err := q.db.Query(ctx, listPipelinesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pipeline
	for rows.Next() {
		var i Pipeline
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Contents,
			&i.Matchers,
			&i.Enabled,
			&i.Source,
			&i.WizardKind,
			&i.WizardState,
			&i.RepoLinkID,
			&i.GitPath,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SanitizedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPipelineEnabled = `-- name: SetPipelineEnabled :one
UPDATE pipelines
SET enabled    = $2,
    updated_by = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, org_id, name, contents, matchers, enabled, source, wizard_kind, wizard_state, repo_link_id, git_path, created_by, updated_by, created_at, updated_at, sanitized_name
`

type SetPipelineEnabledParams struct {
	ID        pgtype.UUID `json:"id"`
	Enabled   bool        `json:"enabled"`
	UpdatedBy string      `json:"updated_by"`
}

func (q *Queries) SetPipelineEnabled(ctx context.Context, arg SetPipelineEnabledParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, setPipelineEnabled, arg.ID, arg.Enabled, arg.UpdatedBy)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Contents,
		&i.Matchers,
		&i.Enabled,
		&i.Source,
		&i.WizardKind,
		&i.WizardState,
		&i.RepoLinkID,
		&i.GitPath,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SanitizedName,
	)
	return i, err
}

const updatePipeline = `-- name: UpdatePipeline :one
UPDATE pipelines
SET name       = $2,
    contents   = $3,
    matchers   = $4,
    updated_by = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, org_id, name, contents, matchers, enabled, source, wizard_kind, wizard_state, repo_link_id, git_path, created_by, updated_by, created_at, updated_at, sanitized_name
`

type UpdatePipelineParams struct {
	ID        pgtype.UUID     `json:"id"`
	Name      string          `json:"name"`
	Contents  string          `json:"contents"`
	Matchers  json.RawMessage `json:"matchers"`
	UpdatedBy string          `json:"updated_by"`
}

func (q *Queries) UpdatePipeline(ctx context.Context, arg UpdatePipelineParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, updatePipeline,
		arg.ID,
		arg.Name,
		arg.Contents,
		arg.Matchers,
		arg.UpdatedBy,
	)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Contents,
		&i.Matchers,
		&i.Enabled,
		&i.Source,
		&i.WizardKind,
		&i.WizardState,
		&i.RepoLinkID,
		&i.GitPath,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SanitizedName,
	)
	return i, err
}
