// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repo_links.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRepoLink = `-- name: CreateRepoLink :one
INSERT INTO repo_links (org_id, collector_id, credential_id, project, repository, branch, path, poll_interval_seconds)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, collector_id, credential_id, project, repository, branch, path, poll_interval_seconds, last_synced_at, last_commit, sync_status, sync_error, created_at, updated_at
`

type CreateRepoLinkParams struct {
	OrgID               pgtype.UUID `json:"org_id"`
	CollectorID         pgtype.UUID `json:"collector_id"`
	CredentialID        pgtype.UUID `json:"credential_id"`
	Project             string      `json:"project"`
	Repository          string      `json:"repository"`
	Branch              string      `json:"branch"`
	Path                string      `json:"path"`
	PollIntervalSeconds int32       `json:"poll_interval_seconds"`
}

func (q *Queries) CreateRepoLink(ctx context.Context, arg CreateRepoLinkParams) (RepoLink, error) {
	row := q.db.QueryRow(ctx, createRepoLink,
		arg.OrgID,
		arg.CollectorID,
		arg.CredentialID,
		arg.Project,
		arg.Repository,
		arg.Branch,
		arg.Path,
		arg.PollIntervalSeconds,
	)
	var i RepoLink
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CollectorID,
		&i.CredentialID,
		&i.Project,
		&i.Repository,
		&i.Branch,
		&i.Path,
		&i.PollIntervalSeconds,
		&i.LastSyncedAt,
		&i.LastCommit,
		&i.SyncStatus,
		&i.SyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRepoLink = `-- name: DeleteRepoLink :exec
DELETE FROM repo_links WHERE id = $1
`

func (q *Queries) DeleteRepoLink(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRepoLink, id)
	return err
}

const getRepoLinkByID = `-- name: GetRepoLinkByID :one
SELECT id, org_id, collector_id, credential_id, project, repository, branch, path, poll_interval_seconds, last_synced_at, last_commit, sync_status, sync_error, created_at, updated_at FROM repo_links WHERE id = $1
`

func (q *Queries) GetRepoLinkByID(ctx context.Context, id pgtype.UUID) (RepoLink, error) {
	row := q.db.QueryRow(ctx, getRepoLinkByID, id)
	var i RepoLink
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CollectorID,
		&i.CredentialID,
		&i.Project,
		&i.Repository,
		&i.Branch,
		&i.Path,
		&i.PollIntervalSeconds,
		&i.LastSyncedAt,
		&i.LastCommit,
		&i.SyncStatus,
		&i.SyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueRepoLinks = `-- name: ListDueRepoLinks :many
SELECT id, org_id, collector_id, credential_id, project, repository, branch, path, poll_interval_seconds, last_synced_at, last_commit, sync_status, sync_error, created_at, updated_at FROM repo_links
WHERE last_synced_at IS NULL
   OR last_synced_at + (poll_interval_seconds * interval '1 second') < now()
ORDER BY last_synced_at ASC NULLS FIRST
`

func (q *Queries) ListDueRepoLinks(ctx context.Context) ([]RepoLink, error) {
	rows, err := q.db.Query(ctx, listDueRepoLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoLink
	for rows.Next() {
		var i RepoLink
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CollectorID,
			&i.CredentialID,
			&i.Project,
			&i.Repository,
			&i.Branch,
			&i.Path,
			&i.PollIntervalSeconds,
			&i.LastSyncedAt,
			&i.LastCommit,
			&i.SyncStatus,
			&i.SyncError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoLinksByOrg = `-- name: ListRepoLinksByOrg :many
SELECT id, org_id, collector_id, credential_id, project, repository, branch, path, poll_interval_seconds, last_synced_at, last_commit, sync_status, sync_error, created_at, updated_at FROM repo_links WHERE org_id = $1 ORDER BY created_at
`

func (q *Queries) ListRepoLinksByOrg(ctx context.Context, orgID pgtype.UUID) ([]RepoLink, error) {
	rows, err := q.db.Query(ctx, listRepoLinksByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoLink
	for rows.Next() {
		var i RepoLink
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CollectorID,
			&i.CredentialID,
			&i.Project,
			&i.Repository,
			&i.Branch,
			&i.Path,
			&i.PollIntervalSeconds,
			&i.LastSyncedAt,
			&i.LastCommit,
			&i.SyncStatus,
			&i.SyncError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepoLink = `-- name: UpdateRepoLink :one
UPDATE repo_links
SET credential_id         = $2,
    project               = $3,
    repository            = $4,
    branch                = $5,
    path                  = $6,
    poll_interval_seconds = $7,
    updated_at            = now()
WHERE id = $1
RETURNING id, org_id, collector_id, credential_id, project, repository, branch, path, poll_interval_seconds, last_synced_at, last_commit, sync_status, sync_error, created_at, updated_at
`

type UpdateRepoLinkParams struct {
	ID                  pgtype.UUID `json:"id"`
	CredentialID        pgtype.UUID `json:"credential_id"`
	Project             string      `json:"project"`
	Repository          string      `json:"repository"`
	Branch              string      `json:"branch"`
	Path                string      `json:"path"`
	PollIntervalSeconds int32       `json:"poll_interval_seconds"`
}

func (q *Queries) UpdateRepoLink(ctx context.Context, arg UpdateRepoLinkParams) (RepoLink, error) {
	row := q.db.QueryRow(ctx, updateRepoLink,
		arg.ID,
		arg.CredentialID,
		arg.Project,
		arg.Repository,
		arg.Branch,
		arg.Path,
		arg.PollIntervalSeconds,
	)
	var i RepoLink
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CollectorID,
		&i.CredentialID,
		&i.Project,
		&i.Repository,
		&i.Branch,
		&i.Path,
		&i.PollIntervalSeconds,
		&i.LastSyncedAt,
		&i.LastCommit,
		&i.SyncStatus,
		&i.SyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRepoLinkSync = `-- name: UpdateRepoLinkSync :exec
UPDATE repo_links
SET last_synced_at = now(),
    last_commit    = $2,
    sync_status    = $3,
    sync_error     = $4,
    updated_at     = now()
WHERE id = $1
`

type UpdateRepoLinkSyncParams struct {
	ID         pgtype.UUID `json:"id"`
	LastCommit pgtype.Text `json:"last_commit"`
	SyncStatus pgtype.Text `json:"sync_status"`
	SyncError  pgtype.Text `json:"sync_error"`
}

func (q *Queries) UpdateRepoLinkSync(ctx context.Context, arg UpdateRepoLinkSyncParams) error {
	_, err := q.db.Exec(ctx, updateRepoLinkSync,
		arg.ID,
		arg.LastCommit,
		arg.SyncStatus,
		arg.SyncError,
	)
	return err
}
