// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: serve_cache.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getServeCache = `-- name: GetServeCache :one
SELECT collector_id, content, hash, computed_at, dirty FROM serve_cache WHERE collector_id = $1
`

func (q *Queries) GetServeCache(ctx context.Context, collectorID pgtype.UUID) (ServeCache, error) {
	row := q.db.QueryRow(ctx, getServeCache, collectorID)
	var i ServeCache
	err := row.Scan(
		&i.CollectorID,
		&i.Content,
		&i.Hash,
		&i.ComputedAt,
		&i.Dirty,
	)
	return i, err
}

const markServeCacheDirty = `-- name: MarkServeCacheDirty :exec
UPDATE serve_cache SET dirty = true WHERE collector_id = $1
`

// KEEP: single-collector dirty marking; used in agentapi tests and available for
// targeted per-collector invalidation. Do not remove.
func (q *Queries) MarkServeCacheDirty(ctx context.Context, collectorID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markServeCacheDirty, collectorID)
	return err
}

const markServeCacheDirtyByOrg = `-- name: MarkServeCacheDirtyByOrg :exec
UPDATE serve_cache sc
SET dirty = true
FROM collectors c
JOIN clusters cl ON c.cluster_id = cl.id
WHERE sc.collector_id = c.id AND cl.org_id = $1
`

func (q *Queries) MarkServeCacheDirtyByOrg(ctx context.Context, orgID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markServeCacheDirtyByOrg, orgID)
	return err
}

const upsertServeCacheConditional = `-- name: UpsertServeCacheConditional :one
INSERT INTO serve_cache (collector_id, content, hash, computed_at, dirty)
VALUES ($1, $2, $3, now(), false)
ON CONFLICT (collector_id) DO UPDATE SET
    content     = EXCLUDED.content,
    hash        = EXCLUDED.hash,
    computed_at = now(),
    dirty       = false
WHERE serve_cache.dirty = true
RETURNING collector_id, content, hash, computed_at, dirty
`

type UpsertServeCacheConditionalParams struct {
	CollectorID pgtype.UUID `json:"collector_id"`
	Content     string      `json:"content"`
	Hash        string      `json:"hash"`
}

// Only clears the dirty flag if it is still true at write time (conditional update).
// This prevents a newer dirty-mark from being overwritten by a stale recompute.
func (q *Queries) UpsertServeCacheConditional(ctx context.Context, arg UpsertServeCacheConditionalParams) (ServeCache, error) {
	row := q.db.QueryRow(ctx, upsertServeCacheConditional, arg.CollectorID, arg.Content, arg.Hash)
	var i ServeCache
	err := row.Scan(
		&i.CollectorID,
		&i.Content,
		&i.Hash,
		&i.ComputedAt,
		&i.Dirty,
	)
	return i, err
}
