// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createServiceAccount = `-- name: CreateServiceAccount :one
INSERT INTO service_accounts (org_id, name, capability, token_hash, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, name, capability, token_hash, created_by, revoked_at, created_at, updated_at
`

type CreateServiceAccountParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	Name       string      `json:"name"`
	Capability string      `json:"capability"`
	TokenHash  []byte      `json:"token_hash"`
	CreatedBy  string      `json:"created_by"`
}

func (q *Queries) CreateServiceAccount(ctx context.Context, arg CreateServiceAccountParams) (ServiceAccount, error) {
	row := q.db.QueryRow(ctx, createServiceAccount,
		arg.OrgID,
		arg.Name,
		arg.Capability,
		arg.TokenHash,
		arg.CreatedBy,
	)
	var i ServiceAccount
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Capability,
		&i.TokenHash,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceAccountByID = `-- name: GetServiceAccountByID :one
SELECT id, org_id, name, capability, token_hash, created_by, revoked_at, created_at, updated_at FROM service_accounts WHERE id = $1 AND revoked_at IS NULL
`

// Only an unrevoked row authenticates — a revoked service account's id
// still exists (for audit/history) but GetServiceAccountByID (the lookup
// the auth interceptor uses) treats it as gone, the same "revoked is
// absent, not merely flagged, at the authentication boundary" shape
// agent_tokens' GetAgentTokenByID does not currently enforce at the query
// layer but service_accounts does, deliberately, since this is new code
// with no legacy behavior to preserve.
func (q *Queries) GetServiceAccountByID(ctx context.Context, id pgtype.UUID) (ServiceAccount, error) {
	row := q.db.QueryRow(ctx, getServiceAccountByID, id)
	var i ServiceAccount
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Capability,
		&i.TokenHash,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServiceAccountsByOrg = `-- name: ListServiceAccountsByOrg :many
SELECT id, org_id, name, capability, token_hash, created_by, revoked_at, created_at, updated_at FROM service_accounts WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListServiceAccountsByOrg(ctx context.Context, orgID pgtype.UUID) ([]ServiceAccount, error) {
	rows, err := q.db.Query(ctx, listServiceAccountsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceAccount
	for rows.Next() {
		var i ServiceAccount
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Capability,
			&i.TokenHash,
			&i.CreatedBy,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeServiceAccount = `-- name: RevokeServiceAccount :exec
UPDATE service_accounts SET revoked_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) RevokeServiceAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeServiceAccount, id)
	return err
}
