// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_oid, email, display_name, group_ids, is_app_admin, id_token_expires, expires_at, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_oid, email, display_name, group_ids, is_app_admin, id_token_expires, expires_at, created_at, updated_at, source
`

type CreateSessionParams struct {
	ID             string             `json:"id"`
	UserOid        string             `json:"user_oid"`
	Email          string             `json:"email"`
	DisplayName    string             `json:"display_name"`
	GroupIds       json.RawMessage    `json:"group_ids"`
	IsAppAdmin     bool               `json:"is_app_admin"`
	IDTokenExpires pgtype.Timestamptz `json:"id_token_expires"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	Source         string             `json:"source"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserOid,
		arg.Email,
		arg.DisplayName,
		arg.GroupIds,
		arg.IsAppAdmin,
		arg.IDTokenExpires,
		arg.ExpiresAt,
		arg.Source,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserOid,
		&i.Email,
		&i.DisplayName,
		&i.GroupIds,
		&i.IsAppAdmin,
		&i.IDTokenExpires,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_oid, email, display_name, group_ids, is_app_admin, id_token_expires, expires_at, created_at, updated_at, source FROM sessions WHERE id = $1 AND expires_at > now()
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserOid,
		&i.Email,
		&i.DisplayName,
		&i.GroupIds,
		&i.IsAppAdmin,
		&i.IDTokenExpires,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions
SET group_ids        = $2,
    is_app_admin     = $3,
    id_token_expires = $4,
    expires_at       = $5,
    updated_at       = now()
WHERE id = $1
`

type UpdateSessionParams struct {
	ID             string             `json:"id"`
	GroupIds       json.RawMessage    `json:"group_ids"`
	IsAppAdmin     bool               `json:"is_app_admin"`
	IDTokenExpires pgtype.Timestamptz `json:"id_token_expires"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession,
		arg.ID,
		arg.GroupIds,
		arg.IsAppAdmin,
		arg.IDTokenExpires,
		arg.ExpiresAt,
	)
	return err
}
