// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: simulate_runs.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimQueuedSimulateRun = `-- name: ClaimQueuedSimulateRun :one
UPDATE simulate_runs
SET status = 'running', started_at = now()
WHERE id = (
    SELECT id FROM simulate_runs
    WHERE status = 'queued'
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, org_id, status, graph, requested_duration_seconds, created_by, created_at, started_at, finished_at, rewrites, captured_series, captured_log_lines, component_health, gate_diagnostics, stderr_tail, error_code, error_message
`

// Claims the single oldest queued run for the caller's connection. Callers
// must hold a cluster-wide advisory lock (pg_try_advisory_lock) before
// calling this so MaxConcurrentRuns is enforced regardless of replica count
// — see internal/simulate.RunWorker.
func (q *Queries) ClaimQueuedSimulateRun(ctx context.Context) (SimulateRun, error) {
	row := q.db.QueryRow(ctx, claimQueuedSimulateRun)
	var i SimulateRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Status,
		&i.Graph,
		&i.RequestedDurationSeconds,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Rewrites,
		&i.CapturedSeries,
		&i.CapturedLogLines,
		&i.ComponentHealth,
		&i.GateDiagnostics,
		&i.StderrTail,
		&i.ErrorCode,
		&i.ErrorMessage,
	)
	return i, err
}

const completeSimulateRun = `-- name: CompleteSimulateRun :one
UPDATE simulate_runs
SET status              = $2,
    finished_at         = now(),
    rewrites            = $3,
    captured_series     = $4,
    captured_log_lines  = $5,
    component_health    = $6,
    gate_diagnostics    = $7,
    stderr_tail         = $8,
    error_code          = $9,
    error_message       = $10
WHERE id = $1
RETURNING id, org_id, status, graph, requested_duration_seconds, created_by, created_at, started_at, finished_at, rewrites, captured_series, captured_log_lines, component_health, gate_diagnostics, stderr_tail, error_code, error_message
`

type CompleteSimulateRunParams struct {
	ID               pgtype.UUID     `json:"id"`
	Status           string          `json:"status"`
	Rewrites         json.RawMessage `json:"rewrites"`
	CapturedSeries   json.RawMessage `json:"captured_series"`
	CapturedLogLines json.RawMessage `json:"captured_log_lines"`
	ComponentHealth  json.RawMessage `json:"component_health"`
	GateDiagnostics  json.RawMessage `json:"gate_diagnostics"`
	StderrTail       string          `json:"stderr_tail"`
	ErrorCode        string          `json:"error_code"`
	ErrorMessage     string          `json:"error_message"`
}

func (q *Queries) CompleteSimulateRun(ctx context.Context, arg CompleteSimulateRunParams) (SimulateRun, error) {
	row := q.db.QueryRow(ctx, completeSimulateRun,
		arg.ID,
		arg.Status,
		arg.Rewrites,
		arg.CapturedSeries,
		arg.CapturedLogLines,
		arg.ComponentHealth,
		arg.GateDiagnostics,
		arg.StderrTail,
		arg.ErrorCode,
		arg.ErrorMessage,
	)
	var i SimulateRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Status,
		&i.Graph,
		&i.RequestedDurationSeconds,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Rewrites,
		&i.CapturedSeries,
		&i.CapturedLogLines,
		&i.ComponentHealth,
		&i.GateDiagnostics,
		&i.StderrTail,
		&i.ErrorCode,
		&i.ErrorMessage,
	)
	return i, err
}

const countNonTerminalSimulateRunsByOrg = `-- name: CountNonTerminalSimulateRunsByOrg :one
SELECT count(*) FROM simulate_runs
WHERE org_id = $1 AND status IN ('queued', 'running')
`

func (q *Queries) CountNonTerminalSimulateRunsByOrg(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNonTerminalSimulateRunsByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQueuedSimulateRunsBefore = `-- name: CountQueuedSimulateRunsBefore :one
SELECT count(*) FROM simulate_runs AS sr
WHERE sr.status = 'queued'
  AND sr.created_at < (SELECT created_at FROM simulate_runs AS target WHERE target.id = $1)
`

// Best-effort queue_position for GetRun: how many queued runs sort ahead of
// this one. Not transactionally consistent with the claim loop — see the
// run-API spec's Risks (cosmetic UI progress text only).
func (q *Queries) CountQueuedSimulateRunsBefore(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countQueuedSimulateRunsBefore, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSimulateRun = `-- name: CreateSimulateRun :one
INSERT INTO simulate_runs (org_id, graph, requested_duration_seconds, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, status, graph, requested_duration_seconds, created_by, created_at, started_at, finished_at, rewrites, captured_series, captured_log_lines, component_health, gate_diagnostics, stderr_tail, error_code, error_message
`

type CreateSimulateRunParams struct {
	OrgID                    pgtype.UUID     `json:"org_id"`
	Graph                    json.RawMessage `json:"graph"`
	RequestedDurationSeconds int32           `json:"requested_duration_seconds"`
	CreatedBy                string          `json:"created_by"`
}

func (q *Queries) CreateSimulateRun(ctx context.Context, arg CreateSimulateRunParams) (SimulateRun, error) {
	row := q.db.QueryRow(ctx, createSimulateRun,
		arg.OrgID,
		arg.Graph,
		arg.RequestedDurationSeconds,
		arg.CreatedBy,
	)
	var i SimulateRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Status,
		&i.Graph,
		&i.RequestedDurationSeconds,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Rewrites,
		&i.CapturedSeries,
		&i.CapturedLogLines,
		&i.ComponentHealth,
		&i.GateDiagnostics,
		&i.StderrTail,
		&i.ErrorCode,
		&i.ErrorMessage,
	)
	return i, err
}

const deleteOldSimulateRuns = `-- name: DeleteOldSimulateRuns :exec
DELETE FROM simulate_runs
WHERE status IN ('completed', 'failed', 'expired')
  AND finished_at < now() - make_interval(secs => $1::int)
`

func (q *Queries) DeleteOldSimulateRuns(ctx context.Context, retentionSeconds int32) error {
	_, err := q.db.Exec(ctx, deleteOldSimulateRuns, retentionSeconds)
	return err
}

const expireStaleSimulateRuns = `-- name: ExpireStaleSimulateRuns :many
UPDATE simulate_runs
SET status = 'expired', finished_at = now()
WHERE status IN ('queued', 'running')
  AND created_at < now() - make_interval(secs => $1::int)
RETURNING id, org_id
`

type ExpireStaleSimulateRunsRow struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

// Force-transitions any run still queued/running past its TTL to expired.
// This is also the orphan-reclaim safety net for a worker that dies
// mid-run: the advisory lock releases automatically when its connection
// drops, and the abandoned "running" row simply ages out here.
func (q *Queries) ExpireStaleSimulateRuns(ctx context.Context, ttlSeconds int32) ([]ExpireStaleSimulateRunsRow, error) {
	rows, err := q.db.Query(ctx, expireStaleSimulateRuns, ttlSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpireStaleSimulateRunsRow
	for rows.Next() {
		var i ExpireStaleSimulateRunsRow
		if err := rows.Scan(&i.ID, &i.OrgID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSimulateRunByID = `-- name: GetSimulateRunByID :one
SELECT id, org_id, status, graph, requested_duration_seconds, created_by, created_at, started_at, finished_at, rewrites, captured_series, captured_log_lines, component_health, gate_diagnostics, stderr_tail, error_code, error_message FROM simulate_runs WHERE id = $1
`

// No org_id filter, matching GetPipelineByID: the caller (loadRun in
// rpc_simulate.go) does the org-ownership check in Go and returns NotFound
// on mismatch, mirroring loadPipeline's tenant-isolation shape exactly.
func (q *Queries) GetSimulateRunByID(ctx context.Context, id pgtype.UUID) (SimulateRun, error) {
	row := q.db.QueryRow(ctx, getSimulateRunByID, id)
	var i SimulateRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Status,
		&i.Graph,
		&i.RequestedDurationSeconds,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Rewrites,
		&i.CapturedSeries,
		&i.CapturedLogLines,
		&i.ComponentHealth,
		&i.GateDiagnostics,
		&i.StderrTail,
		&i.ErrorCode,
		&i.ErrorMessage,
	)
	return i, err
}
