// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (org_id, name, idp_group_id)
VALUES ($1, $2, $3)
RETURNING id, org_id, name, idp_group_id, created_at, updated_at
`

type CreateTeamParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	Name       string      `json:"name"`
	IdpGroupID string      `json:"idp_group_id"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.OrgID, arg.Name, arg.IdpGroupID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.IdpGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, org_id, name, idp_group_id, created_at, updated_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.IdpGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeamsByOrg = `-- name: ListTeamsByOrg :many
SELECT id, org_id, name, idp_group_id, created_at, updated_at FROM teams WHERE org_id = $1 ORDER BY name
`

func (q *Queries) ListTeamsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.IdpGroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByOrgAndGroups = `-- name: ListTeamsByOrgAndGroups :many
SELECT id, org_id, name, idp_group_id, created_at, updated_at FROM teams WHERE org_id = $1 AND idp_group_id = ANY($2::text[])
`

type ListTeamsByOrgAndGroupsParams struct {
	OrgID   pgtype.UUID `json:"org_id"`
	Column2 []string    `json:"column_2"`
}

// Used by internal/auth.authorizeOrgAccess's team-membership fallback: is
// this session a member (via IdP group) of any team in this org? A
// non-empty result grants the same reader-equivalent baseline
// group_assignments already grants for collector access — see that
// function's doc comment.
func (q *Queries) ListTeamsByOrgAndGroups(ctx context.Context, arg ListTeamsByOrgAndGroupsParams) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByOrgAndGroups, arg.OrgID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.IdpGroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
