// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_routes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenantRoute = `-- name: CreateTenantRoute :one
INSERT INTO tenant_routes (org_id, tenant_id, kind, segment, gateway_mode, gateway_name, gateway_namespace, rotated_from_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, tenant_id, kind, segment, status, valid_until, rotated_from_id, gateway_mode, gateway_name, gateway_namespace, created_at, updated_at, revoked_at
`

type CreateTenantRouteParams struct {
	OrgID            pgtype.UUID `json:"org_id"`
	TenantID         string      `json:"tenant_id"`
	Kind             string      `json:"kind"`
	Segment          string      `json:"segment"`
	GatewayMode      string      `json:"gateway_mode"`
	GatewayName      string      `json:"gateway_name"`
	GatewayNamespace string      `json:"gateway_namespace"`
	RotatedFromID    pgtype.UUID `json:"rotated_from_id"`
}

func (q *Queries) CreateTenantRoute(ctx context.Context, arg CreateTenantRouteParams) (TenantRoute, error) {
	row := q.db.QueryRow(ctx, createTenantRoute,
		arg.OrgID,
		arg.TenantID,
		arg.Kind,
		arg.Segment,
		arg.GatewayMode,
		arg.GatewayName,
		arg.GatewayNamespace,
		arg.RotatedFromID,
	)
	var i TenantRoute
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.Kind,
		&i.Segment,
		&i.Status,
		&i.ValidUntil,
		&i.RotatedFromID,
		&i.GatewayMode,
		&i.GatewayName,
		&i.GatewayNamespace,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deprecateTenantRoute = `-- name: DeprecateTenantRoute :one
UPDATE tenant_routes
SET status = 'deprecated', valid_until = $2, updated_at = now()
WHERE id = $1 AND status = 'active'
RETURNING id, org_id, tenant_id, kind, segment, status, valid_until, rotated_from_id, gateway_mode, gateway_name, gateway_namespace, created_at, updated_at, revoked_at
`

type DeprecateTenantRouteParams struct {
	ID         pgtype.UUID        `json:"id"`
	ValidUntil pgtype.Timestamptz `json:"valid_until"`
}

func (q *Queries) DeprecateTenantRoute(ctx context.Context, arg DeprecateTenantRouteParams) (TenantRoute, error) {
	row := q.db.QueryRow(ctx, deprecateTenantRoute, arg.ID, arg.ValidUntil)
	var i TenantRoute
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.Kind,
		&i.Segment,
		&i.Status,
		&i.ValidUntil,
		&i.RotatedFromID,
		&i.GatewayMode,
		&i.GatewayName,
		&i.GatewayNamespace,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveTenantRoute = `-- name: GetActiveTenantRoute :one
SELECT id, org_id, tenant_id, kind, segment, status, valid_until, rotated_from_id, gateway_mode, gateway_name, gateway_namespace, created_at, updated_at, revoked_at FROM tenant_routes
WHERE org_id = $1 AND tenant_id = $2 AND kind = $3 AND status = 'active'
`

type GetActiveTenantRouteParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	TenantID string      `json:"tenant_id"`
	Kind     string      `json:"kind"`
}

func (q *Queries) GetActiveTenantRoute(ctx context.Context, arg GetActiveTenantRouteParams) (TenantRoute, error) {
	row := q.db.QueryRow(ctx, getActiveTenantRoute, arg.OrgID, arg.TenantID, arg.Kind)
	var i TenantRoute
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.Kind,
		&i.Segment,
		&i.Status,
		&i.ValidUntil,
		&i.RotatedFromID,
		&i.GatewayMode,
		&i.GatewayName,
		&i.GatewayNamespace,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getTenantRouteByID = `-- name: GetTenantRouteByID :one
SELECT id, org_id, tenant_id, kind, segment, status, valid_until, rotated_from_id, gateway_mode, gateway_name, gateway_namespace, created_at, updated_at, revoked_at FROM tenant_routes WHERE id = $1
`

func (q *Queries) GetTenantRouteByID(ctx context.Context, id pgtype.UUID) (TenantRoute, error) {
	row := q.db.QueryRow(ctx, getTenantRouteByID, id)
	var i TenantRoute
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.Kind,
		&i.Segment,
		&i.Status,
		&i.ValidUntil,
		&i.RotatedFromID,
		&i.GatewayMode,
		&i.GatewayName,
		&i.GatewayNamespace,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listTenantRoutesByOrg = `-- name: ListTenantRoutesByOrg :many
SELECT id, org_id, tenant_id, kind, segment, status, valid_until, rotated_from_id, gateway_mode, gateway_name, gateway_namespace, created_at, updated_at, revoked_at FROM tenant_routes WHERE org_id = $1 ORDER BY tenant_id, kind, created_at DESC
`

func (q *Queries) ListTenantRoutesByOrg(ctx context.Context, orgID pgtype.UUID) ([]TenantRoute, error) {
	rows, err := q.db.Query(ctx, listTenantRoutesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TenantRoute
	for rows.Next() {
		var i TenantRoute
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TenantID,
			&i.Kind,
			&i.Segment,
			&i.Status,
			&i.ValidUntil,
			&i.RotatedFromID,
			&i.GatewayMode,
			&i.GatewayName,
			&i.GatewayNamespace,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeTenantRoute = `-- name: RevokeTenantRoute :one
UPDATE tenant_routes
SET status = 'revoked', revoked_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, org_id, tenant_id, kind, segment, status, valid_until, rotated_from_id, gateway_mode, gateway_name, gateway_namespace, created_at, updated_at, revoked_at
`

func (q *Queries) RevokeTenantRoute(ctx context.Context, id pgtype.UUID) (TenantRoute, error) {
	row := q.db.QueryRow(ctx, revokeTenantRoute, id)
	var i TenantRoute
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.Kind,
		&i.Segment,
		&i.Status,
		&i.ValidUntil,
		&i.RotatedFromID,
		&i.GatewayMode,
		&i.GatewayName,
		&i.GatewayNamespace,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const tenantRouteSegmentExists = `-- name: TenantRouteSegmentExists :one
SELECT EXISTS(SELECT 1 FROM tenant_routes WHERE kind = $1 AND segment = $2) AS exists
`

type TenantRouteSegmentExistsParams struct {
	Kind    string `json:"kind"`
	Segment string `json:"segment"`
}

func (q *Queries) TenantRouteSegmentExists(ctx context.Context, arg TenantRouteSegmentExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, tenantRouteSegmentExists, arg.Kind, arg.Segment)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
