// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::bigint AS total FROM users
`

// Drives the first-run bootstrap: an empty table means nobody can sign in yet.
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (login, email, display_name, password_hash, is_app_admin, must_change_password)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, login, email, display_name, password_hash, is_app_admin, must_change_password, disabled, created_at, updated_at, last_login_at
`

type CreateUserParams struct {
	Login              string `json:"login"`
	Email              string `json:"email"`
	DisplayName        string `json:"display_name"`
	PasswordHash       string `json:"password_hash"`
	IsAppAdmin         bool   `json:"is_app_admin"`
	MustChangePassword bool   `json:"must_change_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Login,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.IsAppAdmin,
		arg.MustChangePassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAppAdmin,
		&i.MustChangePassword,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const deleteOrgMember = `-- name: DeleteOrgMember :exec
DELETE FROM org_members WHERE org_id = $1 AND user_id = $2
`

type DeleteOrgMemberParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteOrgMember(ctx context.Context, arg DeleteOrgMemberParams) error {
	_, err := q.db.Exec(ctx, deleteOrgMember, arg.OrgID, arg.UserID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

// sessions.user_id and org_members cascade, so this ends the user's sessions
// and removes their org roles in the same statement.
func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getOrgMemberRole = `-- name: GetOrgMemberRole :one
SELECT role FROM org_members WHERE org_id = $1 AND user_id = $2
`

type GetOrgMemberRoleParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
}

// The authorization lookup for a local session.
func (q *Queries) GetOrgMemberRole(ctx context.Context, arg GetOrgMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getOrgMemberRole, arg.OrgID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, login, email, display_name, password_hash, is_app_admin, must_change_password, disabled, created_at, updated_at, last_login_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAppAdmin,
		&i.MustChangePassword,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, email, display_name, password_hash, is_app_admin, must_change_password, disabled, created_at, updated_at, last_login_at FROM users WHERE lower(login) = lower($1)
`

// Case-insensitive, matching idx_users_login_lower. Disabled users are returned
// so the caller can distinguish "no such account" from "account disabled" in
// logs while still refusing the login.
func (q *Queries) GetUserByLogin(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAppAdmin,
		&i.MustChangePassword,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT om.org_id, om.role, om.created_at, om.updated_at,
       u.id AS user_id, u.login, u.email, u.display_name, u.is_app_admin, u.disabled
FROM org_members om
JOIN users u ON u.id = om.user_id
WHERE om.org_id = $1
ORDER BY lower(u.login)
`

type ListOrgMembersRow struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UserID      pgtype.UUID        `json:"user_id"`
	Login       string             `json:"login"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	IsAppAdmin  bool               `json:"is_app_admin"`
	Disabled    bool               `json:"disabled"`
}

func (q *Queries) ListOrgMembers(ctx context.Context, orgID pgtype.UUID) ([]ListOrgMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgMembersRow
	for rows.Next() {
		var i ListOrgMembersRow
		if err := rows.Scan(
			&i.OrgID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Login,
			&i.Email,
			&i.DisplayName,
			&i.IsAppAdmin,
			&i.Disabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgMembershipsForUser = `-- name: ListOrgMembershipsForUser :many
SELECT om.org_id, om.role, o.name AS org_name, o.display_name AS org_display_name
FROM org_members om
JOIN orgs o ON o.id = om.org_id
WHERE om.user_id = $1
ORDER BY lower(o.name)
`

type ListOrgMembershipsForUserRow struct {
	OrgID          pgtype.UUID `json:"org_id"`
	Role           string      `json:"role"`
	OrgName        string      `json:"org_name"`
	OrgDisplayName string      `json:"org_display_name"`
}

func (q *Queries) ListOrgMembershipsForUser(ctx context.Context, userID pgtype.UUID) ([]ListOrgMembershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, listOrgMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgMembershipsForUserRow
	for rows.Next() {
		var i ListOrgMembershipsForUserRow
		if err := rows.Scan(
			&i.OrgID,
			&i.Role,
			&i.OrgName,
			&i.OrgDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, login, email, display_name, password_hash, is_app_admin, must_change_password, disabled, created_at, updated_at, last_login_at FROM users ORDER BY lower(login)
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Login,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.IsAppAdmin,
			&i.MustChangePassword,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users
SET password_hash = $2, must_change_password = $3, updated_at = now()
WHERE id = $1
`

type SetUserPasswordParams struct {
	ID                 pgtype.UUID `json:"id"`
	PasswordHash       string      `json:"password_hash"`
	MustChangePassword bool        `json:"must_change_password"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash, arg.MustChangePassword)
	return err
}

const touchUserLogin = `-- name: TouchUserLogin :exec
UPDATE users SET last_login_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) TouchUserLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLogin, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, display_name = $3, is_app_admin = $4, disabled = $5, updated_at = now()
WHERE id = $1
RETURNING id, login, email, display_name, password_hash, is_app_admin, must_change_password, disabled, created_at, updated_at, last_login_at
`

type UpdateUserParams struct {
	ID          pgtype.UUID `json:"id"`
	Email       string      `json:"email"`
	DisplayName string      `json:"display_name"`
	IsAppAdmin  bool        `json:"is_app_admin"`
	Disabled    bool        `json:"disabled"`
}

// Profile and flags only. Passwords go through SetUserPassword so the hash is
// never carried alongside fields a general-purpose update might touch.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.IsAppAdmin,
		arg.Disabled,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAppAdmin,
		&i.MustChangePassword,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const upsertOrgMember = `-- name: UpsertOrgMember :one
INSERT INTO org_members (org_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, user_id) DO UPDATE SET role = EXCLUDED.role, updated_at = now()
RETURNING org_id, user_id, role, created_at, updated_at
`

type UpsertOrgMemberParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) UpsertOrgMember(ctx context.Context, arg UpsertOrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, upsertOrgMember, arg.OrgID, arg.UserID, arg.Role)
	var i OrgMember
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
