package mgmtapi

import (
	"context"
	"errors"

	"connectrpc.com/connect"

	mgmtv1 "shepherd/gen/shepherd/mgmt/v1"
	"shepherd/internal/store/sqlc"
)

// errNotWizardPipeline refuses DetachFromWizard on a pipeline no wizard
// manages (nothing to detach from).
var errNotWizardPipeline = errors.New("this pipeline was not generated by a wizard, so there is nothing to detach it from")

// detachChangeNote is the change note of the revision DetachFromWizard writes.
const detachChangeNote = "detached from wizard"

// DetachFromWizard turns a wizard pipeline into an ordinary editor pipeline
// in place (#262 follow-up): same id, revisions, owner team, matchers and
// enabled state; source "ui", and no wizard kind, wizard state or render
// fingerprint (DetachPipelineFromWizard). From then on a destination update
// neither regenerates it nor refuses because of its hand edits — the
// operator owns its text.
//
// Authorization is UpdatePipeline's: the interceptor admits an org reader
// and authorizeOwnership makes the org-editor-or-owning-team decision. The
// contents and matchers do not change and merge never reads a non-git
// pipeline's source, so the served config is unchanged: no validation gate
// and no serve-cache mark are involved. The row, its revision and the
// pipeline.detach audit row are written in one transaction.
func (s *PipelineService) DetachFromWizard(ctx context.Context, req *connect.Request[mgmtv1.DetachFromWizardRequest]) (*connect.Response[mgmtv1.Pipeline], error) {
	if err := requireWriteAuthorized(ctx); err != nil {
		return nil, err
	}
	p, err := s.loadPipeline(ctx, req.Msg.GetOrgId(), req.Msg.GetId())
	if err != nil {
		return nil, err
	}
	if err := s.authorizeOwnership(ctx, req.Msg.GetOrgId(), pipelineOwnerTeamID(p)); err != nil {
		return nil, err
	}
	if p.Source != "wizard" || !p.WizardKind.Valid {
		return nil, connect.NewError(connect.CodeFailedPrecondition, errNotWizardPipeline)
	}

	actor := actorFromCtx(ctx)
	tx, err := s.store.Pool().Begin(ctx)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, errUpdatePipelineFailed)
	}
	defer func() { _ = tx.Rollback(ctx) }() //nolint:errcheck // no-op once committed
	txQ := s.store.Queries.WithTx(tx)

	updated, err := txQ.DetachPipelineFromWizard(ctx, sqlc.DetachPipelineFromWizardParams{ID: p.ID, UpdatedBy: actor})
	if err != nil {
		s.logger.Error("detach from wizard: update", "err", err)
		return nil, connect.NewError(connect.CodeInternal, errUpdatePipelineFailed)
	}
	if _, err := createPipelineRevisionQ(ctx, txQ, updated, detachChangeNote, actor); err != nil {
		s.logger.Error("detach from wizard: revision", "err", err)
		return nil, connect.NewError(connect.CodeInternal, errUpdatePipelineFailed)
	}
	detail := map[string]string{"wizard_kind": p.WizardKind.String}
	if err := auditInsert(ctx, txQ, actor, "user", p.OrgID, "pipeline.detach", "pipeline", p.ID.String(), detail); err != nil {
		s.logger.Error("detach from wizard: audit", "err", err)
		return nil, connect.NewError(connect.CodeInternal, errUpdatePipelineFailed)
	}
	if err := tx.Commit(ctx); err != nil {
		s.logger.Error("detach from wizard: commit", "err", err)
		return nil, connect.NewError(connect.CodeInternal, errUpdatePipelineFailed)
	}
	return connect.NewResponse(pipelineToProto(updated)), nil
}
